### ISSUE TITLE
Demo里还是1.4版本的JQuery 是否考虑支持1.9

### ISSUE THREAD

**Issue by applesstt** [zTree/zTree_v3#10]

**Comment by TianYongwei** [comment]
@stark-summer  解决了吗

**Comment by Ambince** [comment]
上述的问题，是因为 zNodes需要的是json对象，而不是json字符串。  jQuery.fn.zTree.init($("#treeDemo"), setting, zNodes);  
1.转化json对象 var json = JSON.parse(zNodes);  
2.初始化ztree  jQuery.fn.zTree.init($("#treeDemo"), setting, json);
