### ISSUE TITLE
在较低版本的IE下（入IE8）能否提高ZTREE的加载速度

### ISSUE THREAD

**Issue by doukai** [zTree/zTree_v3#100]
如题，感觉数据量比较的大的情况下，ZTREE有点卡，有没有解决思路？

**Comment by zTree** [comment]
节点总数较大，但每一级节点数量不是很大的情况下，应该不会很卡。  你出现的情况很可能是 某一级下的节点数量就很大。 这种对于低版本IE来说就是噩耗。。。可以考虑分页显示，或延迟加载 ，请参考 Demo 中大数据量演示 的例子：  http://www.ztree.me/v3/demo.php#_402  ； http://www.ztree.me/v3/demo.php#_403

如果你的数据量实在太大，也不能分页，又要适应低版本的IE，那么就换个思路，改变一下需求吧。

**Comment by doukai** [comment]
受教了，非常感谢！
