### ISSUE TITLE
多颗树之间的互动

### ISSUE THREAD

**Issue by icssjs** [zTree/zTree_v3#101]
多颗树之间的互动的时候，第一次拖动子节点到目标节点，如果有父节点的时候，能带一个父节点过去吗，我使用copyNode复制getParentNode的时候会把他整个支干带过去。没有可以调整复制深度的呢？

**Comment by zTree** [comment]
这种需要自行控制， 在 beforeDrop 内 return false， 同时自行clone 节点， 根据自己的需求处理 clone 节点的深度，然后 使用 addNodes 方法添加即可
