### ISSUE TITLE
Add breadcrumb trail option

### ISSUE THREAD

**Issue by Rycochet** [zTree/zTree_v3#102]
Suggestion to add a breadcrumb trail to the selected node (useful option in another program I use regularly)

![example here](http://www.gpsoft.com.au/help/opus11/Media/Opus%2011%20Lister%20-%20Small.png)

This also show's a secondary breadcrumb trail to another node - which would also be useful, but not as important :-)

**Comment by zTree** [comment]
I'm sorry. It can't add to this version.  But I've recorded your suggestion.
