### ISSUE TITLE
getNodeByParam获取的值为null

### ISSUE THREAD

**Issue by skipify** [zTree/zTree_v3#103]
var node = blockObj.getNodeByParam('id',1,null);

node 为null

我使用了异步加载数据，以上代码写在了 callback的 onAsyncSuccess的回调中

**Comment by zTree** [comment]
请确定你的数据id 是 Number 还是 String

**Comment by skipify** [comment]
确定了，string  number 都试过 都不行，怀疑是异步的问题

**Comment by zTree** [comment]
onAsyncSuccess 回调 是已经 异步结束了才触发的， 不应该有这种情况呀？  你确信id=1 的节点已经被加载？？

**Comment by skipify** [comment]
确定加载了 大量的数据几千个 。
我要做权限管理，现在大约2000个栏目，选择了之后保存，编辑的时候想要把之前选中的自动给他选中，就这样的需求

**Comment by zTree** [comment]
你这几千个节点 是一次性 异步加载 进来的，还是 分多次 异步加载的？  如果是一次性异步加载进来也不应该出现问题。。 如果是分多次的话，那么就要考虑了，因为 使用 zTree 的异步模式， 每个节点异步加载子节点完毕后都会触发一次 onAsyncSuccess， 所以如果你有多个节点同时开启异步加载， 那么肯定会触发多次 这个回调的

**Comment by skipify** [comment]
一次加载

**Comment by zTree** [comment]
一次性加载，怎么会有异步的问题呢？？ 我觉得不对呀！ 如果你实在找不到原因，还请你做一个静态的demo 页面， 重现你的bug， 然后发给我，谢谢！ hunter.z@263.net

**Comment by skipify** [comment]
demo已经邮件形式发送，麻烦给看一下 谢谢

**Comment by zTree** [comment]
很明显还是你的数据有问题呀。

1065,1055,1041,1040 这几个是你demo 中需要初始化后勾选的节点id ，但是 在你的 json.php 中根本不存在这几个id 的节点数据， 我在里面添加了 1029 之后， 立刻就能看到有节点被勾选， 因为这个节点是存在的
