### ISSUE TITLE
3.5.18在beforeExpand折叠父节点会造成展开状态异常

### ISSUE THREAD

**Issue by yyjdelete** [zTree/zTree_v3#104]
因为某个地方的代码写错了, 然后发现了个很神奇的事件
在beforeExpand中如果用`zTree.expandNode(zTree.getNodes()[0], false);`之类的代码去折叠了该节点的父节点
会出现节点+/-号显示为'-',状态为已展开, 
但实际上的子节点折叠并不显示的问题

**Comment by zTree** [comment]
在beforeExpand 里面去执行展开、折叠的操作时，请务必 return false; 否则就会导致两个操作。。从而出现异常。
