### ISSUE TITLE
缺了个bower.json文件

### ISSUE THREAD

**Issue by e-cloud** [zTree/zTree_v3#108]

**Comment by zTree** [comment]
目前 zTree 的架构 不需要这个东西吧

**Comment by e-cloud** [comment]
这个跟架构有什么关系，是说插件吗？不过我觉得既然注册到bower上面，应该遵循一下他的规范，声明依赖，声明main文件，声明一下不需要下载的文件之类的，我认为这不是可有可无的。主入口文件可以只写all的文件吧

**Comment by zTree** [comment]
抱歉， 我根本没有去 bower 注册！那肯定不是我

**Comment by zTree** [comment]
在 zTree 官网的 API 页面上有这么一句话： all.js = core + excheck + exedit ( 不包括 exhide );
所以， 如果你不使用 exhide 功能的话， 直接使用 all 就有了主要的全部功能。

**Comment by e-cloud** [comment]
好吧
![image](https://cloud.githubusercontent.com/assets/5255354/10009469/04064f58-6110-11e5-8e7a-c19976a2528d.png) 
那就是一帮热心人帮你注册的

感觉你不待见bower

**Comment by zTree** [comment]
冤枉呀， 不是不待见， 是目前无暇顾及， 之前有人跟我说过让我去 bower 上发布， 我现在顾不过来，所以就没有去 bower 发布。 还望见谅！
