### ISSUE TITLE
有没有方法可以获取树已完成渲染或者说dom元素已全部生成

### ISSUE THREAD

**Issue by e-cloud** [zTree/zTree_v3#110]

**Comment by zTree** [comment]
1. 如果你没有使用异步加载模式，那么init 方法执行后就已经算 zTree 渲染完毕；
2. 如果你使用了异步加载模式，那么要利用 onAsyncSuccess 回调来判断异步加载完成， 触发此回调时，渲染已完成
3. zTree 使用了延迟加载，即 未展开的节点不会生成 dom 元素， 也就是说即使所谓的根节点已经渲染完毕， 父节点如果是未展开的状态时， 子节点的 dom 是不会生成的

**Comment by shihua-guo** [comment]
> 1. 如果你没有使用异步加载模式，那么init 方法执行后就已经算 zTree 渲染完毕；
> 2. 如果你使用了异步加载模式，那么要利用 onAsyncSuccess 回调来判断异步加载完成， 触发此回调时，渲染已完成
> 3. zTree 使用了延迟加载，即 未展开的节点不会生成 dom 元素， 也就是说即使所谓的根节点已经渲染完毕， 父节点如果是未展开的状态时， 子节点的 dom 是不会生成的

在onAsyncSuccess 回调里面，dom并没有渲染完成。请问，如何知道dom渲染完成了呢？因为我需要在dom渲染完成之后，需要做一些处理
