### ISSUE TITLE
How to cancel rename after ENTER, by program instead of ESC?

### ISSUE THREAD

**Issue by Viky-zhang** [zTree/zTree_v3#113]
I rename node by "editName(node)", when press ENTER, then I change file name backstage, if change file name failed, can I cancel rename by program instead of press ESC ?

**Comment by zTree** [comment]
看了一下，您懂汉语， 我就用汉语吧。。。:)  本人英文太差

你这种需求完全可以利用 beforeRename 回调， 判断 isCancel 不是 true 的时候，就 return false；

同时触发你的修改文件名的方法， 当修改后，利用cancelEditName 方法可以根据是否成功，确定设置新名字 还是 恢复旧名字。

**Comment by Viky-zhang** [comment]
后来试了，确实可以。
谢！
