### ISSUE TITLE
整棵树都展开后，expandNode() 有时只折叠图标“+”号，却没有折叠子元素。

### ISSUE THREAD

**Issue by Viky-zhang** [zTree/zTree_v3#115]
最开始想要一个类似expandToLevel()的功能，但没找到，就自行在元素create事件中进行设置，根据level属性进行expandToLevel()展开，但有时发现【只折叠图标“+”号，却没有折叠子元素】（即虚折叠了）。是否bug？还是我自己哪里设置有误？

**Comment by zTree** [comment]
如果你自己添加事件处理展开操作， 那么请在 beforeExpand beforeCollapse 这两个回调中 return false 阻止 zTree 默认事件， 同时 你使用 expandNode 方法的时候 终于 callbackFlag 参数， 设置为 false
