### ISSUE TITLE
async加载所有节点,当节点"isParent":true时异常

### ISSUE THREAD

**Issue by xiilei** [zTree/zTree_v3#116]
我是这样调用的
```javascript
    var setting = {
            async: {
                enable: true,
                url:"nodes.json",
                type:'get',
                dataType:'json'
            }
    };
    $.fn.zTree.init($("#ztree_demo"), setting);
```
nodes.json
```json
[{"id":1,"pId":0,"name":"1"},{"id":2,"pId":1,"name":"2","isParent":true}]
```
这个时候加载出来的第二个节点就无限了

**Comment by WizWebTeam** [comment]
请你修改你的后台 生成节点数据部分的代码吧！ 不要收到请求就返回同样的数据， 至少也要根据是哪个父节点 ，然后才去生成这个父节点下面的子节点数据。。这样肯定不会出现无限的情况

**Comment by zTree** [comment]
请你修改你的后台 生成节点数据部分的代码吧！ 不要收到请求就返回同样的数据， 至少也要根据是哪个父节点 ，然后才去生成这个父节点下面的子节点数据。。这样肯定不会出现无限的情况

**Comment by xiilei** [comment]
我的需求是希望一次得到所有的数据,之后不再请求（当子节点存在时不会再去请求,这个没问题,但当存在属性"isParent":true时就出现了这个问题)

如果 nodes.json 是这样

```json
[{"id":1,"pId":0,"name":"1"},{"id":2,"pId":1,"name":"2"}]
```
就没有问题

**Comment by zTree** [comment]
isParent = true ，说明这是一个父节点， 任何没有子节点的父节点 第一次展开时，都会去默认异步加载其子节点的（开启异步加载模式的时候）； 你这种自定义的需求完全可以根据你自己的数据规则， 利用 beforeAsync 回调进行控制

**Comment by xiilei** [comment]
我明白了，谢谢
