### ISSUE TITLE
表格中的实现

### ISSUE THREAD

**Issue by renxia** [zTree/zTree_v3#117]
![123](https://cloud.githubusercontent.com/assets/2276421/11355711/0bf1a5a6-9292-11e5-8f97-644d966675b8.png)

如附件示例，如果想实现在表格中展现，有没有好的思路呢。
或者说用插件的方式能否容易实现出来

**Comment by zTree** [comment]
很抱歉， 目前 zTree 的 dom 结构不太方便你实现这种需求， 硬要实现的话，就必须要去设置很多图层的宽高。。。会比较麻烦
