### ISSUE TITLE
jquery.ztree.core-3.5.js的1225有问题，会导致多出来一个span，显示为双重checkbox图标。

### ISSUE THREAD

**Issue by yanpengfei** [zTree/zTree_v3#119]
提供的jquery.ztree.core-3.5.js在使用checkbox的情况下，会多一个span出来，但是min.js的文件就不会出现这个问题，请作者确认一下，大概跟踪了一下问题应该出现在jquery.ztree.core-3.5.js的1225行上，多出的span会导致多出来一个checkbox的图标。

**Comment by yanpengfei** [comment]
![1](https://cloud.githubusercontent.com/assets/11885508/11436187/5212f4e4-951d-11e5-8bbf-12c46135f2b8.png)

**Comment by zTree** [comment]
你这种情况貌似是 引入了两次 excheck 导致的吧， 请再检查一下

**Comment by yanpengfei** [comment]
我检查了一下，确实又引入了jquery.ztree.excheck-3.5.js的包，不过用jquery.ztree.core-3.5.js和jquery.ztree.core-3.5.min.js，不是应该是一套代码吗？用min就没事了。

**Comment by zTree** [comment]
按道理不应该出现 压缩和 未压缩 有区别的情况。。。。请你再检查一下， 谢谢！ 我现在比较忙

**Comment by yanpengfei** [comment]
经过确认，我引入的是all的包，确实是重复引用导致的，你的包没有问题~   :+1:

**Comment by zTree** [comment]
非常感谢你的细心！
