### ISSUE TITLE
引用bootstrap后，会造成因节点内容过多，但是不出现滚动条的现象

### ISSUE THREAD

**Issue by zimplexing** [zTree/zTree_v3#120]
引用bootstrap后，节点内容超出ul宽度后，点展开收缩后，会无法出现滚动条。初步定位到是与bootstrap所设置box-sizing:border-box有关，由于这个样式是全局的，通过使用样式补丁的方式修改并不会生效。希望能修改这个下bug

**Comment by zTree** [comment]
你好， css 设置样式 是有 优先级设置的， 请针对你使用的 bootstrap ， 给 .ztree 添加样式，作为补丁，不可能不会生效的。
