### ISSUE TITLE
从当前节点直接获取当前节点的所有父节点

### ISSUE THREAD

**Issue by zhangwei900808** [zTree/zTree_v3#122]
能不能 添加一个方法：从当前节点直接获取当前节点的所有父节点的方法

**Comment by zTree** [comment]
请下载最新版本的 zTree ，treeNode.getPath 方法就能满足你的需求

**Comment by zhangwei900808** [comment]
官网api上没有啊，大神，这个getPath怎么用啊

**Comment by zTree** [comment]
你才是大神呀。。。。在 API 页面的 右下方， treeNode 的部分(treeNode 节点数据详解) 。。。怎么会没有 getPath 方法呢？

**Comment by zhangwei900808** [comment]
好的，谢谢啊
