### ISSUE TITLE
想要在节点上添加一个div里面再输入缩略图和按钮等，怎么实现？

### ISSUE THREAD

**Issue by 754522669** [zTree/zTree_v3#124]
adddiydom可以在每个节点后添加按钮等，我现在想要在节点上添加一个div里面添加缩略图和按钮，怎么实现？我发现如果叶子节点里有换行的话，就被下一个叶子节点遮盖住了，怎么解决？谢谢！

**Comment by zTree** [comment]
请参考：http://my.oschina.net/dyhunter/blog/97535
调整 节点高度的样式， 但是一旦调整高度后， 请设置 showLine 参数为 false， 不要显示连接线， 否则 连接线会显示异常的。
