### ISSUE TITLE
ie9下ztree checkAllNodes(false);方法不起作用？

### ISSUE THREAD

**Issue by zhangwei900808** [zTree/zTree_v3#126]
var ipsegObj = $.fn.zTree.getZTreeObj("ipsegTree");
ipsegObj.checkAllNodes(false);
这段代码在chrome下浏览没有问题，在ie9下就不起作用，怎么解决的？

**Comment by zTree** [comment]
首先请确定是否开启了异步记载模式， 我怀疑可能是 你的异步加载还没有完成就执行勾选造成的
