### ISSUE TITLE
在dataFilter里设置chkDisabled ，使用zTree.checkAllNodes(false)没有效果。

### ISSUE THREAD

**Issue by coolskull** [zTree/zTree_v3#127]
在dataFilter里设置chkDisabled ，使用zTree.checkAllNodes(false)没有效果。

````
  function dataFilter(treeId, parentNode, responseData) {
        if (responseData) {
               for (var i = 1; i < responseData.length; i++) {
                    responseData[i].chkDisabled = responseData[i].disabled;

               }
               return responseData;
         }
 }
````

**Comment by zTree** [comment]
demo/cn/excheck/checkbox_chkDisabled.html
我使用该Demo进行测试， checkAllNodes 方法不会影响已经设置为 disabled 的 checkbox

请你再检查一下你的代码逻辑

**Comment by coolskull** [comment]
关于这个问题，我发了封邮件到你的hunter.z@263.net邮箱，里面有具体的demo,你可以看一下

**Comment by coolskull** [comment]
![image](https://cloud.githubusercontent.com/assets/6679909/12439396/1f695826-bf6b-11e5-934c-26a3576f0990.png)

如果父节点是chkDisabled=true，它的子节点是chkDisabled=false就会有问题

**Comment by zTree** [comment]
非常感谢， 你给的例子定位bug很精准， 已经修复，请下载最新版本的代码，如果有问题请及时告诉我！！
