### ISSUE TITLE
ztree生成多颗树时的问题

### ISSUE THREAD

**Issue by alex86gbk** [zTree/zTree_v3#128]
为了减少id关联，我没有给要显示ztree的DOM加上id。一律用的是父层的节点查找的，如下：

```
var $modal =$('#modal');
var $ztreeNode = $modal.find('.ztree-multiselect .selections');
$.fn.zTree.init($ztreeNode, setting, data);
```

**以上方式在单独生成一棵树时是好的，但同时生成多颗时，树的节点展开就有问题了。树是生成了没错，但是点击展开会触发其他某棵树的展开动作。**

后来只有改用id方式获取ztree节点，如下：

```
var $modal =$('#modal');
var ztreeId = $modal.find('.ztree-multiselect .selections').get(0).id;
$.fn.zTree.init($('#' + ztreeId), setting, data);
```

**Comment by daystory** [comment]
我在整合angularjs的时候，也遇到这个问题，只能曲线救国了。求解决方案

**Comment by zTree** [comment]
不好意思，居然1月份的时候没有注意到这条消息。。。目前的确不支持 init 的时候传入的 jQuery 对象是多个dom 的情况。。。请自己循环单个 init 吧。

**Comment by wobuchizhunao** [comment]
如果循环jquery对象集合，然后初始化，也出现点击+号显示错误的问题，硬要规定个id才行，希望这点可以改善
