### ISSUE TITLE
只要给.ztree li a加一个padding，那么禁止拖拽dropInner: false 就失效了

### ISSUE THREAD

**Issue by aiyuchen** [zTree/zTree_v3#131]
求解决方法

**Comment by zTree** [comment]
很抱歉， 最近工作繁忙，没能及时回复。

你这个问题有点儿小复杂，  早期的样式没有使用 box-sizing 这种， 导致你添加了 padding 后（样式中还有 height 的设置） <a> 标签实际的高度 和获取的高度不匹配。再加上计算位置时的不严谨导致了这个bug。

我已经修正了代码，但你修改样式时还需要适当注意，如果添加 padding 最好配合着去处理 box-sizing 以及 里面已经设置了的 height、line-height 等，保证显示正常，并且 js 计算也正常。

请你去下载最新代码，如有问题请及时联系！ 谢谢
