### ISSUE TITLE
MetroStyle: zTreeDragUL has position "static"

### ISSUE THREAD

**Issue by ctoesca** [zTree/zTree_v3#133]
When we move a item, in METRO STYLE, the element zTreeDragUL has position="static" and appears at the wrong place (bottom of the parent)

The problem is in metroStyle.css: 
CHANGED 
ul.ztreeul.ztreeDragUL{
TO
ul.zTreeDragUL{

ZTREE is a very good plugin !

**Comment by zTree** [comment]
Thank you very much. I have fixed this issue.
