### ISSUE TITLE
ztree通过reAsyncChildNodes刷新节点后，想选中某个节点，这个怎么做啊

### ISSUE THREAD

**Issue by zhangwei900808** [zTree/zTree_v3#135]
ztree通过reAsyncChildNodes刷新节点后，想选中某个节点，这个怎么做啊

**Comment by zTree** [comment]
利用 selectNode 方法，利用 asnycSuccess 回调

**Comment by zhangwei900808** [comment]
我试了啊，当asnycSuccess 成功回调的时候，selectNode会选中紧接的上面的节点(有时会出现这种情况，也不知道是不是bug)，

**Comment by zhangwei900808** [comment]
为什么不能在节点上搞个类似checked=true的属性啊

**Comment by zTree** [comment]
请多调试一下代码， 
请注意：asyncSuccess 是每次异步加载后都会触发的，你需要确认 是哪个父节点的子节点加载完毕，还需要确认你 selectNode 的节点是否是你需要的那个节点。

**Comment by zhangwei900808** [comment]
调试的过程中节点是那个节点，这个没问题，关键是异步加载完的执行成功后的执行选中节点时偶尔会出现选中错的情况，我和同事在猜是不是ztree有延时问题

**Comment by zTree** [comment]
这个完全不需要猜的呀， console 调试输出一下你异步加载完，执行选中的节点数据，再看看 选中的是否你需要选中的 不就知道了？

**Comment by zhangwei900808** [comment]
![qq 20160316165105](https://cloud.githubusercontent.com/assets/4385154/13806564/5d3e5e6e-eb97-11e5-8cd1-345e5aa550f7.jpg)
![qq 20160316165026](https://cloud.githubusercontent.com/assets/4385154/13806562/5d29328c-eb97-11e5-895b-cf7334b669d7.jpg)
![Uploading QQ截图20160316164952.jpg…]()

**Comment by zTree** [comment]
1、请检查代码，是否有其他地方进行了 selectNode 操作
2、请利用 console.log把你执行 selectNode 方法时的 节点数据输出， 以便你查找问题

为了避免问题1 引起的错误，请直接使用 zTree 未压缩版本，在 selectNode 方法内添加 console.log 输出调试

**Comment by zhangwei900808** [comment]
![qq 20160316165553](https://cloud.githubusercontent.com/assets/4385154/13806684/fbc7bb2a-eb97-11e5-875d-e98f5653862c.jpg)

**Comment by zTree** [comment]
如果把你 44 行代码屏蔽，是否还会有 选中操作？ 这是用于合适 前面说的问题1 的情况

**Comment by zhangwei900808** [comment]
没有选中，这个是没问题的

**Comment by zhangwei900808** [comment]
我在想为什么传的是对的节点，选中的却是其它结点，是不是有bug

**Comment by zTree** [comment]
这个如果有bug， 那么所有执行 selectNode 的时候都会出错呀， 通过 节点的 tId 找到dom 设置 class； 
请你使用 console.log(selectNode) 进行输出，看看到底 selectNode 方法被执行了多少次。。。

**Comment by zhangwei900808** [comment]
哦哦，我试试

**Comment by zTree** [comment]
貌似我估计到另一个原因了。。。。你的 selectNode 到底是从何而来？？？ 如果是树 刷新前保存下来的， 然后你让整棵树从新刷新。。。。。那样肯定有问题呀

**Comment by zTree** [comment]
如果你的树是重新刷新的， 那么你应该用zTree 的 getNodeByParam 方法，通过节点的 id 去重新找到这个节点。  因为 zTree 内部的 tId 只是一个序列数值， 并不能保证同一个节点在每次刷新后都能严格保证同一个值

**Comment by zhangwei900808** [comment]
是的，是刷新前的

**Comment by zhangwei900808** [comment]
好吧，那 我知道怎么解决了

**Comment by zTree** [comment]
哈哈，终于知道原因了。。分分钟你就能解决啦！

**Comment by zhangwei900808** [comment]
话说，你搞个属性：selected:true不更好吗

**Comment by zTree** [comment]
这个问题暂且不谈了吧，一句话说不清楚。。。目前不会增加这东西了，抱歉。 以后完全重做的话可能会考虑

**Comment by zhangwei900808** [comment]
哦哦，不过今天谢谢你了^_^
