### ISSUE TITLE
selectNode 选中节点

### ISSUE THREAD

**Issue by doocal** [zTree/zTree_v3#136]
selectNode 选中节点 导致节点跳动。

![jdfw](https://cloud.githubusercontent.com/assets/2017549/13834083/f8a88bb0-ec26-11e5-96bd-96d90e00757d.gif)

**Comment by zTree** [comment]
1、请核实你使用的 zTree 版本 是否 目前的最新版
2、请检查样式，是否出现由于样式冲突导致的问题？ 

看看如果只使用 zTree 自己的样式，是否会出现此情况？

**Comment by doocal** [comment]
@zTree 
1、最新版：v3.5.22
2、检查未发现是样式问题导致

**Comment by zTree** [comment]
多谢，确定是 scrollIntoView 部分的问题导致， 这几天抽空修正！

**Comment by zTree** [comment]
抱歉， 本周工作任务较多， 再拖延一周吧。。。非常抱歉！

**Comment by zTree** [comment]
非常抱歉让你等了这么久。。。

1、由于 zTree 树形的特殊情况， 不同项目里使用完全不同， 既 到底滚动条是出现在某个 div 内 还是在 body 上。。所以几乎不可能使用 js 去计算。
2、我增加了 scrollIntoViewIfNeeded 方法的支持， 但这个方法只支持 chrome
3、我给 selectNode 方法增加了 isSilent 参数，你可以设置此参数为 true ，滚动条就不会自动滚动了

请你去下载最新代码，测试一下，有问题请与我联系，谢谢。
