### ISSUE TITLE
zTree的实现能力问题

### ISSUE THREAD

**Issue by zhangjiaqing** [zTree/zTree_v3#138]
![qq 20160323143905](https://cloud.githubusercontent.com/assets/13639247/13986727/f56cf2de-f13e-11e5-82da-d3e489108c59.jpg)

zTree能实现上图所示的效果么？

**Comment by zTree** [comment]
十分抱歉，目前的 zTree 不支持这种格式， 你这种请去寻找 思维脑图 的 插件
