### ISSUE TITLE
title  提标信息最好支持点位符替换

### ISSUE THREAD

**Issue by doocal** [zTree/zTree_v3#139]
var setting = {
	data: {
		key: {
			title: "fullName"
		}
	}
};

目前配置是这样，灵活灵稍差了些。目前想实现提示一种是后台处理，一种是前台自带的过滤器处理，不好。

最好支持：title: "ID:{id} \n Name:{name}"

**Comment by zTree** [comment]
不好意思，暂且将就一下吧。 当初考虑的不妥善，也不全面。 

等啥时候工作不忙的时候， 我还是打算让 zTree 脱胎换骨一下比较好。。。你的建议我会考虑的。

我倒觉得支持 function 让用户自己去拼凑是不是更灵活一些？？

**Comment by doocal** [comment]
@zTree   支持 fun 挺好，更灵活。

**Comment by wxxcarl** [comment]
为什么不能给没个结点设置单独的title？只能设置统一的吗？
`$.each(list,function(i,e){`
`	treeList.push({"id":e.id,"pId":e.parentId,"name":e.name,"field":e.field,"title":e.title});`
`});`
而且我发现最新版本的，在settings里面配置data.key.title，实际效果是"undefined"

**Comment by zTree** [comment]
@wxxcarl   
1、什么叫做 单独的 title； 每个节点数据中的 title 不算 单独的么？ 还是说 每个节点的 title 的数据都放在不同的 节点数据属性中？ a.title01;  b.title02？ 如果是这样的话， 我肯定很难实现
2、请参考API 和Demo， 做做测试， title 如果你不设定， 则直接把 name 拿来当作 title； 如果你设置了的属性不存在，那么肯定就是 undefined 了

**Comment by wxxcarl** [comment]
哦，是我理解错误，api里面的“fullName”是属性，我以为是字符串。如我之前发的代码，我只要设置titie:"title"就可以了
