### ISSUE TITLE
cookies persistence

### ISSUE THREAD

**Issue by joankent** [zTree/zTree_v3#140]
hi, how I can use the cookies persistence in the z-tree when the page is reloaded?

thanks.

**Comment by zTree** [comment]
Hello. 

zTree don't provide these interface. You can achieve it by your self.

**Comment by mibamur** [comment]
@joankent solved here https://github.com/zTree/zTree_v3/issues/154

**Comment by joankent** [comment]
Thanks Michael for the answer, after several weeks than I was waiting for,
sorry by the way, but I decided by dynatree plugin, it's better and 100%
recommended :)

Regards.

J.

**Comment by mibamur** [comment]
@joankent https://github.com/mar10/fancytree/

**Comment by zTree** [comment]
Good,  select what you want.
