### ISSUE TITLE
TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode f

### ISSUE THREAD

**Issue by sunnysk** [zTree/zTree_v3#143]
我在chrome浏览器下。本地测试demo可以正常启动。放到服务器环境测试
jquery.ztree.core.js:820Uncaught TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to themclone @ jquery.ztree.core.js:820init @ jquery.ztree.core.js:1575(anonymous function) @ test.html:63fire @ jquery.js:3232self.fireWith @ jquery.js:3362jQuery.extend.ready @ jquery.js:3582completed @ jquery.js:3617

**Comment by zTree** [comment]
你的系统环境中可能使用了严格模式 user strict； zTree 的 core 代码中有使用到 arguments.callee 导致出错。 以前还真没强行要求使用  严格模式，估计用户们也都没有这么使用过，所以一直没有报这种错误。

请你去下载最新代码， 我刚才修改了一下，你试试看吧，如果没问题就 close， 有问题就继续告诉我！ 多谢！

**Comment by sunnysk** [comment]
刚才下载了代码，已经ok了。我是用gulp + browser-sync搭建的本地静态服务，不知道为什么会是严格模式运行的。这个我需要再查查看。十分感谢了

**Comment by xjchenhao** [comment]
@zTree 你好，我是用webpack搭建的，也遇到了这个问题诶，下载了最新的2.0.14还是报错。
`Uncaught TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them`

**Comment by zTree** [comment]
你用的是最新版的 zTree 么？

**Comment by lixiansky** [comment]
@zTree 好像现在还有这个问题，在webpack下

**Comment by zTree** [comment]
首先请确认你用的什么版本的 zTree？
