### ISSUE TITLE
IE8 浏览器，严格模式下点击展开操作提示堆栈溢出

### ISSUE THREAD

**Issue by sunnysk** [zTree/zTree_v3#144]
首先说下我这里严格模式产生原因，因为项目其他js应用到了ES6语法，所以在gulp执行scripts相关任务时候用到了babel来做转化，默认把ztreejs中也嵌入了 ‘use strict’ ， IE9无此问题
在IE8下，点击展开操作时候错误提示如下：

SCRIPT28: 堆栈溢出 
jquery.ztree.core.js, 行1153 字符21

**Comment by zTree** [comment]
这个情况很难确定， 建议你把你的数据 以及 你的框架编译成一套静态文件， 做成Demo 那样，可以重现bug 的，然后发给我，我再去调试确定问题

**Comment by zTree** [comment]
不过话说，你们都玩儿到 ES6，用上 babel了，还要支持 ie8.....有点儿苦逼了呀。。。我重构 zTree 的时候，绝对不考虑 ie 10以下的浏览器了

**Comment by sunnysk** [comment]
实际上就我一个人造，给我从别的组调来支援的前端连命令行cd进入文件夹命令都不知道。我很心塞。demo我发您邮件了。您看一下。

**Comment by zTree** [comment]
找到原因了：

下面这个是源码
```javascript
expandCollapseNode: function(..., callback) {
//...
var _callback = callback;
callback = function () {
    if (_callback) _callback();
    //...
};
//...
}
```

到了你的系统里面， 代码被处理后，上面这部分就变成了下面这样：
```javascript
expandCollapseNode: function expandCollapseNode(..., callback) {
//...
var _callback = callback;
callback = function callback() {
    if (_callback) _callback();
    //...
};
//...
}
```

很明显，在 IE8 内 callback 会首先被初始化为 function， 导致 callback 不断地自己调用自己。。所以就完蛋了！！

顺便我也反思一下，当初写这个的时候，我的认识也不深入，所以才会导致这种情况， 请你去下载最新代码，我重构一下这部分，你再看看。

**Comment by sunnysk** [comment]
没问题了。周末没有上网。
