### ISSUE TITLE
为何不设计beforeAddnode这样的事件？

### ISSUE THREAD

**Issue by 0704681032** [zTree/zTree_v3#145]
我该如何自定义新增节点的名字

场景如下,点击+号 新增一个节点的时候,我首先去后台取数据,得到这个新增节点的名字,然后出现这个节点

**Comment by zTree** [comment]
新增节点本来就是你自己去触发新增的， 干嘛还要设计个 beforeAddNode 呢？ 你新增节点操作时，就自己先去后台取数据，然后再新增不就可以了？
