### ISSUE TITLE
勾选父节点，子节点被选中却未触发子节点的onCheck函数

### ISSUE THREAD

**Issue by javyuan** [zTree/zTree_v3#146]
设置如下：
`	var setting = {
			check: {
				enable: true,
				chkboxType: { "Y": "s", "N": "s" }
			},
			view: {
				showIcon: true,
				nameIsHTML:true
			},
			callback: {
				onCheck: zTreeOnCheck
			}
	};
`

方法如下：
`
	function zTreeOnCheck(event, treeId, treeNode) {
		alert(treeNode.tId + ", " + treeNode.name + "," + treeNode.checked);
	        .....
	};
`
勾选父节点后，只触发了父节点的onCheck函数，但并没有触发子节点的onCheck函数，如何设置可以触发子节点的onCheck函数？

**Comment by zTree** [comment]
setting.check.autoCheckTrigger
