### ISSUE TITLE
创建新节点的问题

### ISSUE THREAD

**Issue by YourWildDad** [zTree/zTree_v3#147]
当我通过调用 `treeObj.addNodes()` 时,如果此时父节点下有子节点时会出现创建了两个的情况

[![b6c1c74f5be9361ec5ccf5fcce112a2a.png](https://dn-imgloli.qbox.me/images/2016/04/27/b6c1c74f5be9361ec5ccf5fcce112a2a.png)](https://img.myhloli.com/image/nSisx)

[![c531ba1ccc2988b76f848dfae9331946.png](https://dn-imgloli.qbox.me/images/2016/04/27/c531ba1ccc2988b76f848dfae9331946.png)](https://img.myhloli.com/image/nSy0A)

[![c48d42500d88bb9c05a3abb5a973f92e.png](https://dn-imgloli.qbox.me/images/2016/04/27/c48d42500d88bb9c05a3abb5a973f92e.png)](https://img.myhloli.com/image/nStSi)

代码如下: 
```javascript
...
var node = treeObj.getSelectedNodes()[0];
var newNode = {
    name: '新建选项组' + ++optionGroupCount,
    id: node.id + '/新建选项组' + optionGroupCount,
    PId: node.id,
    type: 'OptionGroup',
    iconSkin: 'option-group',
    // isParent: false,
    oldName: '新建选项组'
};
$.post('someurl', {
    data: somedata
    }, function(r) {
        var rsp = JSON.parse(r);
        if (r && rsp.message === 'SUCCESS') {
            var newNodepost = zTree.addNodes(node, newNode);
            // setTimeout(function() {
            //     zTree.selectNode(newNodepost[0]);
            //     zTree.editName(newNodepost[0]);
            // }, 200);
    }
});
...
```

希望能够得到答复,祝越办越好

**Comment by zTree** [comment]
异步加载的情况下， 如果 给没有加载子节点的父节点使用 addNodes 方法，会先去ajax 加载子节点，然后再执行添加操作。 

所以请你判断父节点是否已经加载过子节点，如果加载过，可以直接使用 addNodes 方法 以及 你的 保存到数据库的操作； 如果尚未加载过，请在你 保存数据库操作结束后， 直接让该父节点展开即可，不需要addNodes 了。 

参考属性：treeNode.zAsync  可以看看 API 中的描述
