### ISSUE TITLE
两棵树移动节点出现Maximum call stack size exceeded

### ISSUE THREAD

**Issue by xlkit456852** [zTree/zTree_v3#148]
`callback: {
            beforeDrag: beforeDrag,
            beforeDrop: beforeDrop,
            onClick:onClick
        }
function onClick(event, treeId, treeNode, clickFlag){
        var treeObj = $.fn.zTree.getZTreeObj("treeDemo");
        var node = treeObj.getNodeByParam("id", treeNode.data_pId, null);  //这里的data_pId是我定的一个属性，用来找回这个节点拖拽之前的父节点id
        var result = treeObj.moveNode(node, treeNode, "inner");
        console.log(result);
    }`

我的业务逻辑是：从树1拖拽节点到树2，然后点击树2节点的时候，树2节点会回到它之前所在的树1的节点。现在树1拖拽到树2没问题，就是点击树2节点时，树1节点原来的位置的确出现了树2节点，但树2的节点没有消失（即现在有2个树2节点，这是问题1），然后就是js报错：Maximum call stack size exceeded

![qq 20160429110212](https://cloud.githubusercontent.com/assets/7323450/14907333/fa36fddc-0df9-11e6-9714-19e7abb6022d.png)

**Comment by zTree** [comment]
你这个很明显是出现了死循环导致，请务必检查你的代码逻辑， 我能提醒的有以下几点：
1、moveNode 方法只能适用于单独一棵树内
2、两棵树之间用 function 移动节点必须要在原先的树上 removeNode ，然后在目标树上使用 addNodes 方法
