### ISSUE TITLE
如何自定义isParent的名字

### ISSUE THREAD

**Issue by notech** [zTree/zTree_v3#149]
API中没有找到,是否可以考虑支持?
比如将isParent 改成has_child

**Comment by zTree** [comment]
建议如果你那边能修改就自己修改数据吧， 由于基础架子不合理，这个修改起来会比较麻烦， 本人目前没有时间进行处理。。。抱歉。 只能等以后重构的时候，再考虑了

**Comment by notech** [comment]
好的,明白了.感谢
