### ISSUE TITLE
如何让节点滚动到可视区域

### ISSUE THREAD

**Issue by hylin** [zTree/zTree_v3#15]
貌似只在expandNode里面看到有focus参数，用于expand节点后保持父节点在可视区域内。
但是如果是叶子节点就没效果了。
treeNode对象只公开了一些基本属性和方法，我也拿不到对应的dom，没法手动计算滚动。
有什么办法不？谢谢

**Comment by hellojiangjialin** [comment]
使用了selectNode()的方法，节点可以被标明是处于选中状态，但是却不滚动到可视区域，请问这个是什么问题呢？

**Comment by hellojiangjialin** [comment]
@zTree  嗯，已经解决了。Dom节点还未被渲染出来，所以无法滚动。加了一个setTimeout，等到节点渲染完成之后，就可以滚动值可视区域了。

**Comment by penghzhang** [comment]
你好，
我最近是zTree 3.5.40版本，jquery 3.4.1版本，构建tree后，我使用selectNode函数可以focus到node但是有些元素不能跳转到视图区域。代码如下：
`let treeObj = $.fn.zTree.getZTreeObj(‘treeId’);
    let nodes = treeObj.getNodesByParam('id', 'testNodeId', null);
    if (nodes.length <= 0) {
        treeObj.cancelSelectedNode();
        return;
    }
    for (let i = 0; i < nodes.length; i++) {
        let node = nodes[i];
        treeObj.selectNode(node);
    }`
我的tree结构如下：
Root //parentId = 0
  |--Level_1
          |--Level_2 //在一个Level_1 node下会有大概50个左右的Level_2 node。
问题：
1.  当Root节点本scroll到可视区域外边，调用上边代码选中Root节点是，Root会被focus但是不会跳转到可视区域。
2. 在Level_2中选择最底下元素并使其滚动到可视区域，然后使用上述代码选中Level_1时，可以看到tree所在div的scrollBar有滚动，但是并未将Level_1元素滚动到可视区域。
