### ISSUE TITLE
check before remove or rename

### ISSUE THREAD

**Issue by IamFive** [zTree/zTree_v3#150]
At most times, whether a tree node could be delete or not is depend on a remote check or some callback, how to implement this.

```
function beforeRemove(treeId, treeNode) {
       $.post('check whether this node could be removed').done(function(data) {
              return true or false here?
        });      
        
        //wait for some callback or we can just return a promise?
}
```

I know we can use sync ajax post to fix this, but there are other situations like A confirm message box with a callback

http://layer.layui.com/api.html#layer.confirm

```
function beforeRemove(treeId, treeNode) {
	layer.confirm('is not?', function(index){
		layer.close(index);
		return true or false in a callback;
	});      
}
```

**Comment by zTree** [comment]
function beforeRemove(treeId, treeNode) {
    layer.confirm('is not?', function(index){
        layer.close(index);
        //return true or false in a callback;
       if (true)  {
          treeObj.removeNode(treeNode);
       }

    });
    return false;      
}

**Comment by IamFive** [comment]
哈哈，是国人。在GIT比较少用中文。

貌似这样能解决问题，但是还是感觉怪怪的，在Before中就把节点给删除了。能改成用 Defer promise 去回调会好一些

**Comment by zTree** [comment]
抱歉， 当时哪儿懂 promise 这些东西呀， 等下次重构的时候，全都用 ES6来写吧。。。对异步的回调机制都要调整的。 所以目前版本我基本上只做 bug 修改了。

**Comment by IamFive** [comment]
辛苦了。是个好控件。
