### ISSUE TITLE
disabled property / readonly tree???

### ISSUE THREAD

**Issue by kiosaninsl** [zTree/zTree_v3#152]
Hi,

I did not found any resource to disable/enable/read only entire tree and i need to suggest you to implement this feature on the new release.

If my object was disabled (property disabled), the entire tree disabled and any callbacks are ignored.

I developed new features to improve my use:

-On checked (or clicked) on the item with children and this item is expand automatically or retracts when is unchecked;

I hope you enjoy my suggestions
Kiosaninsl

**Comment by zTree** [comment]
Hi,

1. In zTree, the checkbox or radio is not belong the  edit model. 
  >  When you want to edit, please see: 'setting.edit.enable'.
  >  When you want to not allow check the node, please see: 'setting.callback.beforeCheck'

1.  When you want to click the node and it was expand automatically, please use 'setting.callback.onClick'  && 'treeObj.expandNode()'

**Comment by kiosaninsl** [comment]
Hello,

I think I expressed myself poorly. It would be interesting to have a disabled throughout the tree, preventing any event the same (callbacks, expands, clicks, etc) without the need to monitor all events tree.

The mode "read only" would expand, reduce and roll the tree but not allow any type of change (edit, check or radio item changed, etc.) without the need to monitor all events manually.

Being that I could set the disabled property [jquery prop ('disabled, true)] in the div tag and the component would modify the object's behavior.

I managed to do this with the events but the work was very manual and I would like to help implement these features.

Thank you

**Comment by zTree** [comment]
you can add this, by your self.

example:

1. you make some function to check the readonly/edit mode,  it will return true or false.  the  rule is any thing by your need.

1. you can add the function to the all callback 'before...' what you want to controll.

so, when you change the mode to readonly,  the all callback 'before' will return false.
