### ISSUE TITLE
添加排序功能？

### ISSUE THREAD

**Issue by e-cloud** [zTree/zTree_v3#153]
树节点希望可以排序

现在的一个暂行方案是，在外部排序传进去初始化
但是，当数据动态修改（添加节点，更改节点排序依赖的属性）后，没找到一个很好的办法来更新排序，

所以想问问是不是可以内置节点排序

**Comment by zTree** [comment]
抱歉， 请利用 moveNode 方法自行排序吧，目前暂不增加排序功能了。 等以后整个代码重构以后，再考虑吧

**Comment by e-cloud** [comment]
打算重构呀，因为什么而需要重构？打算重构成什么样子？

**Comment by zTree** [comment]
1、早先 的 zTree 是自己刚开始深入 前端的时候制作的， 是一步步学习的过程，所以整体代码结构不合理，命名规则不合理、事件机制不合理等等；从而导致 看API 难以阅读和理解，对事件处理较繁杂，代码结构不利于扩展， 再扩展下去就会越来越臃肿

2、彻底抛弃 旧版的浏览器，一切向前看，使用较新的架构，利用 node 系进行 build，让代码结构化更细，组合更灵活， 这样可以不断制作新的扩展， 用户可以根据需要的功能进行打包

这是想的。。。目前由于本人工作较繁忙，所以一直没有开始做这个事情。。。。抱歉呀

**Comment by e-cloud** [comment]
明白，或许可以开一个issue，讨论一下发展方向之类的，那就可以借力社区加速改进

**Comment by zTree** [comment]
感谢！

**Comment by sailiaspeng** [comment]
文档瞄了很久木有节点排序相关的内容在这里找到了ISSUE，用下来发现都会有类似需求：节点初始化给定Index，拖拽等操作改变节点Index属性。目前用 moveNode 方法效率实在有点不可描述。

**Comment by zTree** [comment]
@sailiaspeng 其实排序功能完全可以自行写一套排序算法，给 树节点进行排序，排序后重新 init 就是了， moveNode 适用于界面操作少量节点排序的
