### ISSUE TITLE
ztree 自带的level和后台返回的数据里的level冲突了？

### ISSUE THREAD

**Issue by docikaci** [zTree/zTree_v3#158]
怎么最小化改动处理好呢？ 能否将后台返回的数据放到某一个对象key的下面，然后挂载到当前treenode上面存起来，不至于和ztree自己提供的数据字段冲突？

**Comment by zTree** [comment]
如果后台实在无法修改的话，那么就在前端获取数据以后， 遍历一下，将 level 改成 _level 保存数据吧。
