### ISSUE TITLE
Text Wrapping

### ISSUE THREAD

**Issue by cstone651** [zTree/zTree_v3#159]
Hi;

Is there a way to have node text wrap?  I have scoured documentation, examples, and the API but don't see if it is possible.

Thanks for any assistance!

**Comment by zTree** [comment]
if you want wrap node text in zTree, please modify the zTreeStyle.css by yourself.

example: 
1.   .ztree li{padding:0; margin:0; list-style:none; line-height:14px; text-align:left; white-space:nowrap; outline:0}
2.   height:17px; height:16px;   (you must remove these 'height', or change some value)

And please set the line hide. (setting.view.showLine = false)
