### ISSUE TITLE
异步加载节点，第一次需要传id和type，怎么办？

### ISSUE THREAD

**Issue by docikaci** [zTree/zTree_v3#160]
剩下的节点是传当前id和type。
如果在URL里写上，之后会重复。如图：
![image](https://cloud.githubusercontent.com/assets/7788102/17282388/dde86a76-57d7-11e6-8025-b75406ad65ef.png)

autoparam 是对除第一次之外的生效？？

**Comment by docikaci** [comment]
有没有解决方案呢？非常感谢

**Comment by zTree** [comment]
1. autoparam 是提交请求时，把当前父节点的对应属性值传给后台， 用于后台处理
2. 树在初始化时，第一次进行异步加载，本身就是为了加载根节点，对于根节点来说是没有父节点， 所以当然就没有 autoparam 配置的这些数据了。。。其实你只需要在后台判断没有这些值时，就按照 根节点来处理就是了

**Comment by docikaci** [comment]
![image](https://cloud.githubusercontent.com/assets/7788102/17282854/d9a08386-57dc-11e6-87c0-5ae5bd711c5a.png)
这样就实现了。。。

**Comment by zTree** [comment]
你这种方式也没有问题的！
