### ISSUE TITLE
内存溢出

### ISSUE THREAD

**Issue by daivem** [zTree/zTree_v3#161]
simpleData模式，数据量56W
数据全部加载好了，树的头渲染出来了，但当双击想展开的时候就提示错误
Uncaught RangeError: Invalid string length
chrome浏览器。

如果是火狐，错误提示为：uncaught exception: out of memory

不知道有没有办法解决？

**Comment by zTree** [comment]
56w 的数据你要一次性加载进来？？？ 太疯狂了吧？？？ 请你务必采用 每层节点 异步加载的方式， 并且如果某一层节点过多，建议也采用分页的方式。。。否则效果好不了！ 对于页面来说， 56w 的数据的确有些过大了。
