### ISSUE TITLE
请问怎么让checkbox放到最前面呢？

### ISSUE THREAD

**Issue by docikaci** [zTree/zTree_v3#163]
![image](https://cloud.githubusercontent.com/assets/7788102/17431789/4a813d94-5b2e-11e6-8120-6311f75a7949.png)
 
有没有简单的配置，或者修改方法，多谢

**Comment by zTree** [comment]
抱歉， 你这种改动会导致连接线 显示异常， 因为 zTree 的结构 是 +/- 号 与 连接线是组合在一起的。

如果一定要把 checkbox 放到前面， 请 设置 不显示连接线，然后利用 onNodeCreated 回调，把刚生成的 节点Dom 中 +/- 和 checkbox 的span 交换位置 即可

**Comment by docikaci** [comment]
连接线的问题，先可以忽略，可以不显示，具体怎么交换呢，在onNodeCreated回调里？怎么拿到checkbox和加减号，然后交换位置，非常感谢

**Comment by docikaci** [comment]
@zTree 连接线的问题，先可以忽略，可以不显示，具体怎么交换呢，在onNodeCreated回调里？怎么拿到checkbox和加减号，然后交换位置，非常感谢

**Comment by docikaci** [comment]
或者渲染的时候，每一行如果有checkbox或者radio，我可以知道，并且给当前li加个自定义的class，然后我就可以写样式交换位置了。
有什么标示可以知道当前 LI下面出现了checkbox？

**Comment by zTree** [comment]
请你调试一下， onNodeCreated 触发时，就说明该节点的 Dom 已经创建完毕， 你可以利用你的方式尝试交换位置； 通过 treeNode.tId 配上 _check   _switch   就能生成对应的 Dom id，从而便于找到对应的 Dom元素进行操作

**Comment by docikaci** [comment]
![image](https://cloud.githubusercontent.com/assets/7788102/17433378/f54ce63a-5b36-11e6-9e70-449f31803325.png)

修改了这个方法，插入checkbox，radio放在了最前面，暂时没有发现其它问题？不知道有什么隐患没？先这样吧，谢谢你哈

**Comment by zTree** [comment]
你这种小的改动, 完全没必要直接修改 源码, 利用 onNodeCreated 回调直接修改 dom 有什么不能实现的问题么?  你这种修改，直接导致的问题就是以后 zTree 有升级操作时，你还得不断地去修改源码。 不过幸运的是，目前这种情况不多
