### ISSUE TITLE
Ztree 设置的setting.async.dataFilter 回调函数出现偶尔不执行的情况 

### ISSUE THREAD

**Issue by lsunflower** [zTree/zTree_v3#164]
监测Network，请求正常返回数据，但是会出现偶尔不调用dataFilter 回调函数的情况，版本v3.5.18 #
![Uploading image.png…]()

**Comment by zTree** [comment]
请你再仔细检查一下：
1、异步加载模式下， 只要是把节点加入zTree ，肯定会触发 dataFilter
2、你看到的代码一旦满足条件， 压根都不会把数据加入到 zTree 内，所以当然也不会触发 dataFilter
3、_ver 属性是 zTree 初始化的时候才设置的， 这个逻辑主要是避免 树 反复刷新后， 避免前一次初始化的异步加载数据 进入 最后一次初始化后的树内。，跟你说的情况没什么关系呀。
