### ISSUE TITLE
怎么自动展开某一个节点呢？

### ISSUE THREAD

**Issue by docikaci** [zTree/zTree_v3#165]
比如说我这是5级的树， 我想展开第三级的某一个节点（可以从缓存获取到此节点id，level等信息）

也就是想还原上次的点击记录

同步和异步怎么分别实现呢？？
感谢大神

**Comment by docikaci** [comment]
整个树时同步加载，和整个树时异步加载，怎么分别自动展开某一个节点？

**Comment by zTree** [comment]
抱歉，最近工作较忙，没能及时回复，请见谅！

如果一次性加载了全部节点，那么相当简单：
1. 利用 getNodeByParams 方法找到你需要展开的节点
2. 利用 expandNode 方法展开此节点， 其父节点会自动被展开不用操心

如果你是逐级异步加载， 那么稍微麻烦一点：
1. 你肯定要把 需要展开的节点的所有父节点 id 都记录下来
2. 利用 onAsyncSuccess 回调， 判断刚加载的节点中，如果有其某个父节点，就利用 expandNode 方法展开此节点，这时候 zTree 会自动进行异步加载，加载后又会触发 onAsyncSuccess 回调，依此类推，直到你指定的这这个节点找到。。。这时候也就全部展开了。。

**Comment by zTree** [comment]
可以适当参考Demo：http://www.treejs.cn/v3/demo.php#_512

**Comment by docikaci** [comment]
expandNode  只是展开，不会触发click事件， 比如说，展开某一个节点，还想加载其对应的列表。

**Comment by zTree** [comment]
那你可以使用 jQuery 的 trigger 事件自己触发， 另外也完全可以 自己直接调用 onClick 回调呀
