### ISSUE TITLE
nodejs express框架，异步加载的url地址不发送请求，请问一下这个是特殊处理过么

### ISSUE THREAD

**Issue by foolishgao** [zTree/zTree_v3#166]

**Comment by zTree** [comment]
完全没有做过这类特殊处理， 而且 你的 express 完全是服务端的框架， 跟前端框架没有任何关系， 无非是使用了同一种 语言而已，这跟 前端的 插件不应有任何影响。

zTree 是纯前端的 jQuery 插件，你所需要检查的还是生成的前端页面的 js 是否正常，配置是否正常，检查是否有什么报错信息。
