### ISSUE TITLE
Number of childs

### ISSUE THREAD

**Issue by szabacsik** [zTree/zTree_v3#167]
zTree is awesome! Grats!

In the dragWithOther.html demo, when I drag item to the tree from the div, the number of items (n) doesn't increment. When I remove item, decrement is ok. Do I implement it myself or is there a refresh function or something I did not notice? Thanks!

**Comment by zTree** [comment]
hello, please see: http://www.treejs.cn/v3/demo.php#_511

I drag node in this page, it works well.

I don't know what problem with your code.  when you visit this demo, have any issue??

**Comment by szabacsik** [comment]
There is the same issue on the demo. The number of items in the bracket show a wrong number. It calculates only when I remove from the tree.
![ztree_issue](https://cloud.githubusercontent.com/assets/1412263/18364239/066f4cea-760e-11e6-9f9f-a14978ce2b3f.PNG)

**Comment by zTree** [comment]
Thank you very much. This issue is only in the code of this demo.  I have fixed it.
