### ISSUE TITLE
beforeDrop的moveType有BUG

### ISSUE THREAD

**Issue by sasayaku** [zTree/zTree_v3#168]
当拖拽节点，在放下前进行高频来回移动时，beforeDrop中获取到的moveType有时候会错误。
更新：onDrop同样有该问题

**Comment by zTree** [comment]
请你再仔细确认一下问题， 只要你不放下， 不管你的频率有多快，都不可能触发 onDrop 回调的

**Comment by sasayaku** [comment]
我的意思是放下前经过了来回高频拖动，然后松开鼠标。场景：目前有4个同级节点，正常情况下，第三个拖到第二个节点前，onDrop和beforeDrop的moveType都是prev。然后同样的节点，拖住第三个节点，上下来回拖拽，然后再放到第二个节点前，有较大概率moveType变成next.

**Comment by sasayaku** [comment]
好像理解错prev和next的含义了，不好意思。

**Comment by zTree** [comment]
原来你说的错误是 prev 变成了 next 呀， 这个肯定不是错误！

请务必注意， moveType 是一个相对的参考，就好像说， 前后左右，一样， 都是有相对值的。 而 moveType 就是相对 targetNode 的相对位置。 

因此 不管你是否高频， 关键看你松开鼠标时的位置而定， 请你再多操作几次，就会明白的。 基本上是 节点的 1/3 高度来划分的
