### ISSUE TITLE
初始化成功回调

### ISSUE THREAD

**Issue by baiyapeng** [zTree/zTree_v3#170]
看了一圈API，发现没有初始化成功或者失败的回调函数，`onAsyncError onAsyncSuccess` 也不是我想要的，如果设置延迟回调的话就太不靠谱了，这个问题作者有没有想过呢，如果可以完善就太好了？另外，感谢作者开源这么优秀的JS插件！

**Comment by zTree** [comment]
你好， 你提的问题比较尖锐。 zTree 制作时 本人前端技能非常初级， 考虑的也不周全， 对于 初始化来说， 如果没有采用异步加载模式， 那么init 之后就是成功了， 失败的话肯定就是有 js 报错了；对于 异步加载模式， 那么完全就是依靠 onAsyncSuccess 和 onAsyncError 来处理。

下一次重构的话， 肯定会全面采用异步机制，提供各种回调和事件处理。这样才会更加灵活并易于使用和扩展。

另外 关于 采用异步加载模式的话， 需求各有不同：有的人是每次加载一级节点， 有的是异步加载时 第一次就加载n级节点， 有的甚至是直接利用异步加载 逐级 异步加载 n级节点。。。对于这些情况的 初始化成功和失败 你是如何理解的呢？ 

我个人针对这种情况的理解是， 以后对于 初始化成功失败的事件，就是  init 后的结果， 同时并不会把 异步加载的状态包含进去。。。异步加载依然提供自己特定的事件回调。

非常期望你能把你的想法告诉我， 谢谢。

**Comment by baiyapeng** [comment]
其实有些时候不太在意树是静态加载还是异步动态加载， 从调用`$.fn.zTree.getZTreeObj('tree')`可能返回`null`，这个角度讲，我个人觉得应该可以设置监听函数来监听，个人意见，谢谢回复~

**Comment by zTree** [comment]
非常感谢！

你的想法可以分析为以下几点：

1. 在 init 中去触发了某些回调 导致 有可能去使用 getZTreeObj 方法，这个是个值得去调整的地方
2. 让用户忽略是否异步  总体来说都按照异步的方式来思考问题
