### ISSUE TITLE
父子节点关联时选中问题

### ISSUE THREAD

**Issue by aw6658913** [zTree/zTree_v3#171]
当选中父节点，下面子节点全选，去掉子节点，这时候父节点为半选状态，可是仍然算选中状态会把值传到后台

**Comment by zTree** [comment]
1. 只要是节点被勾选（有打勾的标识）， checked 属性就是 true
2. 背景为灰色的状态只是表明该父节点有部分子节点被勾选

综上所述，检查你自己的节点状态，确定视图中实际的节点勾选状态。 另外， 提交到后台的逻辑是根据你们自己需求制作的， 检查你提交时获取数据的方法， 根据你们自己的需求进行制作并提交。
