### ISSUE TITLE
只有第一个节点鼠标悬停时显示下划线，其他节点无效

### ISSUE THREAD

**Issue by justforuse** [zTree/zTree_v3#172]
Angular项目，调用了onNodeCreated方法，运行时只有第一个节点鼠标悬停时显示下划线，F12审查元素，所有节点均调用了.ztree li a :hover{text-decoreation:underline;}样式，但是却不显示，我用的Chrome，这是浏览器的问题吗？

**Comment by zTree** [comment]
1、跟 是否 使用 angular 无关
2、检查 是否与你项目内的 css 有冲突导致
3、按道理应该与 chrome 无关

排查方法：先把你项目内的css屏蔽掉，看看是否正常。 用 chrome 的调试工具检查 样式， 查看 hover 时生效的样式！
