### ISSUE TITLE
Filter multiple nodes for beforeDrag and beforeDrop when "selectedMulti" enabled

### ISSUE THREAD

**Issue by servocoder** [zTree/zTree_v3#174]
At the moment it's possible to prevent drag and drop actions by returning "false" value inside "beforeDrop" and "beforeDrop" callbacks. So I'm able to completely stop the process, but what if I'm going to drag a set of nodes ("selectedMulti" enabled) and some nodes is ok, and some should be removed from the list. Example of nodes list:
```
var zNodes =[
	{ id: 1, name: "node 1", validToDrag: true,  validToDrop: true },
	{ id: 2, name: "node 2", validToDrag: true,  validToDrop: false },
	{ id: 3, name: "node 3", validToDrag: false,  validToDrop: false },
];
```
You can see the "node 3" have "validToDrag" property is set to "false" and I want to filter the nodes before dragging so that when I start to drag only 2 of 3 nodes are dragged. And before I drop the 2 draggable nodes I also want to filter the nodes by "validToDrop" property, so only the "node 1" will be dropped eventually.

It would be great to have a capability to return filtered array out of "beforeDrag" and "beforeDrop" callbacks:
```
beforeDrag: function (treeId, treeNodes) {
	var filtered = [];
	for (var i=0,l=treeNodes.length; i<l; i++) {
		if (treeNodes[i].validToDrag === true) {
			filtered.push(treeNodes[i]);
		}
	}
	return filtered;
},
beforeDrop: function (treeId, treeNodes, targetNode, moveType) {
	var filtered = [];
	for (var i=0,l=treeNodes.length; i<l; i++) {
		if (treeNodes[i].validToDrop === true) {
			filtered.push(treeNodes[i]);
		}
	}
	return filtered;
}
```
Very convenient as for me.
Otherwise new callbacks shall be implemented for the filtering.

**Comment by zTree** [comment]
please try:

```
function beforeDrag(treeId, treeNodes) {
    return true;
}
function beforeDrop(treeId, treeNodes, targetNode, moveType) {
    var lastNode = targetNode, i, l;
    for (i = 0, l = treeNodes.length; i < l; i++) {
        if (treeNodes[i].validToDrop === true) {
            moveNode(treeNodes[i], moveType);
        }
    }
    return false;

    function moveNode(node, moveType) {
        var zTreeObj = $.fn.zTree.getZTreeObj("treeDemo");
        setTimeout(function () {
            if (moveType == 'next') {
                zTreeObj.moveNode(lastNode, node, moveType);
                lastNode = node;
            } else {
                zTreeObj.moveNode(targetNode, node, moveType);
            }
        }, 0);

    }
}
```

**Comment by servocoder** [comment]
It works, thank you
