### ISSUE TITLE
Promise support in callbacks (deffered objects)

### ISSUE THREAD

**Issue by servocoder** [zTree/zTree_v3#175]
I need to perform ajax calls inside callbacks and return true/false based on the response. Example:
```
beforeDrop: function (treeId, treeNodes, targetNode, moveType) {
	$.getJSON('/script.php', function(response) {
		// return true or false to callback based on response
        // in other words I need to break or proceed drop action based on response
	});
}
```
I know that jQuery has "async" parameter, which I can set as `async: false` to perform sync request, but this stuff [is deprecated](https://bugs.jquery.com/ticket/11013) and the promises is the preferable way to handle the case. Is it possible to implement promises? Or perhaps you can suggest another solution? Thank you.

**Comment by zTree** [comment]
```
beforeDrop: function (treeId, treeNodes, targetNode, moveType) {
    $.getJSON('/script.php', function(response) {

        // you can use : treeObj.moveNode(....)
    });
   return false;
}
```
