### ISSUE TITLE
reAsyncChildNodes: remove old children after new ones are loaded

### ISSUE THREAD

**Issue by servocoder** [zTree/zTree_v3#176]
It should be a simple improvement.
When I use `reAsyncChildNodes()` method it removes all old nodes at first and then calls `asyncNode()` function which initiates ajax request. In the UI this looks as all nodes are gone for a moment and then appear again. I suggest to improve this behavior in a way to remove old nodes after the ajax call is done, inside the `success` callback, right before new nodes are added.

**Comment by zTree** [comment]
You can use ajax by yourself to get new nodes, and remove the old nodes, and add the new nodes

**Comment by servocoder** [comment]
Of course I can, but isn't it expected behavior by default?
There is no sense to remove old nodes before new ones are loaded.
It's easy to move "remove nodes" logic to ajax success callback. I can create PR for this improvement if you want.
