### ISSUE TITLE
simpleData模式下根节点pId被重置

### ISSUE THREAD

**Issue by ystyle** [zTree/zTree_v3#178]
```{data:{simpleData:{enable:true,idKey:"id",pIdKey:"pId",rootPId:0}},```

其中rootPId不管写不写。 根节点的pId都会被重置，有没有办法不让重置。

**Comment by zTree** [comment]
1、初始化时 zTree 会根据 id、pId 的数据构建 树形的数据结构
2、在初始化时，会把 根节点的 pId 按照 rootPId 进行重置，即使你不设置，他也有默认值的
3、非根节点的 pId 只有在 拖拽移动后才会被修改

综上所述，你设置 rootPId 为你需要让根节点设置的 默认 pId 即可， 其他的不应该去操心了。

不知道你为何会纠结 根节点的 pId？

**Comment by ystyle** [comment]
pid，就是后台数据的pid，由于权限过滤，用户是看不到整颗树的，
业务需用到pid字段的值

**Comment by zTree** [comment]
你这种需求，完全可以让你这个不需要被修改的字段换个属性名，存一份就是了
