### ISSUE TITLE
关于自定义展开图标的问题

### ISSUE THREAD

**Issue by ch3400258** [zTree/zTree_v3#181]
我如果不用图片，用CSS图标放到switch的span里面,触发事件的DOM是<i></i>,而你写死的是span,这个是不是可以优化一下

**Comment by zTree** [comment]
1、zTree 内部功能只会针对 zTree 定义的功能组件处理， 你自行扩展的功能 zTree 无从获取，也就无法控制
2、展开图标的替换基本上只是 css 层面的修改，所以实际上触发事件时仍然是 zTree 定义的 span 即可，所以应该不会影响你的需求

请参考 Demo: http://www.treejs.cn/v3/demo.php#_515
这里面所有的图标都换成 字体的矢量图标了，但也不会去影响操作，因为他仅仅修改的是 css ，并没有改变 dom 结构

**Comment by ch3400258** [comment]
恩，谢谢，我看看
