### ISSUE TITLE
Exhide and Exedit

### ISSUE THREAD

**Issue by epime** [zTree/zTree_v3#182]
Refering to: This feature can't support the 'exedit' feature, so please don't use this feature in edit mode.

I can seem to find anywhere what exactly makes these two incompatible? I've got a tree where I've got use for both, and it seems to work exactly as I want. However could this come back and bite me later..... 

I suspect that the incompatibility comes from the drag drop functionality ?

**Comment by zTree** [comment]
1. If you hide or show the nodes, it will effect the 'isFirstNode' and 'isLastNode' attribute.
2. When you remove all child nodes(there are some child nodes had been hidden), the parent node will not to change to the leaf node.

I did not do comprehensive testing for exhide and exedit. so I am not recommended that you use exhide and exedit as the same time.

**Comment by epime** [comment]
Thanks for the quick response. I should be in the clear then as I don't use any of those properties :)
