### ISSUE TITLE
ztree是否可以支持treetable这样的展现形式

### ISSUE THREAD

**Issue by siye1982** [zTree/zTree_v3#184]
有些场景, 比如想展示rpc调用链跟踪, 在树中需要展示一些其他更加详细的字段. 这样用treetable的形式展示会更好一些. 不知道是否有这方面的计划

**Comment by zTree** [comment]
非常抱歉，目前 zTree 的结构并不适合 table 的展示，之前有部分用户通过修改 css 实现了一定功能的treetable，但未必能满足各种需求，短时间内 不会提供这方面的开发，请见谅。

**Comment by siye1982** [comment]
收到, 感谢回复
