### ISSUE TITLE
两个节点中间的子节点，无法展开对应的li标签的class好像没有触发修改

### ISSUE THREAD

**Issue by legolasNg** [zTree/zTree_v3#186]

**Comment by zTree** [comment]
请仔细查看 updateNode 方法的 API 文档；

请仔细查看 isParent 属性的 API 文档

**Comment by legolasNg** [comment]
是这样的。我是一次性将树形结构生成ztree，树的深度超过4层，在我展开某一个节点的时候，没有子节点显示。但是在dom中是有生成的，只是显示的时候出现了问题

**Comment by zTree** [comment]
首先可以肯定的是，正常使用不会有这种问题。

所以提问题，请把问题描述清楚， 你的数据是什么样子的？ setting 如何设置？ 显示时的错误截图？  

什么都不写，如何帮你？

**Comment by legolasNg** [comment]
##  数据结构

![data](http://ww4.sinaimg.cn/large/6338e79dgw1f9bjmm74bij21e60imtd0.jpg)

## 出错节点

![errorNode](http://ww4.sinaimg.cn/large/6338e79dgw1f9bjmn0tsmj20p90d5jrt.jpg)

## 出错节点的DOM

![errorNode_DOM](http://ww3.sinaimg.cn/large/6338e79dgw1f9bjmn64lrj20z90p1q8s.jpg)

**Comment by legolasNg** [comment]
之前是去找图床去了，花费了点时间。不好意思

**Comment by legolasNg** [comment]
设置如下

````
var setting = {
     check: {
                enable: true,
                chkStyle: "checkbox",
                nocheckInherit: true,
                chkDisabledInherit: true
            }
};
$.fn.zTree.init(element.find('#sourceTree'), setting, sourceTree);
````

我的节点数据中并没有"open"属性，也就是默认是不展开的。但是数据是一次性init的。是在展开的时候出现的问题

**Comment by zTree** [comment]
1、确认是否使用的 最新版 zTree
2、请使用 官网提供的官网 Demo ，直接用上你的数据，看看是否正常
3、请检查你的项目中的样式，查看这个节点 中 子节点的 DOM，看看对应的样式，检查为何没有显示出来。

DOM 都已生成，但看不到，一般来说是 样式出现冲突导致。
