### ISSUE TITLE
removeHoverDom事件在点击树节点后不触发

### ISSUE THREAD

**Issue by jeatime6** [zTree/zTree_v3#187]
```
var setting = {
	view : {
		showLine : false,
		showIcon : false,
		addHoverDom : (treeId, treeNode) => {
			let aObj = $('#' + treeNode.tId + '_a');
			$(aObj).find('i:first').eq(0).removeClass('hidden');
		},
		removeHoverDom : (treeId, treeNode) => {
			console.log(123);
			let aObj = $('#' + treeNode.tId + '_a');
			$(aObj).find('i:first').eq(0).addClass('hidden');
		}
	}
};
```

未点击树节点之前，addHoverDom和removeHoverDom都能触发，点击节点后，removeHoverDom不能触发。

> 版本：JQuery zTree core v3.5.23

**Comment by zTree** [comment]
1. 没有正确配置 removeHoverDom 回调

addHoverDom 绝对不能单独使用，必须要与 removeHoverDom 配套，zTree 会根据鼠标位置 和 节点状态 自行控制 触发这两个回调

2. addHoverDom 中未作判断，导致反复添加多个 控件

addHoverDom 回调触发时，一定要根据你的 控件 id 规则去判断是否该节点已经创建过控件，如果已经创建过就不要反复创建！

3. 注意节点的高亮状态

节点在高亮状态时，只会触发 addHoverDom 回调，不会触发 removeHoverDom 回调
> 主要原因是为了避免 节点右侧根据 hover 状态显示自定义控件时，有可能自定义控件的位置会超出 zTree 容器，必须移动横向滚动条才能进行操作。如果不考虑高亮状态，那么就会导致用户永远无法操作这些 自定义控件。
