### ISSUE TITLE
对多个节点展开，总是只执行最后一个

### ISSUE THREAD

**Issue by maxwellyue** [zTree/zTree_v3#188]
我是想检索节点，然后展开包含检索内容的节点，代码如下：
`
var nodes = zTree.getNodesByParamFuzzy("name", searchContent, null);

for(var i=0; i<nodes.length; i++){	
	     
        zTree.expandNode(nodes[i], true, true, true);
}
`
假如获取的nodes的长度是2，那么只有
`
 zTree.expandNode(nodes[1], true, true, true);
`
会产生效果，
`
 zTree.expandNode(nodes[0], true, true, true);
`
并不会展开，这是为什么呢？应该怎么解决呢？谢谢解答
用expandAll(true)可以展开所有节点，但不是想要的结果。

**Comment by zTree** [comment]
1、expandNode 只针对父节点有效，如果是叶子节点（isParent = false）是无效的
2、对于 叶子节点，你应该展开他的 父节点

**Comment by maxwellyue** [comment]
@zTree 好的，非常感谢
