### ISSUE TITLE
rtl  use or support

### ISSUE THREAD

**Issue by omrani6550** [zTree/zTree_v3#189]
How do I use for right-to-left?

**Comment by zTree** [comment]
http://stackoverflow.com/questions/2560966/text-right-to-left-css

please change css.

**Comment by azerafati** [comment]
For future reference you can achieve what you looking for with following scss snippet
```
///ztree_rtl.scss
.ztree{
  direction: rtl;
  li{
    text-align: right;
    ul.line {
      background-position: right 10px top;
      padding: 0 18px 0 0;
    }
    span.button{
      transform: scale(-1, 1);
    }
  }
}

```
[demo](https://codepen.io/azerafati/pen/oEbLLV?editors=1100)

**Comment by SAFatemi** [comment]
Salam @azerafati ;
I change this line and get better result:
`transform: scale(1, 1);`
