### ISSUE TITLE
Have a feature to not show +/- when no children are present for parent

### ISSUE THREAD

**Issue by sudheesh001** [zTree/zTree_v3#190]
Currently the tree shows up the +/- symbols in the tree when the parent does not have a child. it's a nice practice from a design point of view to give flexibility to the users to see whether they want that or not. An ideal thing would be in such a scenario to have such elements have this class `button level2 switch center_docu` thus making the tree look like this

<img width="232" alt="screen shot 2016-11-20 at 2 22 41 pm" src="https://cloud.githubusercontent.com/assets/4545925/20461729/d6e1649c-af2c-11e6-80e7-24b0b6574ffe.png">

to

<img width="234" alt="screen shot 2016-11-20 at 2 22 23 pm" src="https://cloud.githubusercontent.com/assets/4545925/20461730/dba390ea-af2c-11e6-953b-4f9f6bab4163.png">

Or is there a way to do the same ?

**Comment by zTree** [comment]
I'm sorry.  There is not way to hide the +/- symbols on the parent node. 

But if you judge the node is not parent node, you can set node.isParent = false, and use the updateNode(node)  method.
