### ISSUE TITLE
高版本的jquery 2.0  不支持

### ISSUE THREAD

**Issue by dcdlove** [zTree/zTree_v3#191]

**Comment by zTree** [comment]
请你确认是否使用最新版的 zTree 代码， 应该没有问题的！ 另外，请检查你自己的代码

**Comment by dcdlove** [comment]
哈哈哈哈哈哈是的是的

**Comment by dcdlove** [comment]
哈哈哈哈哈哈是的是的

**Comment by zTree** [comment]
敢问。。。您笑得这么灿烂。。。这问题是解决了还是没解决？

**Comment by dcdlove** [comment]
解决了啊，是被队友坑了，用了一个老版本的 说是这是新版的，

**Comment by dcdlove** [comment]
作者啊意见设计几套符合现代的皮肤，这样就更具竞争力，

**Comment by zTree** [comment]
这个抱歉了，现在一没精力，二没设计的能力。。。要改也是该整个 zTree 的架构，用上新的技术流，支持移动设备，才是更重要的事情。 这些皮肤以后可以考虑弄出一些氛围让粉丝自行提供。

**Comment by survivol** [comment]
jquery。。。 就先进性而言react、vue、nodejs、angular2都在一线，这个基数占比国内互联网公司10~20%吧，大部分公司还是jquery等稳定的系统，怎么过度，关键有大量工作要做是个问题， zTree只支持jquery或dom操作的开发，考虑过比较小众的vue、react、ang等的支持吗？

**Comment by survivol** [comment]
移动端目前是rn、weex和vue之类

**Comment by dcdlove** [comment]
目前前端框架太多了学都学不过来

**Comment by zTree** [comment]
zTree 目前用户更多是初学者，大部分使用高级框架的同学基本上也都能自己做出对应的树功能了。zTree 要改造架构更主要的是为了便于扩展，便于使用。不过前提是我必须要对目前流行的架构都比较熟悉以后，再来决定。一下子全都学好，也的确要花费不少时间的！大家一起加油吧！
