### ISSUE TITLE
请教如何实现子类展开不触发父类展开

### ISSUE THREAD

**Issue by shitfSign** [zTree/zTree_v3#199]
如何实现子类展开不触发父类展开。
   目前发现都是（expandNode）子类展开的话，父类会自动展开。

**Comment by zTree** [comment]
请问你的目的何在？ 尤其是 zTree 还是用了 延迟加载。

假设 A 是父节点， B 是A 的子节点，  初始化时， A 不展开，这时候 B 节点连 DOM 都不会生成，你让 B 节点展开何用？
