### ISSUE TITLE
官方min版是什么压缩的？

### ISSUE THREAD

**Issue by doocal** [zTree/zTree_v3#201]
本地用uglifyjs压缩出问题，jquery.ztree.all.js 行 977的样式 "class" 会被压缩成 class 从而导致在IE7-8兼容模式出现关键字的错误。

**Comment by zTree** [comment]
zTree 项目最开始制作时，我还是一个 java 程序员，当时我使用的是 google 的 js 压缩包 (https://github.com/google/closure-compiler，我看了一下，现在也有 js 版本了)，后来就一直用下来了，因为 整个 zTree 并没有做结构修改，所以也没有修改为使用现在的 grunt、gulp 之类进行编译、压缩。

至于你说的 使用 uglifyjs 处理后会导致 class 的双引号被去掉，我觉得应该还是你这边使用有些问题，否则 uglifyjs 处理的代码肯定早都是问题多多了

**Comment by luke-huang666** [comment]
能否提供下压缩JS的参数？是否有特殊参数？

**Comment by zTree** [comment]
并没有用特殊参数， 有 js 版本的应该也是可以正常使用的，你可以自己先试试看
