### ISSUE TITLE
同一个页面不能共存多个tree的实例吗

### ISSUE THREAD

**Issue by SmallShrimp** [zTree/zTree_v3#202]
我设置了treeId 但是没有起作用，通过treeId获取不到实例，而且两个实例不能共存 会发生冲突

**Comment by SmallShrimp** [comment]
我找到出问题的地方了
setting.treeId = obj.attr("id"); //这里给定死了 没有设置id就不行 而且这样treeId属性没用了

**Comment by zTree** [comment]
settting.treeId 不是让你手动设置的。

**Comment by SmallShrimp** [comment]
但是在传入的属性中有这个字段 我以为是可以设置的
