### ISSUE TITLE
CSS显示问题

### ISSUE THREAD

**Issue by sasayaku** [zTree/zTree_v3#204]
chkStyle默认值checkbox，但是写不写chkStyle:"checkBox"时，当checkbox被禁用时显示图标不同（都不能被勾选），不知道是不是作者故意做成这样的，还是是显示问题。

![qq 20170103140353](https://cloud.githubusercontent.com/assets/7899927/21600848/9fa33c40-d1bd-11e6-8845-09be9c8c2022.png)

![qq 20170103140451](https://cloud.githubusercontent.com/assets/7899927/21600849/a5b5925e-d1bd-11e6-9df4-c089dbdffa7f.png)

**Comment by zTree** [comment]
这应该是两种不可勾选。
1、被禁用时，背景变灰，这是完全正常的状态
2、你不填写正确的 checkbox ，故意设置为 checkBox，在功能操作时，出现错误，导致不可勾选。请你不要使用这种方法让 checkbox 失效。
