### ISSUE TITLE
IE8 HTMLElement

### ISSUE THREAD

**Issue by market-shandong** [zTree/zTree_v3#205]
HTMLElement undefine error !

**Comment by zTree** [comment]
your question is not clear.  I don't know what wrong with you.

If you tell the doctor, you fell pain.  I think that, the doctor will can not treat you.

PS:  If you are Chinese, please speak Chinese.

**Comment by buxiang2895** [comment]
作者这PS笑死我了，题主应该是国际友人了。
这个问题刚好也碰到，应该不是个别现象。
我是在ztree.all.min.js  v3.5.27版本中出现

调用selectNode方法时  IE8提示     'HTMLElement' 未定义  jquery.ztree.all.min.js, 行58 字符336
调试时定位在     (d=e.parentNode)instanceof HTMLElement;)

**Comment by zTree** [comment]
@buxiang2895 楼主肯定是我朝人士，你看看他的名字，shandong 这是拼音；另外他自己的项目，最后一次提交记录都是中文

另外，你赶紧去下载 最新版 v3.5.28 这个是专门修正这个问题的，你试试看，如果有问题就告诉我，谢谢。

**Comment by buxiang2895** [comment]
@zTree  换了v3.5.28版本后可以了，不过这个issue不是我创建的，应该关闭不了
