### ISSUE TITLE
beforeDrop调用同步接口,返回false时,之前的node已经删掉

### ISSUE THREAD

**Issue by kimiGG** [zTree/zTree_v3#206]
beforeDrop调用同步接口,返回false时,之前的node已经删掉,返回true正常.如果beforeDrop没有调用接口,直接返回false则不会删掉,打扰了

**Comment by zTree** [comment]
请晒出你的代码，我觉得是你代码逻辑有问题导致。 请你确认是你给 beforeDrop 进行了 return 操作，而不仅仅是你的 回调函数里面 return 。

**Comment by kimiGG** [comment]
是的,不好意思浪费你时间了
