### ISSUE TITLE
关于 api getNodeByParam(key, value, parentNode)

### ISSUE THREAD

**Issue by jml8871** [zTree/zTree_v3#209]
请问getNodeByParam可以用多个key,value来查询吗

**Comment by zTree** [comment]
没必要了，直接使用 getNodesByFilter 即可

**Comment by jml8871** [comment]
谢谢，不过我不太清楚invokeParam的具体用法，以下是我的代码，为了修改icon:

		this.updateIcon = function(content, newIconType) {
			var treeObj = $rootScope.treeObject;
			if(treeObj !== null && treeObj !== undefined) {
				var id = content.sourceId.split("/")[4];
				var repositoryId = content.sourceId.split("/")[2];
				var invokeParam = {};
				invokeParam.id = id;
				invokeParam.repositoryId = repositoryId;
				var node = treeObj.getNodesByFilter(filter, true, invokeParam);
				if(node !== null && node !== undefined) {
					node.icon = "../custom/images/kca_icon/" + newIconType + ".gif";
				}
			}
		}
		
		function filter(node, invokeParam) {
			return (node.id === invokeParam.id && node.repositoryId === invokeParam.repositoryId);
		}
