### ISSUE TITLE
调用reAsyncChildNodes会有段空白期

### ISSUE THREAD

**Issue by rikan** [zTree/zTree_v3#210]
Hi, 
想请教一个问题.
当我们使用ztree, 调用reAsyncChildNodes时候
有个参数是这样
reloadType = "refresh" 表示清空后重新加载。
reloadType != "refresh" 时，表示追加子节点处理。
我需要使用refresh来刷新整个tree数据.
使用"refresh"会清空再加载. 中间会有空白时间. 这个时间是和服务器响应时间有关么. 有没有办法没有这个空白期呢.

Thanks

**Comment by zTree** [comment]
你好， 肯定是跟 ajax 加载时间有关系的。

最完美的解决方案是，不要使用 reAsyncChildNodes 方法，自己后端生成增量的数据（例如：删除的节点、修改的节点、新增的节点）；前端用 ajax 自行获取增量数据 ，然后使用 zTree 的方法逐个更新节点，这样绝对不会有任何问题。

如果后端无法实现这种情况，那么就自己使用 ajax 获取数据，自行 removeNode，然后 addNodes。。。

**Comment by rikan** [comment]
估计这个做起来非常麻烦. 我们是异步加载tree, 还需要每个节点名称后面显示子节点的数量. 所以一些操作要保证整个tree上节点的数量是正确的.

为什么reAsyncChildNodes 接口需要在请求开始前清空整个Tree,而不是请求结束后success或者error的里面呢.这样空白的时间就缩短到小了吧.

**Comment by zTree** [comment]
当初这么实现应该还是为了避免 加载过程中用户对树进行操作吧。  你使用我说的后一种方法应该还好吧

**Comment by rikan** [comment]
好 我再看一下, 谢谢
