### ISSUE TITLE
树异步加载的时候，设置isParent属性会导致树被重复加载

### ISSUE THREAD

**Issue by longmazhanfeng** [zTree/zTree_v3#211]
树异步加载的时候，设置isParent属性之后，如果该节点是父节点但没有children，此时设置isParent为true，则该节点会被当作根基点，重新加载树，如此循环 @zTree

**Comment by zTree** [comment]
请务必调试代码正确配置对应参数，并且正确处理后台生成子节点的数据接口， 必须要根据当前父节点的id去生成对应的子节点数据，不能永远都生成同样的一批节点数据，那样肯定是无限循环下去了。
