### ISSUE TITLE
【改进】希望disabled状态的节点也应体现出半选状态，根据子节点自动计算其半选状态

### ISSUE THREAD

**Issue by netmou** [zTree/zTree_v3#212]

**Comment by zTree** [comment]
抱歉， 都 disabled 了，也就是不可用状态， 当然就不考虑半选状态了。

如果按照你的需求，那么 被 disabled 的节点自身的 checked 勾选状态是否还要影响 其父节点的 半选状态呢？？ 这本身就是不合理的，或者说无法准确的说到底哪个对那个错的，那这种情况下也就无法用统一的代码逻辑来实现所有的需求了。

根据你的情况，建议 不要使用 disabled，仅仅根据节点特殊属性在 beforeCheck 回调中控制该节点是否允许被勾选或取消勾选 ，就可以实现  disabled 的功能了，而且还有半选状态

**Comment by netmou** [comment]
disabled 了，虽然其状态不可用，但是如果树是折叠的，就不能看出是否有子节点被勾选。

**Comment by netmou** [comment]
disabled 的语义应当是用户不可直接勾选，但js任然能操作

**Comment by zTree** [comment]
抱歉，你理解的意思应该是 readonly 而不是 disabled；你试试form 表单 给 input 分别设置 readonly 和 disabled；提交数据后看看区别
