### ISSUE TITLE
zTree插件中，复选框--当取消所有子节点的选中状态父节点才会取消选中

### ISSUE THREAD

**Issue by LBX13** [zTree/zTree_v3#217]
zTree插件中，复选框--当取消所有子节点的选中状态父节点才会取消选中，我想当前父节点下面有一个子节点未被选中，当前父节点就不被选中，求解

**Comment by zTree** [comment]
利用 setting.check.chkboxType 设置  取消勾选时， 不操作父节点；然后在 onCheck 回调中根据勾选状态判断如果是取消勾选，则自行控制父节点的勾选状态即可
