### ISSUE TITLE
3.5.15  版本存在使用getNodesByParam无法精确匹配问题

### ISSUE THREAD

**Issue by lemensyang** [zTree/zTree_v3#219]
若树种存在id为：23、24、25等node节点时，使用getNodesByParam("id",2),可以查出所有的包含2的节点

**Comment by zTree** [comment]
抱歉，没有时间去专门测试你说的版本， 至少最新版本是没有这个问题的。

还有，你确定你那边产生这种情况不是因为使用 getNodesByParamFuzzy 这个方法，并且你的 id 都是 String 类型的么？
