### ISSUE TITLE
【图标问题】

### ISSUE THREAD

**Issue by MerlChen** [zTree/zTree_v3#220]
目前的zTree只支持两种类型图标：叶子节点，文件夹节点，希望官方能提供多种类型图标的方法

**Comment by zTree** [comment]
1、对于树的图标也就是 叶子节点、文件夹节点的图标，不知道你还想支持哪个部分的图标？ 自定义组件的部分制作的图标都请自行设计和制作
2、修改 css 可以很方便的支持 其他类型图标，包括字体图标，这个已经有 Demo
3、“官方” 也就我一个人， 我不是设计师，也无力设置更多的图标出来，所以请自行设计。
