### ISSUE TITLE
异步模式下，移动节点，不能正确返回当前父节点

### ISSUE THREAD

**Issue by Evaim** [zTree/zTree_v3#221]
@zTree 在异步模式下，修改树的层级结构时，使用transformToArray方法返回的节点中parent字段的值仍然为修改之前的值，请问是用法不对，还是什么原因？

**Comment by zTree** [comment]
1、zTree 对于节点数据没有 parent 字段，只有 parentTId 和 getParentNode()
2、只要是在树节点上拖拽节点修改了层级结构后，从 zTree 内获取的节点数据肯定是最新的
3、transformToArray 方法本身只是一个工具方法，至于其返回的数据是否你需要的，首先要看你传递进去的数据是否正确

**Comment by Evaim** [comment]
也就是说，移动节点（调整节点层级关系），ztree不会修改节点源数据的“parent”字段（也就是setting.data.simpleData.pIdKey配置的字段）的值为最新父节点的“id”（setting.data.simpleData.idKey配置的字段）是吗？

**Comment by zTree** [comment]
抱歉，我结实的不准确，不过你也没说清楚， 如果你修改了 pIdKey 的话， 那么这个对应的字段会被修改的，但还有一个先决条件——你必须开启简单数据模式才行的（simpleData.enable = true）

**Comment by Evaim** [comment]
是我没描述清楚，我之前用过这个功能，不过当时是直接用的json数据，没有用ajax，我移动节点层级发现被修改的节点的setting.data.simpleData.pIdKey字段的值会修改为最新的父节点的setting.data.simpleData.idKey字段的值，但昨天用ajax方式加载节点时，修改节点层级后，获取移动后的节点的setting.data.simpleData.pIdKey字段的值，发现还是之前的值，没有更新。
配置文件是这样的：
`data: {
			simpleData: {enable: true,pIdKey:"PARENT"},
			key:{url:null,name:"COLUMN_NAME",id:"ID"}
		},
		edit:{
			enable:true,
			showRemoveBtn:false,
			showRenameBtn:false,
			drag:{
			}
		},
		async:{
			enable:true,
			autoParam:["ID","CATEGORY_ID"],
			url:"sys/hierarchy/get"
		}`

**Comment by zTree** [comment]
1、zTree 只负责修改 前端已加载的数据各个相关属性
2、修改节点层级后，你必须要将修改的结果反馈给服务端保存最新修改的结果
3、不管你是否使用异步加载，针对已加载的节点，只要把节点修改层级后，肯定会自动修改父子关联的对应关系的。
