### ISSUE TITLE
IE8 'Element' is undefined using zTreeObj.selectNode

### ISSUE THREAD

**Issue by aniizen** [zTree/zTree_v3#222]
```
LINE : 1380 at jquery.ztree.core.js
                // code src: http://jsfiddle.net/08u6cxwj/
                if (!Element.prototype.scrollIntoViewIfNeeded) {
```
using IE8
case 1. this is ok when Silent mode is true. but cant scroll into. 
`zTreeObj.selectNode(node, false, true)`

case 2. this is fail. IE8 does not support "Element" 
`zTreeObj.selectNode(node, false, false)`

**Comment by zTree** [comment]
Please use  the last version files of zTree.  I try it in IE8, is ok.

IE8 support the 'Element' base. please see: [https://developer.mozilla.org/en-US/docs/Web/API/Element](https://developer.mozilla.org/en-US/docs/Web/API/Element)
