### ISSUE TITLE
【高级 增 / 删 / 改 节点】节点多次点击新增子节点不定时会收缩

### ISSUE THREAD

**Issue by sosoapi** [zTree/zTree_v3#223]
大神你好，最近在使用ztree v3.5.28的过程中发现对一个父节点多次点击新增子节点时，父节点会时不时由原先的展开状态变成收缩。对应的官网demo为【高级 增 / 删 / 改 节点】，该示例依然有这个问题。

**Comment by zTree** [comment]
请自行在 新建节点的事件中加入阻止时间冒泡的功能就可以了
