### ISSUE TITLE
节点名称过长展示不友好

### ISSUE THREAD

**Issue by sosoapi** [zTree/zTree_v3#224]
当节点名称过长的时候，导致展示不友好，同时节点相关的操作功能没办法展示出来。

**Comment by zTree** [comment]
这个请根据自己的界面需求调整样式。
例如：
1、设置固定宽度，超出后自动隐藏，显示省略号； 
2、或者让 树足够宽，或允许横向滚动； 
3、或者设置 节点允许自动换行（自动换行这个必须要隐藏 树的节点连接线，否则会导致样式异常）
