### ISSUE TITLE
@ztree，什么时候出一个下拉框的模糊搜索 扩展官方版？

### ISSUE THREAD

**Issue by linbren** [zTree/zTree_v3#225]
网上已经有不少网友做了类似的功能，良莠不齐。建议出一个官方版的。像select2一样的功能。

**Comment by zTree** [comment]
抱歉，目前不会做这个功能。

* 搜索框、图层样式不同的需求差别太大，无法一一满足
* 搜索结果的规则不同的需求差别太大，也无法一一满足
* 异步加载节点时，前端更是无法做到正确搜索

综上所述，目前不会制作这种扩展的，谢谢。

**Comment by bigablecat** [comment]
@zTree 
提炼了一个基于ztree的模糊搜索扩展，只在前端实现，请问是否可以作为contributor加入ztree项目？
项目演示：
https://bigablecat.github.io/programming/2017/07/03/zTreeFuzzySearch/
文件地址：
https://github.com/bigablecat/zTreeFuzzySearch/blob/master/js/fuzzysearch.js
使用方法：

@param zTreeId ztree对象的id,不需要#
@param searchField 输入框选择器
@param isHighLight 是否高亮,默认高亮,传入false禁用
@param isExpand 是否展开,默认合拢,传入true展开
@returns
*/
function fuzzySearch(zTreeId, searchField, isHighLight, isExpand){

**Comment by bigablecat** [comment]
@zTree 
提炼了一个基于ztree的模糊搜索扩展，只在前端实现，请问是否可以作为contributor加入ztree项目？
灵活之处在于用户只要把自定义的input元素的id传入即可

项目演示：
https://bigablecat.github.io/programming/2017/07/03/zTreeFuzzySearch/
文件地址：
https://github.com/bigablecat/zTreeFuzzySearch/blob/master/js/fuzzysearch.js

使用方法：
@param zTreeId ztree对象的id,不需要#
@param searchField 输入框选择器
@param isHighLight 是否高亮,默认高亮,传入false禁用
@param isExpand 是否展开,默认合拢,传入true展开
@returns
*/
function fuzzySearch(zTreeId, searchField, isHighLight, isExpand){
