### ISSUE TITLE
节点属性判断有疑问

### ISSUE THREAD

**Issue by maicss** [zTree/zTree_v3#226]
![ztree-bug](https://cloud.githubusercontent.com/assets/9784767/24396033/660c5116-13d4-11e7-8f43-5269a35f1881.png)

这是生成节点的数据（问题应该不在这个上面，但是还是放上来吧）：
```
[
    {"name":"agoda","id":1,"pId":0},
    {"name":"hotel","id":11,"pId":1},
    {"name":"check","id":111,"pId":11},
    {"name":"mapping","id":4,"pId":1},
    {"name":"correct","id":41,"pId":4}
]
```

前面那个框是另外一个tree，没有初始化，样式最小的样子，请忽略。

这个布尔值的生成是这句话：`isLastNode = (index < 0 && i == (nodes.length - 1));`，在`core:939`处，这样的结果是每个父组件的最后一个子级都是lastNode了，而不是选择树的最后一个子级，为啥不用`children.length`进行判断？还是对`lastNode`的定义不一样？

![ztree-bug2](https://cloud.githubusercontent.com/assets/9784767/24396707/b166b03c-13d6-11e7-8295-b7a0af7eeff1.png)

**Comment by maicss** [comment]
另外，我想得到每次选择的所有节点的名字。比如第一张图上，我想得到的数据是`agoda/hotel/check, agoda/mapping/correct`，如果内部有自定义数据的属性就好了，现在看来只有一个url，但是我这没啥效果……是我姿势不对么？

**Comment by zTree** [comment]
1. API上讲的很清楚： isLastNode —— 记录 treeNode 节点是否为同级节点中的最后一个节点。
   所以每一个父节点下的子节点集合中最后一个都是 last node

2. zTree 不负责生成你需要的这种数据格式，请自行拼接（可以 利用 getPath 方法）

**Comment by maicss** [comment]
ok, thanks
