### ISSUE TITLE
你好，请问zTree支持自定义样式吗？

### ISSUE THREAD

**Issue by brahmachen** [zTree/zTree_v3#227]
包括自定义节点内容和样式，如果有的话，能给我一个demo地址吗？

**Comment by zTree** [comment]
http://www.treejs.cn/v3/demo.php#_513

http://www.treejs.cn/v3/demo.php#_514

http://www.treejs.cn/v3/demo.php#_515

这些都是各种样式的 Demo，并且你都到了 Github 上来了， 直接下载源码，里面 有全部 demo 的源码呀。

顺便再给你个地址： https://my.oschina.net/dyhunter/blog/97535
这个是 zTree css 文件的详细说明

**Comment by brahmachen** [comment]
如果我的需求是这样的，用zTree好实现吗？我帮我们美工问的
![image](https://cloud.githubusercontent.com/assets/12797533/24445534/caf31592-149c-11e7-943d-35e7a91f0805.png)
