### ISSUE TITLE
关于全选和半选的问题

### ISSUE THREAD

**Issue by eyelandlau** [zTree/zTree_v3#229]
我的页面树型层级是需要一级级分级读取的  初始化页面会拿到第一级   可是第二级里有部分会被选中   我也能拿到第二级选中的父级id   可是无法把第一级有被选中子级进行半选提示   我只要设置半选  展开读取第二级就自动帮我全选了啊   这怎么解决呢

**Comment by zTree** [comment]
请检查你的代码逻辑， 我可以保证 zTree 的核心代码绝对没有任何一部分是根据父节点的勾选状态，去自动设置后来加入的子节点的勾选状态的。

**Comment by wowolyzh** [comment]
异步加载有对应的事件，可以在加载成功或失败事件中根据不同需求自行进行操作处理。

**Comment by eyelandlau** [comment]
没有用插件的异步加载事件  我用自己的加载+api手动添加进去的  确实是我代码逻辑问题  不过半选我建议不要设置一次之后就再也不计算全半选这种逻辑
