### ISSUE TITLE
拖拽树节点 onDrop，返回的 targetNode 对象不正确

### ISSUE THREAD

**Issue by xingwen1987** [zTree/zTree_v3#232]
在顶级没有节点的情况下，将节点拖拽至顶级，但是跟踪 targetNode，返回的却是相邻的节点，请作者跟踪这个BUG。
![image](https://cloud.githubusercontent.com/assets/15207100/25712151/6ac907be-3123-11e7-8ad7-7456332a4edd.png)

**Comment by zTree** [comment]
无需跟踪， 请你再仔细看看 onDrop 的 API 说明，有 target 就必然还有另一个配套的参数 moveType，这两个参数缺一不可！
