### ISSUE TITLE
异步加载出来的子节点，刷新整棵树后，节点下有子节点，但是用treeNode.children获取不到undefined

### ISSUE THREAD

**Issue by feifeihai120** [zTree/zTree_v3#234]

**Comment by feifeihai120** [comment]
$.fn.zTree.init($("#departSelect"), setting, dbDate);
var tree_obj = $.fn.zTree.getZTreeObj("departSelect");
//获取tree_obj的所有节点
var nodes = tree_obj.getNodes();

function expandTree(nodes_tree){
	for(var i=0;i<nodes_tree.length;i++){
	var isParent = nodes_tree[i].isParent;
	//判断是否父节点
	if(isParent){
	//调用展开方法
	zTreeOnExpand(null, null, nodes_tree[i]);
	tree_obj.updateNode(nodes_tree[i]);
	//获取此节点下所有子节点
	var nodes_next = nodes_tree[i].children;
	console.log(nodes_tree[i]);//有值,且有children值
	console.log(nodes_next );//此输出为undefined
}
}
}
//执行
expandTree(nodes);

**Comment by zTree** [comment]
1. 你的注释描述的情况明显有问题， 从代码执行过程来讲， 第一个 console.log 如果有值且有 children 值的时候， nodes_next 绝对不可能是 undefined

2. 关键问题是异步加载模式下， 父节点还没有子节点，且还没展开时 就是不存在 children 的值，即使你先执行了展开操作，也要等 异步加载完毕后才会生成 children 的值，所以你前面语句执行 展开，后面立刻就查找 children肯定不会有内容的！！！
