### ISSUE TITLE
checkNode方法中callbackFlag参数的疑问

### ISSUE THREAD

**Issue by jianxuejing** [zTree/zTree_v3#235]
checkNode方法中的callbackFlagBoolean参数为`true`时，只触发了当前node的onCheck事件。如果checkTypeFlag参数为`true`时，联动操作的节点并没有触发onCheck事件。
是本身设计就是这样还是我理解错误了？

按我的理解，联动的node也是应该触发onCheck事件的。
或者可以新加一个参数进行控制。

我是使用3.5.28版本，treeObj.checkNode(treeNode,false,true,true);

**Comment by zTree** [comment]
请参考API 中的： autoCheckTrigger （慎用！节点多的话，应该会影响性能）

**Comment by jianxuejing** [comment]
谢谢，果然有用！
