### ISSUE TITLE
好像zTree不支持自定义字号是吧？

### ISSUE THREAD

**Issue by gzlboy** [zTree/zTree_v3#236]
默认的12号字是在是太小了，如果我想用18号字体，行高也需要调整，应该怎么做可以实现？

**Comment by wowolyzh** [comment]
这个直接修改对应的样式就好了，zTree默认是在zTreeStyle里面的
`.ztree * {padding:0; margin:0; font-size:12px; font-family: Verdana, 

Arial, Helvetica, AppleGothic, sans-serif}`
设置了字体大小，但这个的话是全局字体大小样式，建议还是根据不同部分的需求进行修改，会比较好看。

**Comment by zTree** [comment]
https://my.oschina.net/dyhunter/blog/97535

 css 参考说明
