### ISSUE TITLE
check{enable：true}

### ISSUE THREAD

**Issue by garyl12** [zTree/zTree_v3#237]
按照demo里的样子 配置setting   直接copy 但是放在我的项目里死活就是出来不checkbox的框
查过excheck.js也引入了，还试过zTreeall.js,发现还是不行，谁可以告诉我究竟是什么原因，
<script src="../../js/plugin/zTree_v3/js/jquery.ztree.all.min.js" type="text/javascript" charset="utf-8"></script>
	<script src="../../js/plugin/zTree_v3/js/jquery.ztree.core.js" type="text/javascript" charset="utf-8"></script>
	<script src="../../js/plugin/zTree_v3/js/jquery.ztree.excheck.js" type="text/javascript" charset="utf-8"></script>
![image](https://cloud.githubusercontent.com/assets/19684437/26444242/2203c202-416e-11e7-9a59-944631f0ada2.png)
 结果如上图所示；
下边是setting信息
![image](https://cloud.githubusercontent.com/assets/19684437/26444266/4ea5196e-416e-11e7-973e-a620785cc31c.png)
who can tell me why ?

**Comment by zTree** [comment]
朋友，你的问题应该已经不是 js 了，而是 css 和 img 的问题，请你用 chrome 的调试工具检查你的 css 以及 img 的路径，看看这些 静态文件是否被正确加载？

**Comment by garyl12** [comment]
全都加载了，css里单独设置样式在页面上也起作用了，但就是不显示；
问题找到了  html里少l了个class=“ztree”
