### ISSUE TITLE
表格树的实现

### ISSUE THREAD

**Issue by zhaoxieluoke** [zTree/zTree_v3#239]
如题，怎么样实现表格树：p

**Comment by zTree** [comment]
抱歉，zTree 目前的 DOM 结构不太适于制作 表格树，如果硬要制作只能是利用 复杂的 css 设置每一行的单元格细节样式，并且自己设置每一行的 Dom 结构

**Comment by zhaoxieluoke** [comment]
@zTree   晓得了，谢过
