### ISSUE TITLE
BUG：节点数据为空

### ISSUE THREAD

**Issue by wodetian55** [zTree/zTree_v3#241]
在简约数据模式下，如果某条数据的key的value为0，那么在进行zTreeObj.getNodesByParam时候，该数据的key的value为null。
例如：
        var zNodes = [{"id":1,"pid":0},{"id":2,"pid":1}];
        var nodes = zTreeObj.getNodesByParam("pid",0);
nodes为空，因为在插入的数据的时候，ztree自动将value为0的值设置成为了null，我在反复调试输出后发现的。
那么要查询到pid为0的数据节点就只能这么折中：var nodes = zTreeObj.getNodesByParam("pid",null);

**Comment by jameslcj** [comment]
好像是你的设置问题, setting.data.simpleData.pIdKey 默认等于 pId, 而不是pid; setting.data.simpleData.pIdKey = "pid" 就可以解决这问题

**Comment by wodetian55** [comment]
我已经设置了pId为pid：
simpleData: {
                enable: true,
                pIdKey: "pid"
            }

**Comment by zTree** [comment]
@jameslcj 你说的接近了，但是错了！

@wodetian55  应该设置 setting.data.simpleData.rootPId = 0  这样才会保证所有的根节点的 pId 值都为 0； zTree 默认是 null 的。 请仔细看看对应的 API 文档
