### ISSUE TITLE
1.如何让单个节点不可编辑。2.拖拽节点是否可以把父节点带过来

### ISSUE THREAD

**Issue by yidianier** [zTree/zTree_v3#243]

**Comment by zTree** [comment]
1、看 API：beforeEditName 回调
2、利用 beforeDrop 回调， return false；阻止 zTree 默认的拖拽操作； 同时 根据选中的节点生成你需要的带有父节点的节点数据结构，然后利用 addNodes、removeNode 等方法自行处理。

问题：
1、你必须要要考虑的一种情况： 父节点 A； 子节点有 A1、A2、A3， 你拖拽 A1、A2 的时候 父节点是否仅仅是复制还是一定要移动？ 因为 原来的 A3 还要保留在原始位置的。 这个不是技术问题，纯粹属于你的业务需求

2、clone 父节点数据时，建议不要 clone children 属性，根据自己的数据结构自行生成 children 属性，避免把  A3 也移动到新的位置
