### ISSUE TITLE
异步加载节点, 能不能不同层级的节点用不同的url

### ISSUE THREAD

**Issue by 404157386** [zTree/zTree_v3#244]
1. 异步加载节点, 能不能不同层级的节点用不同的url, 不同的url传不同的参数。
2. 现在autoParam和otherParams是拼接起来的, 他们能不能嵌套，让autoParam包含在otherParams里面提交。

**Comment by zTree** [comment]
1. 请仔细看 API， url 属性是可以设置为 function 的
2. 不使用 autoParam 参数即可，利用 beforeAsync 回调， 自行拼接处理 otherParams 即可

**Comment by 404157386** [comment]
谢谢你的回答。
我现在用的是v3.5.24版本, otherParam是用formData的形式提交的, 能不能设置用request payload的形式提交?

**Comment by zTree** [comment]
setting.async.contentType 设置为 'application/json'

**Comment by screamsyk** [comment]
怎么才能提交json对象的形式呢？比如在request payload中的数据为
{
id:1,
name:"测试"
}

**Comment by zTree** [comment]
@screamsyk 
```
setting.async.contentType = 'application/json';
```

**Comment by screamsyk** [comment]
主要是参数的放置，现在无论是放在autoParam还是otherParam中，request payload中的参数形式始终是
x=1等，带有等号的这种，我没找到方法传一个对象的形式

**Comment by zTree** [comment]
@screamsyk 请仔细检查你的代码， 我只需要把 异步加载的 Demo 按照这个配置修改后，提交的数据就已经都是 json 格式的了

**Comment by screamsyk** [comment]
谢谢你的回答，我也试了那个Demo，的确可以传承json对象的形式，我再试试

**Comment by zTree** [comment]
@screamsyk 别忘检查你的 zTree 版本号
