### ISSUE TITLE
不在同一个父节点下的节点不能同时拖动

### ISSUE THREAD

**Issue by heyusysu** [zTree/zTree_v3#245]
我看到代码里有对同时拖动多个节点有一个限制，就是不同父节点下的节点不能同时拖动，如果把这个限制删除会有什么错误吗？
`if (nodes[0].parentTId !== _nodes[i].parentTId) {
nodes = [_node];
break;
}`

**Comment by zTree** [comment]
禁止不同父节点的节点同时拖动，主要就是为了避免 同时拖拽 有父子关系的节点。 这样就比较矛盾了。

例如： A 节点的子节点 A1、A2； 你同时拖拽 A 和 A2 ，那么 A1 该怎么办？

**Comment by Yourroot** [comment]
如果是复制那样，就不可能有这种问题了吧
