### ISSUE TITLE
Cursor style reset causes problems when using other libraries

### ISSUE THREAD

**Issue by jneuendorf** [zTree/zTree_v3#247]
Hi,

The cursor style attribute is set to `auto` here:
https://github.com/zTree/zTree_v3/blob/98a22e0619508cc04984a88d4ca58f99b4e9f91f/js/jquery.ztree.all.js#L3181

I for example use zTree and interactJS.
interactJS also sets a cursor but on the `<html>` node.
Because of zTree's body cursor style the cursor of interactJS never gets applied.

Thus it would be better to just remove the cursor from the body instead of setting it to `auto` like so:
`body.css("cursor", null);`

**Comment by zTree** [comment]
Thank you very much. I have fixed this issue. please check out the code in master.

```
body.css("cursor", "");
```

**Comment by jneuendorf** [comment]
Sorry, I haven't checked the latest code first!

**Comment by zTree** [comment]
I fixed this issue, after accept your advise.
