### ISSUE TITLE
勾选节点影响子父级节点关系，但是只是希望获取到单击的那个CheckBox的id

### ISSUE THREAD

**Issue by moahmn** [zTree/zTree_v3#248]
勾选节点影响子父级节点关系，但是只是希望获取到单击的那个CheckBox的id，请问有办法能够实现吗？

**Comment by zTree** [comment]
都能拿到对应的节点集合了， 自己循环一下不就能得到对应的节点 id 了吗？ 

另外，不要想着去得到 DOM 结构上 checkbox 的 id ，那个无意义。

**Comment by moahmn** [comment]
可能我没说明白吧
节点1
----节点2
-------节点3

我勾选中节点3，节点1,2都会被选中，treeObj.getCheckedNodes(true);会返回1,2,3节点。但是我只希望获取我点击的节点3这个节点的对象信息。

**Comment by zTree** [comment]
请参考 onCheck 回调

**Comment by moahmn** [comment]
解决了，非常感谢

**Comment by shen-lan** [comment]
> 解决了，非常感谢

怎么解决的？
