### ISSUE TITLE
这个项目的license是什么？

### ISSUE THREAD

**Issue by maicss** [zTree/zTree_v3#249]
作者这么认真，这个项目拿到钱了没啊……
为啥不加个license？
最起码商用收费啊。
我都见到了商用的了……

**Comment by zTree** [comment]
在官网 和 js 文件内有说明： 
* Licensed same as jquery - MIT License
* http://www.opensource.org/licenses/mit-license.php

所以基本上就是随便用了，不过还是非常感谢你的建议。

区区一棵树，不是什么大东西，就靠大家捐助以及针对初学者的教程收费了。
