### ISSUE TITLE
通过异步请求数据初始化zTree后如果返回数据为null，则树中的节点不会清空，且会再次触发异步请求

### ISSUE THREAD

**Issue by greaterwinner** [zTree/zTree_v3#251]
$.ajax({
				type : "POST",
				url : url,
				dataType : 'json',			
				async : false,
				success : function(data) {								
					$.fn.zTree.init(_this, settings, data);
				}
			});
如上代码，如果通过异步查询如果没有查询到满足条件的数据时树中的节点不会清空，且会再次触发异步请求；如果有数据返回则不会出现该问题。

**Comment by zTree** [comment]
估计你是 自己使用 ajax获取数据，同时又配置 zTree 进行了异步加载，那么当 data 为空时， zTree 就认为初始化未输入节点数据，所以就去进行异步加载了

**Comment by zTree** [comment]
自己返回 空数组 []  不就可以了？ 为何一定要返回 null

**Comment by zTree** [comment]
你写代码不调试么？
