### ISSUE TITLE
最新的版本异步加载设置autoParam时候，请求入参出错了

### ISSUE THREAD

**Issue by ye406932993** [zTree/zTree_v3#253]
写的设置  async:{
                    enable: true,
                    autoParam:["issueTypeCode=parentIssueType"],
                    contentType: "application/json",
                    type:"get",
                    url:
}
但是请求参数会变成：
{"parentIssueType":0}:
_:1499237716049

?{%22parentIssueType%22:0}&_=1499237716049

**Comment by zTree** [comment]
你都是用 application/json 了，为什么还要设置为 get 方式？？ 怎么也要 post 呀
