### ISSUE TITLE
How to using it with React? 

### ISSUE THREAD

**Issue by xgqfrms-gildata** [zTree/zTree_v3#256]
# npm & React

> It has been published to npm???

**Comment by xgqfrms-gildata** [comment]
# Yes, it is!

https://www.npmjs.com/package/ztree

**Comment by xgqfrms-gildata** [comment]
```sh

$ npm i -g npm to update

```

**Comment by zTree** [comment]
sorry, There is someone publish zTree to npm.  And zTree wasn't design for react

**Comment by xgqfrms-gildata** [comment]
Anyway, Thanks for your time!
