### ISSUE TITLE
怎么在Vue里使用ztree呢

### ISSUE THREAD

**Issue by ttflowerboys** [zTree/zTree_v3#257]
怎么在Vue里使用ztree呢

**Comment by zTree** [comment]
说白了，你在 vue 里面怎么使用 jQuery，就怎么使用 zTree ，毕竟 zTree 没有按照 vue 的模块进行构造

**Comment by c5ms** [comment]
@zTree  有什么优雅的方式替换jquery的ajax为其他呢?

**Comment by zTree** [comment]
这个貌似只能 优雅的坐在电脑前，认真的修改代码了吧？

**Comment by wayne798** [comment]
会有vue版本吗以后？

**Comment by c5ms** [comment]
大赞zTree zTree V587 旷古烁今,能前无古人之能,又后无来者之势.
若有VUE版本,必定千秋万代一统江湖.
