### ISSUE TITLE
拖拽一个子节点，变成直接拖拽整个父节点

### ISSUE THREAD

**Issue by Mavis-0211** [zTree/zTree_v3#258]
#243 根据您该问题的回答，我已经在beforeDrop方法中根据被选中的子节点获取到了这个父节点，但是拖拽的对象还是之前选中的子节点，我要如何把当前操作的对象treeNodes变成已经获取到的父节点呢

我的需求是从当前一个树中，拖拽复制节点到另外一棵树中。
1、原树种结构元素不变；
2、拖拽子节点时，直接把整个父节点复制过去。

![image](https://user-images.githubusercontent.com/15938214/28413670-08dee296-6d7b-11e7-958b-5e0b56835800.png)

**Comment by zTree** [comment]
beforeDrop 中 return false，然后利用 addNodes 方法自己添加就是了，止于添加的节点数据是什么完全根据你自己的需求构造就是了。

你是复制到另一棵树，所以一定要把原先的节点进行 clone ，你都能拿到父节点了，那就 clone 父节点就是了。 止于 里面 叶子节点 2-1 2-3 是否需要纯粹看你自己的需求了

**Comment by Mavis-0211** [comment]
@zTree 非常感谢，结合您说的，再仔细查看了下API，已经解决了(๑•̀ㅂ•́)و✧
