### ISSUE TITLE
拖拽问题

### ISSUE THREAD

**Issue by BeiKeJieDeLiuLangMao** [zTree/zTree_v3#261]
拖拽过程中不出现“表明位置的小箭头”
beforeDrog不触发事件
onDrog触发，但是Target为null
其他功能都正常
setting: {
        view: {
          addHoverDom: this.addHoverDom,
          removeHoverDom: this.removeHoverDom,
          selectedMulti: false
        },
        check: {
          enable: false
        },
        data: {
          simpleData: {
            enable: true
          }
        },
        edit: {
          enable: true
        },
        callback: {
          onClick: this.zTreeOnClick,
          beforeRename: this.zTreeBeforeRename,
          onRename: this.zTreeOnRename,
          beforeRemove: this.zTreeBeforeRemove,
          onRemove: this.zTreeOnRemove,
          beforeDrag: this.zTreeBeforeDrag,
          beforeDrop: this.zTreeBeforeDrop,
          onDrop: this.zTreeOnDrop
        }
      }

**Comment by zTree** [comment]
请对照 Demo 检查样式，有可能是样式导致的箭头无效。

建议采用未压缩版的 zTree 进行调试， 找到 代码中
```
if (tmpArrow) tmpArrow.remove();
```
将此行代码屏蔽后，可以保证拖拽结束后，箭头Dom 仍然存在，便于调试

**Comment by BeiKeJieDeLiuLangMao** [comment]
我测试过样式 发现如果我把arraw的样式挂在span上都是正常的显示
并且我按照您说的 注释掉该行代码之后没有改变
在我这里那个箭头一直不出来

**Comment by zTree** [comment]
让你注释后，不可能会出现呀，但是注释后，dom 依然存在，你就可以去检查 对应的样式了，看看是你自己页面上的哪个样式导致的箭头看不见了。

如果不注释的话，你无法检查 箭头的样式是否正确

**Comment by BeiKeJieDeLiuLangMao** [comment]
哦 我按照您说的找到了这个箭头的dom
发现它一生成出来就迅速
element.style {
    display: none;
}

**Comment by BeiKeJieDeLiuLangMao** [comment]
我改写箭头样式display: inline-block!important;之后 发现它一直处于页面最左下角

**Comment by BeiKeJieDeLiuLangMao** [comment]
当drag Flag == 1 时 tmpTarget 先是undefined 然后一直是null

**Comment by BeiKeJieDeLiuLangMao** [comment]
我发现为什么有问题了 原来是一个同事把TreeId给改了和setting的中的treeid对不上了

**Comment by zTree** [comment]
你这么看是没什么意义的， 本身箭头也不是始终显示的呀，只有需要显示的时候才会显示出来。

你先把你自己的样式都屏蔽住，你看看箭头是否正常。。或者你只看我提供的标准Demo，看看箭头是否正常。。
