### ISSUE TITLE
TypeError: node.getParentNode(...) is null

### ISSUE THREAD

**Issue by M7lrv** [zTree/zTree_v3#264]
首先我知道这是父节点为null了，我的代码是：
`/**
 * 刷新选中的节点（如果没有选中就全部刷新）
 * @param zTree			zTree对象
 * @param isReload		是否强制刷新整个树
 */
function extendRefreshSelectNode(zTree,isReload){
	if(zTree == null || typeof(zTree) == "undefined")
		return;
	else if(isReload)
		zTree.reAsyncChildNodes(null, "refresh");
	else{
	    nodes = zTree.getSelectedNodes();/*获取 zTree 当前被选中的节点数据集合*/
		alert(nodes.length);
		if (nodes.length > 0) {
	    	var thisNode = nodes[0];
	    	var parent = thisNode.getParentNode();//当前节点的父节点
	    	var chields = thisNode.children;//当前节点的子节点
	    	console.log("当前节点："+thisNode.title+",父节点："+(parent==null?"":parent.title)+",当前节点子节点："+(chields==null?"":chields.length));
	    	if(chields == null || typeof(chields) == "undefined"){//没有子节点
	    		if(parent == null || typeof(parent) == "undefined"){//没有父节点
	    			zTree.reAsyncChildNodes(null, "refresh");
	    			
	    			zTree.expandNode(thisNode, true, true, true);//展开这个节点
	    			zTree.selectNode(thisNode);  /*选中指定节点*/  
	    		}
	    		else{
	    			zTree.reAsyncChildNodes(thisNode, "refresh", true);
	    			zTree.expandNode(thisNode, true, true, true);//展开这个节点
	    			zTree.selectNode(thisNode);  /*选中指定节点*/  
	    		}
	    	}
	        else{
	        	zTree.reAsyncChildNodes(thisNode, "refresh", true);
	        	
	        	zTree.expandNode(thisNode, true, true, true);//展开这个节点
	        	zTree.selectNode(thisNode);/*选中指定节点*/
	        }
	    }else{
			zTree.reAsyncChildNodes(null, "refresh");
	    }
	}
}`

功能是添加了一个节点后自动刷新这个节点(并且选中这个节点)
我父节点没有子节点，我选中它添加了子节点后就报错了，配置我用的异步
`//异步获取json数据  
		        async : {    
		            enable : true,url : "{:U('Admin/Menu/gridList')}", // Ajax 获取数据的 URL 地址    
		            autoParam : ["id"], //ajax提交的时候，传的是id值  
		            dataFilter: extendAjaxDataFilter//数据加载完毕后过滤
		        },
`
请问这算个bug嘛？还是我的写法有问题？

**Comment by zTree** [comment]
当然有问题了，你触发刷新该节点时，就是触发了一个异步操作，然后在异步操作还没完成时，你就立刻去执行展开和选中操作，当然要出问题了。 怎么也要等异步操作完成后在处理呀。
目前最新版的 zTree 中，其实已经增加了 callback 回调，只不过没有加到 API 说明里面。（不好意思，上次手懒了，近期一定加上）

```
reAsyncChildNodes: function (parentNode, reloadType, isSilent, callback) {
......
}
```

**Comment by M7lrv** [comment]
这样的索，我下载最新的试试

**Comment by M7lrv** [comment]
callback的参数是啥？文档里好像没有写

**Comment by zTree** [comment]
调试一下不就知道了，另外，这个 callback 也的确没有参数。
