### ISSUE TITLE
哥，取消编辑状态无效，代码一直死循环，试了刷新树都没用。怎么取消编辑状态？

### ISSUE THREAD

**Issue by EthanDCX** [zTree/zTree_v3#265]
````
function zTreeBeforeRename(treeId, treeNode, newName, isCancel) {
    var msg = "确定要修改吗？\n\n请确认！";
    if (confirm(msg)==true){
        $.ajax({
            type:"GET",
            url:"/jcntHelp/catalog/updateNode.do",
            dataType:"html",
            data:{id:treeNode.id,newName:newName},
            success:function(data){
            },
            error:function(){
                alert("方法执行不成功!");
            }
        });
        return true;
    }else{
        zTreeObj.cancelEditName();
        zTreeObj.refresh();
        return false;
    }
}
```

**Comment by zTree** [comment]
请你注意 isCancel 参数！！！！

**Comment by EthanDCX** [comment]
用了isCancel也不好使

**Comment by zTree** [comment]
```
setTimeout(function() {
  zTreeObj.cancelEditName();
}, 0);
return false;
```

补充，
1、你使用 refresh 方法干什么？ API 都不建议使用的。
2、你的 isCancel 如何使用的？

**Comment by zTree** [comment]
在这里把问题解决了，我再 close，请不要重复发问题

**Comment by EthanDCX** [comment]
哥，这是我用的isCancel。
function zTreeBeforeRename(treeId, treeNode, newName, isCancel) {
        if(!isCancel){
            $.ajax({
                type:"GET",
                url:"/jcntHelp/catalog/updateNode.do",
                dataType:"html",
                data:{id:treeNode.id,newName:newName},
                success:function(data){
                },
                error:function(){
                    alert("方法执行不成功!");
                }
            });
            return true;
        }else{
            zTreeObj.cancelEditName();
            return false;
        } 
按esc也取消不了编辑状态

**Comment by zTree** [comment]
你这写的是神马呀， 把你自己的逻辑都破坏了！！！

有木有看 API， isCancel 是什么？？？ 

isCancel 为 true 时，表明当前是取消操作，这时候应该直接 return true 给 zTree ；

按照你的写法一直就是死循环了

**Comment by zTree** [comment]
另外， 学习一下 markdown 如何书写 代码段！！！ （看看我给你修改的帖子内容）

**Comment by EthanDCX** [comment]
嗯呢，第一次用,不知道这里的规矩，谢谢哥

**Comment by EthanDCX** [comment]
```javascript
function zTreeBeforeRename(treeId, treeNode, newName, isCancel) {
        if(isCancel){   //isCancel表示取消操作
            zTreeObj.cancelEditName();
            return true;
        }else{
            $.ajax({
                type:"GET",
                url:"/jcntHelp/catalog/updateNode.do",
                dataType:"html",
                data:{id:treeNode.id,newName:newName},
                success:function(data){
                },
                error:function(){
                    alert("方法执行不成功!");
                }
            });
            return true;
        }
```

哥，按esc还不好使，zTreeObj.cancelEditName();也没生效

**Comment by zTree** [comment]
isCancel 表明是 zTree 已经收到取消操作了！！ 你直接 return true 就是了，这时候 return true 表明同意让zTree 取消编辑！！ 你不要再使用 cancelEditName 了呀！！！！！！！！！！！！

**Comment by EthanDCX** [comment]
好，问题解决了。谢谢哥

**Comment by EthanDCX** [comment]
cancelEditName 怎么用啊？不生效
