### ISSUE TITLE
项目经理要求必须点取消退出编辑状态（esc退出说是用户体验不好），现在能实现退出编辑状态，但恢复不了原名称

### ISSUE THREAD

**Issue by EthanDCX** [zTree/zTree_v3#268]
```JavaScript
function zTreeBeforeRename(treeId, treeNode, newName, isCancel) {
  var msg = "确定要修改吗？\n\n请确认！";
    if (confirm(msg)==true){
        $.ajax({
            type:"GET",
            url:"/jcntHelp/catalog/updateNode.do",
            dataType:"html",
            data:{id:treeNode.id,newName:newName},
            success:function(data){
            },
            error:function(){
                alert("方法执行不成功!");
            }
        });
        return true;
    }else{
        zTreeObj.cancelEditName();
        zTreeObj.setEditable(false);
    }
    zTreeObj.setEditable(true);
    return true;
}
```

**Comment by zTree** [comment]
要听项目经理的话！

看看前两天这个问题：https://github.com/zTree/zTree_v3/issues/265

**Comment by EthanDCX** [comment]
esc退出能实现了,但点取消退出编辑状态用zTreeObj.cancelEditName无效，哥你这个设计有问题吧

**Comment by EthanDCX** [comment]
感觉应该分具体点，断点调试跑到cancelEditName老是跳回zTreeBeforeRename，很尴尬。要是 cancelEditName的过程前和过程后设置 beforeCancelEditName 和 onCancelEditName就好了，不然有点绕不易理解。
像我这个点取消后虽然取消编辑了，但恢复不了原名称

**Comment by EthanDCX** [comment]
API里是这样说的：isCancel = true 表示取消编辑操作（按下 ESC 或 使用 cancelEditName 方法） 
要用cancelEditName ，那么cancelEditName由谁去调用

**Comment by zTree** [comment]
判断 isCancel = true 的时候，你直接 return true 不就可以了？

**Comment by EthanDCX** [comment]
return true 恢复不了原名称

**Comment by EthanDCX** [comment]
我这个不让用isCancel，必须的通过点取消按钮，烦请你看下代码，return true是可以取消，但恢复不了原名称。

**Comment by zTree** [comment]
什么叫做不让用 isCancel，项目经理还能管你用什么参数么？ 只要你使用了 取消编辑的方法，就会触发这个回调，并且 isCancel 就会是 true，除非你别使用 zTree 默认的编辑功能。 zTree 默认的取消编辑方法就会自动还原名称，除非你们还对节点做了什么处理。

试试下面这段代码， 你怎么修改，都让你还原会原先的名称，自己参考着修改自己的代码吧
```
beforeRename: function(treeId, treeNode, newName, isCancel) {
	if (isCancel) {
		return true;
	}
	setTimeout(function() {
		var zTree = $.fn.zTree.getZTreeObj("treeDemo");
		zTree.cancelEditName();
	},0);
	return false;
}
```
