### ISSUE TITLE
showTitle属性没有考虑nameIsHTML属性

### ISSUE THREAD

**Issue by netmou** [zTree/zTree_v3#269]
当nameIsHTML=true,时showTitle不应把 html标记也显示出来

**Comment by netmou** [comment]
makeDOMNodeNameBefore: function (html, setting, node) {
                var title = data.getNodeTitle(setting, node),
                    url = view.makeNodeUrl(setting, node),
                    fontcss = view.makeNodeFontCss(setting, node),
                    fontStyle = [];
                for (var f in fontcss) {
                    fontStyle.push(f, ":", fontcss[f], ";");
                }
                html.push("<a id='", node.tId, consts.id.A, "' class='", consts.className.LEVEL, node.level, "' treeNode", consts.id.A, " onclick=\"", (node.click || ''),
                    "\" ", ((url != null && url.length > 0) ? "href='" + url + "'" : ""), " target='", view.makeNodeTarget(node), "' style='", fontStyle.join(''),
                    "'");
                **if (tools.apply(setting.view.showTitle, [setting.treeId, node], setting.view.showTitle) && title) {
                    html.push("title='", title.replace(/'/g, "&#39;").replace(/</g, '&lt;').replace(/>/g, '&gt;'), "'");
                }**
                html.push(">");
            },

**Comment by netmou** [comment]
if(!setting.view.nameIsHTML){
                    html.push("title='", title.replace(/'/g, "&#39;").replace(/</g, '&lt;').replace(/>/g, '&gt;'), "'");
                    }else{
                    html.push("title='", title.replace(/<(?:.|\s)*?>/g,"").replace(/'/g, "&#39;").replace(/</g, '&lt;').replace(/>/g, '&gt;'), "'");
                    }

**Comment by zTree** [comment]
感谢你的建议，不过 title 本身当初并不是为了直接显示 name 来设计的， title 其实是针对于单独的 title 属性，只是不设置 title 的时候直接使用 name 而已。 所以你只需要把你这个处理 name 数据的规则放到 zTree 外面， 把 name 处理后的 value 赋值给 title 属性，足矣

**Comment by netmou** [comment]
放在外面怎么处理？
