### ISSUE TITLE
大数据量类似数据（9k），模糊查询卡死

### ISSUE THREAD

**Issue by zxx121** [zTree/zTree_v3#272]
环境 ： IE9及以上
数据量 ： 9k以上
是否必现：必现
描述：当使用ztree加载数据，数据名称类似（i1，i2，...）,假使都没有子节点数据，使用“i”进行查询并且定位到查询到的数据（即实现搜索的功能），页面卡死，请问有解决方法吗？

**Comment by zTree** [comment]
是直接使用 getNodesByParams 这个方法就会卡死？ 还是你搜索到结果后处理 DOM 时卡死？ 请先分清楚这两种情况。。

**Comment by fairyly** [comment]
模糊查询时候怎么做可以重新渲染dom树，只显示搜索到的节点？

**Comment by zTree** [comment]
@fairyly 自己组织数据，重新 init 就是了

**Comment by bigablecat** [comment]
@zTree 我提炼了一个基于ztree的模糊搜索扩展，只在前端实现，请问是否可以作为contributor加入ztree项目？
项目演示：
https://bigablecat.github.io/programming/2017/07/03/zTreeFuzzySearch/
文件地址：
https://github.com/bigablecat/zTreeFuzzySearch/blob/master/js/fuzzysearch.js
使用方法：
 * @param zTreeId ztree对象的id,不需要#
 * @param searchField 输入框选择器
 * @param isHighLight 是否高亮,默认高亮,传入false禁用
 * @param isExpand 是否展开,默认合拢,传入true展开
 * @returns
 */	
 function fuzzySearch(zTreeId, searchField, isHighLight, isExpand){

**Comment by bigablecat** [comment]
@zTree 
提炼了一个基于ztree的模糊搜索扩展，只在前端实现，请问是否可以作为contributor加入ztree项目？
灵活之处在于用户只要把自定义的input元素的id传入即可

项目演示：
https://bigablecat.github.io/programming/2017/07/03/zTreeFuzzySearch/
文件地址：
https://github.com/bigablecat/zTreeFuzzySearch/blob/master/js/fuzzysearch.js

使用方法：
@param zTreeId ztree对象的id,不需要#
@param searchField 输入框选择器
@param isHighLight 是否高亮,默认高亮,传入false禁用
@param isExpand 是否展开,默认合拢,传入true展开
@returns
*/
function fuzzySearch(zTreeId, searchField, isHighLight, isExpand){

**Comment by zTree** [comment]
@bigablecat 请别同样内容到处粘贴了。。。谢谢

**Comment by zTree** [comment]
@bigablecat 非常感谢！！！  想作为 contributor 其实很简单，你只需要 对 zTree 的代码进行修改，然后提交 Pull Request ，被我确认收录后，就自动被加入为 contributor 了！

https://github.com/zTree/zTree_v3/graphs/contributors
这上面的朋友都是发了 pull request 被我确认收录的。

你这套代码我建议你 模仿 Demo：http://www.treejs.cn/v3/demo.php#_113 制作一套测试页面，放在 zTree 的 Demo 目录下，保证其能够正常工作即可（如果可以的话，同时提供 中英文两套 Demo）
Demo 目录上的数据我自行添加就可以了。 再次表示感谢

**Comment by bigablecat** [comment]
@zTree 
非常感谢ztree回复。
我这两天就按照demo做测试页面，提交以后烦请对我的代码在格式上做一些优化指导。

**Comment by bigablecat** [comment]
@zTree 
昨天提交了pull request，同时发了一封邮件给Hunter大神，如果有问题直接邮件联系:)

**Comment by ZhangWenJunR** [comment]
遇到同样的问题，用的fuzzySearch方法模糊查询，请问怎么解决呢
