### ISSUE TITLE
如果后端 遍历好 数据，感觉没必要执行transformTozTreeFormat 请多指教

### ISSUE THREAD

**Issue by bigbugor** [zTree/zTree_v3#274]
您好： 如果后端返回的数据是 递归好的 tree类型的list(包含children) 我感觉没必要 执行 transformTozTreeFormat函数中的for循环 ，直接return 就行。实现方法：1.在seting中添加一个属性做标示；2.当transformTozTreeFormat中获取到标示 直接return 。

**Comment by zTree** [comment]
你好，感谢你的建议。

是可以按照你说的这么做，但这样就又要多一个参数进行配置，而且很多人并不是在后端生成好树结构的数据的。  另外， transformTozTreeFormat 的 for 循环应该也不会浪费太多的性能，又不是 嵌套的for 循环去把你所有的节点数据都遍历，他仅仅是遍历一下你提供的 数组而已，这样的话，对于你这种都生成好的数据，也只是遍历了一下根节点的数据而已，应该不会很多吧。

综上所述，就没必要为这一点儿优化处理增加一个配置了，你觉得呢？
