### ISSUE TITLE
zTree如何做权限管理控制

### ISSUE THREAD

**Issue by EthanDCX** [zTree/zTree_v3#275]
![image](https://user-images.githubusercontent.com/18240991/29971255-348d6d9e-8f5a-11e7-93a5-16f11ba3a3f9.png)
比如说 我想登陆管理员以后，才展示这些节点的增删改功能，否则就没有权限操作，请教下思路

**Comment by zTree** [comment]
抱歉，居然在你 close 的时候我才收到的通知。。。估计你已经解决了吧？

其实这个 编辑、删除按钮是否显示都是可以配置的，而新建的按钮是你自己可以控制是否显示的
