### ISSUE TITLE
如何修改编辑节点时的样式？

### ISSUE THREAD

**Issue by coderew** [zTree/zTree_v3#276]
官方demo   exedit/drag_super.html中，编辑节点，会出现浅蓝色的边框，这个蓝色的边框是怎么出现的？没有找到是在哪个标签或者样式上，我想修改编辑时输入框的样式，该怎么修改？

**Comment by zTree** [comment]
蓝色边框是浏览器自带的。。。有样式可以处理

http://blog.163.com/zx_1258/blog/static/133233799201211781436884/

你直接修改 zTree 的css 文件就可以了
