### ISSUE TITLE
给节点nodes 增加一个自定义的属性？

### ISSUE THREAD

**Issue by CangJieZ** [zTree/zTree_v3#277]
作者辛苦了，有个问题请教下，nodes 能否加入自定义的属性，或者有方法能知道某个nodes 是否是最底层的节点？

**Comment by zTree** [comment]
节点可以随意添加自定义的属性呀，只要不跟 zTree 默认使用的属性冲突就是了。。使用时直接从 zTree 内获取的节点数据上就可以获取；

另外 node.level 就是 节点的层级， 默认的 node.children 可以知道该节点是否有子节点， node.isParent 可以知道该节点是否是父节点。。。
