### ISSUE TITLE
如何修改拖动时的样式？

### ISSUE THREAD

**Issue by coderew** [zTree/zTree_v3#280]
我想修改拖拽时的样式，但是没有找到相应的类，请问在哪里？

**Comment by coderew** [comment]
找到了，在这个类中：ul.ztree.zTreeDragUL

**Comment by coderew** [comment]
在  ul.ztree.zTreeDragUL中

**Comment by zTree** [comment]
https://my.oschina.net/dyhunter/blog/97535

这是 Css 文件的详解
