### ISSUE TITLE
异步模式，如果checkbox勾选了该项，再展开时，子项无法自动勾选

### ISSUE THREAD

**Issue by gozhhu** [zTree/zTree_v3#281]
autoParam也无法传过去是否处于选中状态，否则可以自己set下check状态。

**Comment by zTree** [comment]
异步加载时，没有功能让加载的子节点随 父节点自动勾选， 你有两种解决方案：
1、后端解决，但你说的 autoParam无法传递是不应该的，请你对照 异步加载的Demo 检查你的配置是否正确。还有就是需要检查后台接收的参数是否正常，根据父节点的勾选状态去设置子节点的 checked 属性

2、前端解决，利用 setting.async.dataFilter 这个回调，可以在 收到 子节点数据后 先进行一次 数据的处理，zTree 会将 dataFilter 返回的数据添加到 树上的。
