### ISSUE TITLE
index.js not found

### ISSUE THREAD

**Issue by lianzhao** [zTree/zTree_v3#282]
the `main` property in [package.json](https://github.com/zTree/zTree_v3/blob/master/package.json#L9) pointed to `index.js`, which is not found

**Comment by zTree** [comment]
sorry, the main file is not used in this property. 
I will delete this property. Thanks

**Comment by lianzhao** [comment]
well, I think you can set `main` property to [js/jquery.ztree.all.js](https://github.com/zTree/zTree_v3/blob/master/js/jquery.ztree.all.js), as this [npm package](https://www.npmjs.com/package/ztree) did.
