### ISSUE TITLE
(IE9) vue2.0 使用ztree的问题

### ISSUE THREAD

**Issue by yishangtanhuan** [zTree/zTree_v3#284]
在vue2.0中使用ztree的异步加载功能，在现代浏览器（除ie9）上是正常的，但是在ie9中，页面没报错，但是异步的请求也没发送~~

**Comment by zTree** [comment]
请你再仔细检查一下相关代码吧，你用 浏览器访问官网的 Demo，应该都是可以正常的。另外，核实一下你的 zTree 版本

**Comment by yishangtanhuan** [comment]
是，我代码的问题，开发的时候跨域访问的api，到线上之后不用跨域了，但是相关的跨域代码没有注释，所以在IE9上无法显示，ztree是没有问题的~~
