### ISSUE TITLE
关于大数据量的情况下，初始化的时候默认一些节点复选框选中的性能问题

### ISSUE THREAD

**Issue by simbaHuang** [zTree/zTree_v3#285]
前提：我这边大概3W的数据，然后初始化的时候默认有2k多或3K多的节点的复选框是选中状态。
实现代码：
ps：data.data是后台返回的默认选中的数据，一般有2k多；
       $scope.ztreePvg是树对象。代码如下：
```
                var i, len = data.data.length, _node = null;
                for(i = 0; i < len; i ++){
                    //在左侧组织树中获取当前需要被勾选的节点
                    _node = $scope.ztreePvg.getNodesByParam('Id', data.data[i].Id);
                    //左侧组织树勾选节点
                    _node[0] && $scope.ztreePvg.checkNode(_node[0], true, true);
                }
```

然后页面就会长时间的卡顿，chrome一般要20多秒，IE浏览器会直接卡死。
看了下源码 getNodesByParam 这个方法是对所有数据做循环，递归。

看了下官网的API好像也没有其他方法可以通过 idKey 来获取节点。
想了解下有没有啥好的解决方案！谢谢！

**Comment by zTree** [comment]
疯了，上万的数据一次性加载后，还同时 勾选 几千个checkbox，肯定会卡呀！
1、必须要做异步加载，分层逐级加载
2、getNodesByParam 就是遍历获取的，并没有针对用户的 id 做 key-value 关联映射，只是针对zTree 自己的 tId 制作了 map，但这个不是你这里卡顿的原因。

因为 checkbox 勾选会影响父级节点的半勾选状态，所以多少会有性能问题，如果你不是同一个父节点下就有几千个子节点，那就赶紧做成异步加载吧，用户不展开，就不加载对应的子节点，这样才能真正的提升效率

**Comment by simbaHuang** [comment]
现在就是同一个节点下可能会有几千个节点的这种情况，
因为有 checkbox 的存在，异步加载感觉不是很方便，全选的时候还需要再去请求数据。

我这边树的情况一般是这样的：
顶级是固定只有一个，二级结构一般只有十几个，然后大量数据是挂在第三级或者第四级。

初始化的时候是默认请求全部的数据，默认展开顶级，其余的都是默认收起的状态。
然后展开的时候我这边做了一个扩展处理，大概就是200ms加载200个节点，就不会一下子全部展开，这样子处理一下的话效果还是可以的。

然后唯一卡顿的情况就是初始化有几千个默认选中的时候，就是最开始那个贴出来的那个循环处理比较耗时间。我准备试下用 idKey 做一个 key-value的映射缓存，看下具体效果。

非常感谢你的建议，谢谢！

**Comment by lb091188** [comment]
直接处理数据节点的 处理完成在初始化
![image](https://user-images.githubusercontent.com/16659166/48238650-b0af1100-e406-11e8-8d35-b526af56ffd1.png)
