### ISSUE TITLE
能自己处理异步数据吗？

### ISSUE THREAD

**Issue by dusksoft** [zTree/zTree_v3#286]
接口返回的数据结构和zTree需要的结构有点不一样，我能自己拿到数据自己在本地组装吗？

**Comment by zTree** [comment]
当然可以，自己处理后， 传给zTree 就是了，如果使用 zTree 的异步加载，那么要利用 setting.async.dataFilter 这个回调

**Comment by dusksoft** [comment]
再请教个问题，因为我的分页的总页数是服务端下发的，当数据显示完后，我得重新去更新一下父节点的自定义控件addDiyDom部分的代码，应该怎么做？
