### ISSUE TITLE
请教分页的问题。

### ISSUE THREAD

**Issue by dusksoft** [zTree/zTree_v3#287]
因为我的分页的总页数是服务端下发的，当数据显示完后，我得重新去更新一下父节点的自定义控件addDiyDom部分的代码，应该怎么做？

**Comment by zTree** [comment]
利用 zTree 的 Dom 命名规则，拼好 id 找到 dom 直接修改就是了，尤其 addDiyDom 部分你更是可以自己制作 id 规则

**Comment by dusksoft** [comment]
明白了，谢谢
