### ISSUE TITLE
请问有方法直接改变clickFLag的值

### ISSUE THREAD

**Issue by justforuse** [zTree/zTree_v3#289]
我要做的是按住shift键会选中所有子节点，但是也会保留之前选中的节点。
但现在会自动清除之前选中的节点，因为clickFlag为0。
请问有没有修改clickFlag的值或者其他方法呢？

**Comment by zTree** [comment]
zTree 目前默认支持 Ctrl | Cmd 键，不支持 shift键，如果一定要支持 shift 键只能是自己制作事件监控，或者是去修改源码了

**Comment by justforuse** [comment]
嗯，我现在是存储了上个状态选中的节点，然后shift点击后再重新将其选中
