### ISSUE TITLE
请问有无方法可以获取节点当前是否处于选中状态

### ISSUE THREAD

**Issue by justforuse** [zTree/zTree_v3#290]
我想获取某个节点当前是否处于选中状态，这个节点没有被点击，所以无法根据clickFlag判断。
我现在的做法是获取所有选中的节点，然后在判断这个节点是否包含其中。
想节点有没有直接的方法或者属性来标识这个选中状态呢？

（不使用复选框功能）

**Comment by zTree** [comment]
没有，只能是从 getSelectedNodes 方法中去比对
