### ISSUE TITLE
zTreeObj.transformToArray on getCheckedNodes() gives wrong result

### ISSUE THREAD

**Issue by abulka** [zTree/zTree_v3#291]
When I transformToArray(nodes) where nodes is treeObj.getCheckedNodes() I get an array which is the entire tree of nodes, not just the checked nodes.  The result should be just the checked nodes.  Is this a bug?

E.g. If I have a tree of 30 nodes, and 7 are checked:

```
    let treeObj = $.fn.zTree.getZTreeObj("tree");

    let nodes = treeObj.getCheckedNodes();
    console.log(nodes.length)  // 7, corrrect

    nodes = treeObj.transformToArray(treeObj.getCheckedNodes())
    console.log(nodes.length)  // 30, incorrect
```

**Comment by zTree** [comment]
hi,

the transformToArray() function is used to get the node's all child nodes. 

so, you get the  30.

the  getCheckedNodes() is the nodes what you want to get. please don't use transformToArray.
