### ISSUE TITLE
自定义数据格式中的open属性

### ISSUE THREAD

**Issue by MrZhangFengfeng** [zTree/zTree_v3#292]
`Id: 1, PId: 0, NAME: "Policy", OPEN: true, CHECKED: true。`
除了OPEN无法实现自定义外，其余均可以实现自定义。  OPEN 只能小写open才可以。 有什么解决办法吗？

**Comment by zTree** [comment]
因为不是所有属性都支持自定义的， 请自行在前端处理一下数据吧

**Comment by MrZhangFengfeng** [comment]
目前就是自行处理的，谢谢。
