### ISSUE TITLE
using zTree with Polymer v2

### ISSUE THREAD

**Issue by chisholmd** [zTree/zTree_v3#293]
I have two sites, one is developed using Polymer v1 the other is Polymer v2.  I have zTree working fine in the v1 site but I am having trouble on the v2 site.  BUT I don't know that the problem is polymer or not.

The only difference I can spot so far is how $("treeDemo") passes a reference to init().  In both cases I have this:
`<ul id="treeDemo" class="ztree"></ul>`

`$.fn.zTree.init($("#treeDemo"), this.settings, this.data);`

In the poly v1 site the UL is passed into init like this:
![image](https://user-images.githubusercontent.com/13528823/32110466-742229be-baec-11e7-8b18-8c866bf08216.png)

In the Poly v2 site the UL is passed in like this:
![image](https://user-images.githubusercontent.com/13528823/32110507-839f25f4-baec-11e7-827e-d43072b29e93.png)

Any ideas?

**Comment by chisholmd** [comment]
Hmmm I don't normally use jQuery but looking at this it seems obvious to me now that it is not getting a reference to the UL at all.

**Comment by chisholmd** [comment]
This worked
 var treeEl = Polymer.dom(this.root).querySelector('.ztree');
$.fn.zTree.init($(treeEl), this.settings, this.data);

I should title this using zTree with Polymer

**Comment by zTree** [comment]
Do you resolve this issue?

**Comment by chisholmd** [comment]
Yes, my last post contained what worked for me, thx
