### ISSUE TITLE
如何实时异步加载树节点

### ISSUE THREAD

**Issue by pangniur** [zTree/zTree_v3#305]
1、通过setting.async的基本配置可以实现便捷的异步加载树节点
但是发现除了第一次展开请求ajax外，以后展开就不请求ajax了
那么问题来了，如何每次点击节点的时候都请求ajax

2、我想到的方案有两种，
一、 onExpand事件中，如果不是第一次展开，则调用方法reAsyncChildNodes
        但是不会判断“第一次展开”

二、每次beforeExpand时，清空该节点下面的孩子nodes，然后设置该节点的zAsync=false

3、我用上述方案二实现了，实时异步加载树节点
     但是总觉得那里怪怪的，或者说不知道正确的方法是什么？

**Comment by zTree** [comment]
1、你的需求有问题呀， ajax 就是为了提升性能，为何你需要每次点击节点都要重新加载节点？

2、你一边说点击节点，一边又是 onExpand、beforeExpand 回调，那么我暂且认为你说的是展开父节点，如果是这样的话，那么你的方案二是可以实现你这个需求的。。。我觉得就是怪怪的，但不是因为实现的方案问题怪，而是这种需求太奇怪了。。。。

**Comment by pangniur** [comment]
感谢大佬这么快的回复。因为后台的要求目录要实时更新，当目录改变的时候也要获取到最新的目录。暂且先用方案二。

**Comment by zTree** [comment]
你这种实现的结果根本不是实时呀，而且，如果是父节点被更新，你也根本不会重新加载；用户不点击的节点也不会被更新。。。总之压根儿不是什么实时更新呀。。。就应该后台直接发送有更改的目录数据，前端找到对应节点去修改。。。当然了，具体还得根据你们实际情况决定。
