### ISSUE TITLE
async 方法中添加   paramFilter   事件

### ISSUE THREAD

**Issue by Awen25** [zTree/zTree_v3#306]
参数过滤事件 ，请求参数的时候能灵活配置.   使用场景 otherParam  中明细参数需要node 属性。

**Comment by Awen25** [comment]
if ($.isFunction(setting.async.paramFilter)) {

			    var filterParam = setting.async.paramFilter(tmpParam, node);

			    if ($.isArray(filterParam)) {
			        tmpParam = filterParam;
			    } 
			}

**Comment by zTree** [comment]
1、可以利用 beforeAsync 回调捕获即将要进行异步加载的事件；
2、或者 利用 setting.async.url 属性设置为 function，每次异步加载前都会调用此方法获取 url；

可利用以上两种 function 的任何一个， 去修改 zTreeObj.setting.async.otherParam即可
