### ISSUE TITLE
isParent: true when children is empty by default?

### ISSUE THREAD

**Issue by marcosnils** [zTree/zTree_v3#308]
Hi, first of all thank you for putting your effort into such great project. 

Sorry if this has been posted before, as several issues are in chinese, this is probably a dupe. I'd like to know what's the reason for not setting a node as `isParent: true` automatically when it has no children. 

For example:

```javascript
var nodes = [
   { name: "Node1", children: [ {name:"Node1-1"} ]},
   { name: "Node2", children: []},
   { name: "Node3"}
];
```
I'd expect `Node2` to be marked as `parent` automatically because the `children` array is empty, which remarks that it's actually a parent node. On the other hand, Node3 would be rendered as a leaf node because we can't really node if it's a parent or not (in that case the isParent property makes sense).

Is there a way to make it work this way?.  The reason why I need this is because my back-end is already returning an empty children array when the parent node doesn't have any children and  it really it seems redundant to modify it to return an isParent property.

**Comment by zTree** [comment]
Please wait me some days, I will check this issue and modified it.

**Comment by marcosnils** [comment]
sure thing!. thanks for being responsive.

**Comment by zTree** [comment]
Hi, please download the last code. If have some error, please tell me.  If it work well, please close this issue.

thanks.

**Comment by marcosnils** [comment]
Just tested it and works as expected. Thx a lot for the quick fix!.
