### ISSUE TITLE
添加子节点弹窗添加

### ISSUE THREAD

**Issue by rosezh** [zTree/zTree_v3#309]
点击添加按钮，在弹窗里面输入要提交的节点信息提交时添加节点，但是由于添加节点信息都写在addHoverDom(treeId, treeNode)里面，这样会导致只要鼠标滑过的节点都会添加新的节点；这个请大神指点

**Comment by zTree** [comment]
为何要把 添加节点的功能放到 addHoverDom 里面呢？。。。难道没有其他合适的位置了？

**Comment by rosezh** [comment]
function addHoverDom(treeId, treeNode) {
			var sObj = $("#" + treeNode.tId + "_span");
			if (treeNode.editNameFlag || $("#addBtn_"+treeNode.tId).length>0) return;
			var addStr = "<span class='button add' id='addBtn_" + treeNode.tId
				+ "' title='add node' onfocus='this.blur();'></span>";
			sObj.after(addStr);
			var btn = $("#addBtn_"+treeNode.tId);
			if (btn) btn.bind("click", function(){
				**var zTree = $.fn.zTree.getZTreeObj("treeDemo");
				zTree.addNodes(treeNode, {id:(100 + newCount), pId:treeNode.id, name:"new node" + (newCount++)});**
				return false;
			});
		};
这段是您的edit_super.html里的addHoverDom部分，目前我还不太清楚应该写到哪里，还请大神指点

**Comment by rosezh** [comment]
function addHoverDom(treeId, treeNode) {
			var sObj = $("#" + treeNode.tId + "_span");
			if (treeNode.editNameFlag || $("#addBtn_"+treeNode.tId).length>0) return;
			var addStr = "<span class='button add' id='addBtn_" + treeNode.tId
				+ "' title='add node' onfocus='this.blur(); '></span>";
				
			sObj.after(addStr);
			var btn = $("#addBtn_"+treeNode.tId);
			$('.submit_zjy').bind('click',function(){
				$('#myModal').removeClass('in');
				$('#myModal').css({"display":"none"});
				submitData();
			});
			if (btn) btn.on("click", function(){
				showModal();
				console.log("当前节点准备添加子节点");
				
			});	
			function showModal(){
				$('#myModal').addClass('in');
				$('#myModal').css({"display":"block"});
				
			}
			**_function submitData(){
				var zTree = $.fn.zTree.getZTreeObj("treeDemo");
				zTree.addNodes(treeNode, {id:(100 + newCount), pId:treeNode.id, name:"new node" + (newCount++)});
				return false;	
			}_**
		};
这部分是我自己改过的内容，本来是想通过获取当前添加节点按钮的父节点去添加子节点，可是获取完后又不可以；将添加的内容放到外面也没什么思路，还请大神指教

**Comment by zTree** [comment]
非常抱歉， 我的工作比较繁忙，没太多时间逐一调试代码，你的代码简单看上去不应该出现滑动过目标位置就自动添加节点的情况呀，都是在 click 事件后才会触发的。请你还是使用浏览器的调试代码去进行单步调试吧
