### ISSUE TITLE
关于是否是父节点属性isParent的说明

### ISSUE THREAD

**Issue by chengwengao** [zTree/zTree_v3#310]
@zTree 目前很多序列化框架例如Spring/jackson/fastjson等在序列化以is开头的boolean类型属性时会引起序列化“错误“（序列化时会将该属性的is去掉，导致获取原属性失败），虽然我们可以通过修改get/set方法“纠正“它，或者使用@JsonProperty注解解决该问题，但是在java开发规范中有一条强制的代码开发规范要求就是布尔值不能以is开头，这点在最近阿里巴巴整理的java开发规约中也有提及，因此从方便后台使用和代码规范的角度，作者是否可以考虑将isParent属性同节点是否展开的open属性的命名规则保持一致，去掉已is开头的命名形式，修改为parent。请参考一下博文：
http://blog.csdn.net/qq_31145141/article/details/71597608
https://segmentfault.com/q/1010000008468359
http://blog.csdn.net/younger_z/article/details/70241201

**Comment by zTree** [comment]
抱歉，这两天太忙，等周末吧，我修改一下代码，允许用户自定义 isParent 属性名称，就放到 setting.data.key.* 这里面，改好后通知你

**Comment by zTree** [comment]
抽空去下载最新版的 zTree，setting.data.key.isParent / isHidden 都可以自定义设置了！用一下，如果有问题请告诉我，谢谢

**Comment by chengwengao** [comment]
按照作者的提示，亲测了一下自定义父节点属性，确实可以了，以下附上验证方式：
1、修改js/jquery.ztree.core.js文件的setting.data.key.isParent属性为自定义的属性（如parent）
![image](https://user-images.githubusercontent.com/25266894/72523625-27615d00-389b-11ea-8792-1c9c0f6bfeab.png)
2、修改js/jquery.ztree.core.js文件的nodeIsParent方法里的属性名称
![image](https://user-images.githubusercontent.com/25266894/72523741-64c5ea80-389b-11ea-88cd-b5a0c83af81e.png)
3、直接以引用了js/jquery.ztree.core.js文件的demo/cn/core/expand.html文件为例，修改该文件，打印如下信息：
![image](https://user-images.githubusercontent.com/25266894/72523885-b53d4800-389b-11ea-9ebf-2e8dbf8047dc.png)
4、在浏览器打开demo/cn/core/expand.html文件，按如下操作，观察打印信息：
![image](https://user-images.githubusercontent.com/25266894/72524004-f2093f00-389b-11ea-8aff-36931c054183.png)
5、复制打印的treeNode属性，可以看到是否父节点属性已经更新为自定义的节点属性：
![image](https://user-images.githubusercontent.com/25266894/72524116-2da40900-389c-11ea-89ff-af1b4ea433e3.png)
