### ISSUE TITLE
关于ztree渲染父子节点关系数据结构探讨

### ISSUE THREAD

**Issue by chengwengao** [zTree/zTree_v3#311]
我是在大概15年的时候开始接触ztree的，当时用的还是老版本，它的用法很简单，后台直接按前端指定的json格式组装好数据，前端就可以帮你渲染出一颗树，具体只需要指定相应的树节点id和pid就行（父节点的id就是子节点的pid），js里面具体怎么渲染的我没有仔细研究过，现在想来也暗自称奇！中途差不多有1年多没有使用ztree了，现在又因为项目原因要用它，所有前端工作都准备好，但是发现后台用原来的那一套组装好json串返回给前台时无法渲染出那种父子节点关系了，后来回看了一下demo提供的树结构，发现和之前的“平级化”节点有了很大不同，所有子节点都包含在children属性中,于是按照这个结构去后台构造数据，但是发现在后台得使用递归才能组装出这种格式的数据（我只想到这种方法，不知道有没有大神能用其他方法实现），想来作者对数据结构应该有一定的研究，请问ztree从之前的“平级化”的pid-id组合型的数据结构改为“递归式”的children型数据结构是基于何种考量？目前在后台组装数据这一方面，新版V3.5相比之前老版V2.6多了一次递归操作。

**Comment by zTree** [comment]
抱歉，居然忘了给你回复。。。。你这个应该不是问题， 请参考Demo：http://www.treejs.cn/v3/demo.php#_102

v3 的版本完全是支持简单实用 id、pId 组合数据的，不用你自己折腾生成复杂的嵌套关系
