### ISSUE TITLE
zTree 多个字段模糊查询节点，可以不

### ISSUE THREAD

**Issue by fairyly** [zTree/zTree_v3#312]
比如 通过节点数据中的 名字，或者名字代码 进行模糊查询，重新渲染dom树，只显示匹配的节点信息，查询字段为空时候，再显示所有哦节点数据

**Comment by zTree** [comment]
1、如果你是采用异步加载的方式，在前端没有全部的数据信息，是绝对不能采用前端搜索的，因为数据都不全，怎么可能搜得正确？？

2、利用 zTree 提供的 getNodesByFilter 方法，可以自行制作搜索规则，筛选节点，但仅仅能处理已经加载到 界面上的这些数据而已！！！！
