### ISSUE TITLE
再问一个问题，ztree暂时只支持使用id去初始化，有没有什么办法能够兼容到class或者是dom

### ISSUE THREAD

**Issue by cjfpersonal** [zTree/zTree_v3#314]

**Comment by zTree** [comment]
那里表明只支持 使用 id 去初始化？？ 

$(".treeDemo") 这么写照样可以进行初始化呀，只要你的 zTree 容器有这个 class

**Comment by cjfpersonal** [comment]
源码中有使用到setting.treeId，而这个变量是绑定了ztree的id，也就是说容器中必须要有id吗？

**Comment by zTree** [comment]
setting.treeId = obj.attr("id");

源码中大量使用 treeId 是用于区分 不同的 zTree 实例；所以 当然要有 id 了，你设置 id 很困难么？
