### ISSUE TITLE
ztree v3，版本报错

### ISSUE THREAD

**Issue by yy981420974** [zTree/zTree_v3#315]
我在页面引用了jq、avalon2.16、jq ui 这样三个js
`<script src="~/js/jquery.js" type="text/javascript"></script>
    <script src="~/js/avalon.2.1.6.js" type="text/javascript"></script>
    <script src="~/js/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
<script src="~/js/jquery.ztree.core.min.js"></script>`
按照官网的例子：$.fn.zTree.init($("#ztree"), setting, zNodes); ，我只是对zNodes填充了JSON数据
使用 FireFox、Chrome都会报：a is undefined ，在 41行
columnNumber: 124
fileName: "http://localhost/LIRS2.Web/js/jquery.ztree.core.min.js"
lineNumber: 41
message: "a is undefined"

**Comment by yy981420974** [comment]
@zTree 希望能够尽快得到作者解答

**Comment by zTree** [comment]
请参考 2013 年的帖子：
[https://github.com/zTree/zTree_v3/issues/30](https://github.com/zTree/zTree_v3/issues/30)

这个问题应该是 jquery UI 某个版本把 jQuery的方法覆盖导致的错误
