### ISSUE TITLE
树节点的悬浮提示信息

### ISSUE THREAD

**Issue by PanStar** [zTree/zTree_v3#316]
我用 `addHoverDom` 和 `removeHoverDom` 实现了*树节点的悬浮提示信息*
但当鼠标移出选中的节点时，没有触发`removeHoverDom` ，导致提示信息并没有被 `remove`，
查看了源码exedit.js
```
onHoverOutNode: function(b) {
      var b = m.getSetting(b.data.treeId)
          , a = m.getRoot(b);
      if (a.curHoverNode && !m.isSelectedNode(b, a.curHoverNode))
           f.removeTreeDom(b, a.curHoverNode),
           a.curHoverNode = null
  },
```
请问为什么要把当前选中的节点排除掉？

我在已有的问题中找到类似的，大概理解了把选中的节点排除掉的原因。
但我想实现移出选中的节点时，触发`removeHoverDom`，需要怎么实现呢？

**Comment by zTree** [comment]
你好，当初这么做主要就是因为会出现 hover 的时候现实的按钮在可视区外面，这样就要移动滚动条，这样就会导致当你想移动滚动条的时候， 按钮又消失了。。。从而变成了永远也无法点击的按钮了。

目前的确没有100% 适合你需求的快速解决方案，不过你可以每次在 addHoverDom 的时候给你的 指定节点 DOM 绑定 Hover 的事件，移出时执行你的remove方法，同时移出事件即可！这样就可以不使用 removeHoverDom 事件了

**Comment by PanStar** [comment]
嗯，很高兴收到你的回复，这样是可行的。
还有一个问题，addHoverDom 没有排除选中的节点，但 removeHoverDom 排除了，总感觉哪里不对劲
如果我想实现 选中节点的不显示提示信息， 需要在 addHoverDom 加上判断，removeHoverDom 却不做处理，两个对应的方法却是不一样的处理方式也

**Comment by zTree** [comment]
我承认，最开始对于这个事件的callback 设计是不健全的，但时间长了又不想影响老用户的使用。。所以也就没有修改。 如果 addHoverDom 再排除掉，那么你依靠什么去添加 dom 呀。

其实最开始就应该提供标准的 hover 事件定义就是了，目前就先这样处理吧。不好意思了

**Comment by PanStar** [comment]
这个插件非常棒呢，我的需求也实现了，非常感谢！
