### ISSUE TITLE
feature request : tree-style-  triangle 

### ISSUE THREAD

**Issue by alpastar** [zTree/zTree_v3#320]
how about adding a modern tree node indicator,  triangle 

example :  https://bootstrapstudio.io/

**Comment by zTree** [comment]
please check the Demo: http://www.treejs.cn/v3/demo.php#_515

**Comment by alpastar** [comment]
in your old-version(i guess 3.5,17)  ,  triangle is implemented. 
but in later version ,  splite of triangle is deprecated. 
why ? 
i implemented triangle with font-awesome , but this one  looks  more smart !! 
.
what about recall triangle  ??
.
http://120.27.46.75:81/webhtml/%E7%A8%BB%E5%A3%B3/D17-01%E5%8F%A4%E7%B1%8D-%E4%B9%A6%E7%9B%AE%E5%BA%93/html/plug-ins/ztree/demo/en/excheck/checkbox_count.html

**Comment by zTree** [comment]
@alpastar 

This is only demo. If you want to see the code,please visit : https://github.com/zTree/zTree_v3/tree/v3.5.17

but I don't remember that I use the  trangle.
