### ISSUE TITLE
Cannot read property 'expandAll' of undefined

### ISSUE THREAD

**Issue by bigzs** [zTree/zTree_v3#322]
onAsyncSuccess 获取后台数据获取不到，而且 zTreeOnAsyncSuccess 的 zTree 为undefined

**Comment by bigzs** [comment]
![tim 20180306110823](https://user-images.githubusercontent.com/25221782/37012348-2da255f0-212f-11e8-8cd9-b541abb51c03.png)

**Comment by zTree** [comment]
请核实你的 zTree 版本，我测试了一下没有问题。

**Comment by bigzs** [comment]
我把数据库清空，重新添加数据就可以了，应该是脏数据有问题这样的，但是应该有个更好的提示，逻辑不对报个错。

**Comment by zTree** [comment]
真心希望你还能保留那个有问题的数据。。因为按照代码逻辑来看，不应该是数据问题造成 onAsyncSuccess 内无法得到 zTree 呀。。。
