### ISSUE TITLE
关于标准的json串现实问题

### ISSUE THREAD

**Issue by yanwenwu** [zTree/zTree_v3#325]
JSON 对象是满足 JSON 数据格式的 JS 对象
    例如： {name:"abc"}
    最正规的 JSON 数据是连属性名称都要被包括起来的
    例如： {"name":"abc"}
key用""之后， 就显示不出来了， 有什么原因吗

**Comment by zTree** [comment]
抱歉，通过你的描述很难断定什么原因，这种情况 按下 F12 键，通过使用 浏览器的调试工具应该能够很容易的找出具体问题。 一般来说有可能是 拼出的数据有格式错误、服务端数据输出问题等等。应该是服务端出现问题的可能性更大一些。
