### ISSUE TITLE
用addHoverDom在重命名和删除后面增加了一个添加按钮，编辑的时候删除按钮消失，添加按钮消失不了

### ISSUE THREAD

**Issue by boi525** [zTree/zTree_v3#327]
用addHoverDom在重命名和删除后面增加了一个添加按钮，编辑的时候删除按钮消失，添加按钮消失不了
想知道默认的效果就是这样的吗
还有怎么在编辑状态的输入框后面增加一个确定按钮呢？

**Comment by zTree** [comment]
请仔细参考 http://www.treejs.cn/v3/demo.php#_305 这个 Demo 中的源码， addHoverDom 一般是与 removeHoverDom 一起使用的

**Comment by zTree** [comment]
抱歉，没看到你最后一个问题。
这个。。你可以尝试利用 beforeEditName 捕获点击编辑按钮的事件，然后在节点后面添加 DOM；
利用 beforeRename 捕获编辑完成的事件，然后去删除 DOM；

如果实现起来不是很流畅，那么可以利用beforeEditName 捕获事件后， 直接 return false；阻止 zTree 默认的 input 出现，同时自己通过操作DOM实现编辑效果，例如弹出 div 专门用于编辑节点属性
