### ISSUE TITLE
getNodes方法得到节点里面没有Element对象，数据和DOM如何关联

### ISSUE THREAD

**Issue by netnr** [zTree/zTree_v3#328]
getNodes获取JSON，里面没有节点数据对应的DOM对象，该如何建立关联

**Comment by netnr** [comment]
EasyUI里面获取节点时，会有一项target属性指向DOM节点

**Comment by zTree** [comment]
zTree 的数据对象中是不关联 DOM 对象的，但是你可以根据 treeNode.tId 找到对应的 DOM 对象，你可以用调试界面看一下 zTree 节点的 DOM 结构和 id ，就能明白其规律了。

但要记住，不是每一个数据都肯定会对应存在一个 DOM 对象的，因为 zTree 使用了优化处理，当父节点未展开时，是不会生成其子节点的 DOM 对象的，即使存在数据也不会生成的。
