### ISSUE TITLE
你好,请问如何能做到单双选组合?

### ISSUE THREAD

**Issue by DrugsZ** [zTree/zTree_v3#329]
是这样,我需要做一个需求,比如一个父级节点,希望可以点击一下单选,再点击一下全选其下方的子节点,点击第三次取消选中,这样当前有api可以实现吗?
我已经解决,是我的错误,总想要直接调用参数,也感谢作者的贡献

**Comment by zTree** [comment]
赞 +1， 这种特殊的需求应该是自己完成了，一个通用的插件不可能把这么特殊的例子也都涵盖进来的。
