### ISSUE TITLE
exedit阻止了mousedown事件，导致其他事件可能也被阻止

### ISSUE THREAD

**Issue by heyusysu** [zTree/zTree_v3#331]
在jquery.ztree.exedit.js中的onMousedownNode方法阻止了mousedown事件，导致其他事件可能也被阻止。
```
//Avoid FireFox's Bug
//If zTree Div CSS set 'overflow', so drag node outside of zTree, and event.target is error.
if(eventMouseDown.preventDefault) {
    eventMouseDown.preventDefault();
}
```
例如我现在focus在一个input元素中，然后点击树节点，焦点并没有从input元素中移除。

**Comment by zTree** [comment]
非常感谢， 这是n 年前为了解决 firefox 的bug 引入的，刚才实验了一下，其实 firefox 已经没有这个问题了。这部分代码已经屏蔽，请你去下载最新版代码
