### ISSUE TITLE
希望能同步更新webjars中的版本

### ISSUE THREAD

**Issue by woncode** [zTree/zTree_v3#332]
目前github上的Releases已经更新到v3.5.33版本，但是webjars中的最新版本只为v3.5.28。
用着webjars的低版本包有些怕会不会存在bug，但是手动下载又麻烦和不好管理。
谢谢！

**Comment by zTree** [comment]
非常抱歉， webjars 中的代码完全不是我进行维护的，我也不知道是谁在进行维护，如果你只想从 webjars 上进行更新，那么请联系其对应的管理人员，谢谢。
