### ISSUE TITLE
id值不能包含下划线的问题

### ISSUE THREAD

**Issue by lukezp** [zTree/zTree_v3#333]
版本：JQuery zTree v3.5.15、jquery-2.0.3
环境：Chrome 58.0.3029.110 (64-bit)
样例树：
- 父节点
  - 节点1（id=XX0001）
     - 节点11（id=XX0001_1）
     - 节点12（id=XX0001_2）
  - 节点2（id=XX0002）
     - 节点21（id=XX0002_1）
     - 节点22（id=XX0002_2）
  - 节点3（id=XX0003）
     - 节点31（id=XX0003_1）
     - 节点32（id=XX0003_2）

问题：
1. 在id中含有下划线时（例如：XX0001_1、XX0001_2），使用`getSelectedNodes()[0]`获取的节点并非点击的节点，如下：

> 点击“节点11”时，获取到的是“节点31”,
> 点击“节点21”时，获取到的是“节点31”；

2. 当把下划线改为中划线时（例如：XX0001-1、XX0001-2），使用`getSelectedNodes()[0]`能获取到点击的节点。

**Comment by zTree** [comment]
首先请确认你的 id 使用的是什么数据类型？ String 还是 Number？

顺便也请你思考一下，如果一个对象的值是 4125_1， 这个对象的值应该使用哪种数据类型来表示呢？

**Comment by lukezp** [comment]
@zTree 
id肯定是String类型。
查看源码后得知，在data对象中存在下面两个方法：
> addNodeCache: function(setting, node) {
> 	data.getCache(setting).nodes[data.getNodeCacheId(node.tId)] = node;
> },
> getNodeCacheId: function(tId) {
> 	return tId.substring(tId.lastIndexOf("_")+1);
> },

在将界面添加到内部缓存对象时，会从节点中获取ID值，例：
> `<span id="posTree_XX0001_2_span">测试</span>`

由于自定义ID中含有下划线，getNodeCacheId获取到的ID为2，不是XX0001_2，导致内部缓存中存放的数据出现错误。
当使用getSelectedNodes()[0]获取的节点时，返回的是 2对应的节点数据，并非实际节点数据。

因此，**在当前版本中，自定义节点ID中不能包含下划线。**

**Comment by zTree** [comment]
@lukezp 你好， 我差点儿就信以为真了。。。

经过测试， 我使用你说的格式设置 id ，发现完全正常。 然后我才意识到你可能出现的错误： 你是不是自己修改 zTree 的 dom 结构了？ 如果是的话，请务必搞清楚，在你指出的方法中，我用的是 tId ，不是 id 哟。 tId 是 zTree 在初始化数据时自行设置 的 唯一标识，主要就是用于避免用户的数据异常。

请再仔细看看 API 中针对 tId 的介绍

**Comment by lukezp** [comment]
@zTree 多谢解答。
不是ztree的问题。
是因为项目中ztree源码被修改过，在_initNode函数中，使用自定义规则修改tId变量的值，导致的此问题。
