### ISSUE TITLE
如何判断子节点是文件夹还是文件

### ISSUE THREAD

**Issue by yubeihai** [zTree/zTree_v3#340]
您好，请问现在应该是节点后没有文件，就判断为叶子节点！
如果我想设置最后底下没有子节点的图标也显示为文件夹图标应该如何设置呢？

**Comment by zTree** [comment]
方法一：设置 节点数据 treeNode.isParent = true

方法二： 修改 css 样式即可 （https://my.oschina.net/dyhunter/blog/97535）
