### ISSUE TITLE
url返回数据为xml类型 地指树上会被添加undefined bug 

### ISSUE THREAD

**Issue by progblog** [zTree/zTree_v3#341]
测试地址 
www.w3school.com.cn/example/xmle/note.xml

ajax 返回数据为xml的时候
tools.clone(newNodes) 会把 xml字符串转换为乱码的数组

问题代买在这里
https://github.com/zTree/zTree_v3/blob/master/js/jquery.ztree.core.js#L1097
修改成 if (newNodes && newNodes !== "" && typeof newNodes != "string")

**Comment by zTree** [comment]
你好， zTree 没有说过支持 xml 数据格式呀！

**Comment by progblog** [comment]
不是要ztree兼容，这样稍微的改动，开发者就可以在onsuccess事件后自己把xml数据转换成json了

**Comment by zTree** [comment]
很有道理！！这两天抽空修改一下，然后给你消息

**Comment by zTree** [comment]
我使用 async.html 这个 demo ， 设置 setting.async.type= 'get'； 并且 使用 nginx 的 proxy 映射了一个地址到你的 http://www.w3school.com.cn/example/xmle/note.xml 这个数据接口， 测试了一下， 完全不需要修改任何代码，就可以在 dataFilter 内捕获 得到的 xml 字符串呀。 @progblog

**Comment by progblog** [comment]
我使用的是这个
http://127.0.0.1/demo/cn/bigdata/diy_async.html
修改
async: {
  enable: true,
  url: getUrl,
  type: "get"
}

var zNodes =[
			{name:"2000个节点", id:"3",  isParent:true, open: true}
		];
getUrl 修改成
return http://www.w3school.com.cn/example/xmle/note.xml?"

问题出在 
https://github.com/zTree/zTree_v3/blob/master/js/jquery.ztree.core.js#L1099
view.addNodes(setting, node, -1, !!newNodes ? tools.clone(newNodes) : [], !!isSilent);
为xml时候newNodes 是字符串 !!newNodes 为真进入 tools.clone(newNodes)

tools.clone(newNodes)生成
"[{"0":"<","1":"?","2":"x","3":"m","4":"l","5":" ","6":"v","7":"e","8":"r","9":"s","10":"i","11":"o","12":"n","13":"=","14":"\"","15":"1","16":".","17":"0","18":"\"","19":" ","20":"e","21":"n","22":"c","23":"o","24":"d","25":"i","26":"n","27":"g","28":"=","29":"\"","30":"I","31":"S","32":"O","33":"-","34":"8","35":"8","36":"5","37":"9","38":"-","39":"1","40":"\"","41":"?","42":">","43":"\r","44":"\n","45":"<","46":"!","47":"-","48":"-","49":" ","50":" ","51":"C","52":"o","53":"p","54":"y","55":"r","56":"i","57":"g","58":"h","59":"t","60":" ","61":"w","62":"3","63":"s","64":"c","65":"h","66":"o","67":"o","68":"l","69":".","70":"c","71":"o","72":"m","73":".","74":"c","75":"n","76":" ","77":"-","78":"-","79":">","80":"\r","81":"\n","82":"<","83":"n","84":"o","85":"t","86":"e","87":">","88":"\r","89":"\n","90":"\t","91":"<","92":"t","93":"o","94":">","95":"G","96":"e","97":"o","98":"r","99":"g","100":"e","101":"<","102":"/","103":"t","104":"o","105":">","106":"\r","107":"\n","108":"\t","109":"<","110":"f","111":"r","112":"o","113":"m","114":">","115":"J","116":"o","117":"h","118":"n","119":"<","120":"/","121":"f","122":"r","123":"o","124":"m","125":">","126":"\r","127":"\n","128":"\t","129":"<","130":"h","131":"e","132":"a","133":"d","134":"i","135":"n","136":"g","137":">","138":"R","139":"e","140":"m","141":"i","142":"n","143":"d","144":"e","145":"r","146":"<","147":"/","148":"h","149":"e","150":"a","151":"d","152":"i","153":"n","154":"g","155":">","156":"\r","157":"\n","158":"\t","159":"<","160":"b","161":"o","162":"d","163":"y","164":">","165":"D","166":"o","167":"n","168":"'","169":"t","170":" ","171":"f","172":"o","173":"r","174":"g","175":"e","176":"t","177":" ","178":"t","179":"h","180":"e","181":" ","182":"m","183":"e","184":"e","185":"t","186":"i","187":"n","188":"g","189":"!","190":"<","191":"/","192":"b","193":"o","194":"d","195":"y","196":">","197":"\r","198":"\n","199":"<","200":"/","201":"n","202":"o","203":"t","204":"e","205":">","206":" ","207":"\r","208":"\n","level":1,"tId":"treeDemo_2","parentTId":"treeDemo_1","open":false,"zAsync":true,"isFirstNode":true,"isLastNode":true,"isAjaxing":false,"pId":"3","isHover":false,"editNameFlag":false}]"

导致错误

**Comment by progblog** [comment]
使用chrome 开启--disable-web-security 模式

**Comment by zTree** [comment]
那我明白你错在什么地方了！
1、onSuccess 是 异步加载完毕并且 节点数据已经成功加入到 zTree 以后才触发的！
2、你这种情况就是应该使用 setting.async.dataFilter 这个 方法对获取到的数据进行加工 并且 return Json 数据 ，这样才能正确加入到 zTree 内部的。（请你仔细看看 Line 1098 的代码，就在你出错代码的上一行）
