### ISSUE TITLE
RTL support?

### ISSUE THREAD

**Issue by SAFatemi** [zTree/zTree_v3#345]
Hello and thanks for your great library.
I want to use zTree inside a RTL web application, can you help me to use or implement zTree in RTL mode?

**Comment by SAFatemi** [comment]
I found this solution:
[https://github.com/zTree/zTree_v3/issues/189](url)

**Comment by SAFatemi** [comment]
Problem of zTree RTL direction was resolved, but right click menu not show normally!

**Comment by zTree** [comment]
please give me your code for the right click menu.  @SAFatemi

**Comment by SAFatemi** [comment]
I don't have any code for right click in RTL mode, but if I implement it, post it.
