### ISSUE TITLE
how to programmatically click some node , and  trigger click event ...

### ISSUE THREAD

**Issue by alpastar** [zTree/zTree_v3#347]
function on_click(e,treeid,treeNode){
  blah blah blah 
}

setting. callback {
...
onClick : on_click   ;
...
}

var o_node = $ztree.getNodeByParam('level',1, null)   ;  // select  first-node of level-1 
$ztree.selectNode(o_node);                               // but callback is not occuring 

is there  any good ways??

**Comment by zTree** [comment]
please use jQuery.trigger

```
var z = $.fn.zTree.getZTreeObj('treeDemo');
var n = z.getNodes()[1].children[0];
z.selectNode(n);
$('#' + n.tId + '_a').trigger('click');
```
