### ISSUE TITLE
帮助文档错误zTreeObj.getCheckedNodes

### ISSUE THREAD

**Issue by linv2** [zTree/zTree_v3#351]
getCheckedNodes
概述[ 依赖 jquery.ztree.excheck 扩展 js ]
获取输入框被勾选 或 未勾选的节点集合。[setting.check.enable = true 时有效]
请通过 zTree 对象执行此方法。
Function 参数说明
checkedBoolean
checked = true 表示获取 被勾选 的节点集合
checked = false 表示获取 未勾选 的节点集合
省略此参数，等同于 true。
对于 treeNode.nochecked = true 的节点不进行获取。
返回值Array(JSON)
返回全部符合要求的节点集合 Array
function 举例
1. 获取当前被勾选的节点集合
var treeObj = $.fn.zTree.getZTreeObj("tree");
var nodes = treeObj.getCheckedNodes(true);

对于 treeNode.nochecked = true 的节点不进行获取。
treeNode没有nochecked属性
经测试正确属性为nocheck

**Comment by zTree** [comment]
非常感谢！！
