### ISSUE TITLE
How to selected nodes I clicked,not "check" configuration and not "ctrl".

### ISSUE THREAD

**Issue by XiuyeXYE** [zTree/zTree_v3#352]
Click nodes and select node directly one by one,not using 'ctrl'  or 'check' configuration.The function 'selectNode' selects only one of nodes and cancel another selected if not pressing 'ctrl',so I want to select many nodes not using 'ctrl'.How do I do?

**Comment by zTree** [comment]
please use the beforeClick & selectNode() / cancelSelectedNode() method.

In the  beforeClick:

you can 'return false', and use setTimeout() to trigger the  selectNode() / cancelSelectedNode() method.
