### ISSUE TITLE
删除节点时zTreeOnRemove和zTreeBeforeRemove执行问题

### ISSUE THREAD

**Issue by tttmango** [zTree/zTree_v3#354]
zTreeBeforeRemove: function(treeId, treeNode) {
      if (treeNode.isParent) {
        this.$message('请先删除子节点！');
        return false;
      }
      const zTree = $.fn.zTree.getZTreeObj('treeDemo');
      zTree.selectNode(treeNode);
      alert(treeNode.name);
      try {
        this.$confirm('确认删除节点 -- ' + treeNode.name + ' 吗?', '提示', {
          confirmButtonText: '确定',
          cancelButtonText: '取消',
          type: 'warning'
        });
      } catch (e) {
        return false;
      }
    },
zTreeOnRemove: function(event, treeId, treeNode) {
      alert(treeNode.tId);
      alert('onRemove执行了');
}

zTreeOnRemove里的alert在zTreeBeforeRemove里的确认弹框出来之前就执行了,是不是$confirm回调的缘故？前端用的是element UI,不是很熟悉，请大神帮忙解惑

**Comment by zTree** [comment]
你这很明显是一个异步问题导致的。 如果你触发了 confirm，请务必 return false，从而阻止 zTree 的默认删除操作； 然后在你的 confirm 回调中根据需要去执行 removeNode 方法即可



zTreeAPI     http://www.treejs.cn
 
 
发件人： tttmango
发送时间： 2018-07-24 11:10
收件人： zTree/zTree_v3
抄送： Subscribed
主题： [zTree/zTree_v3] 删除节点时zTreeOnRemove和zTreeBeforeRemove执行问题 (#354)
zTreeBeforeRemove: function(treeId, treeNode) {
if (treeNode.isParent) {
this.$message('请先删除子节点！');
return false;
}
const zTree = $.fn.zTree.getZTreeObj('treeDemo');
zTree.selectNode(treeNode);
alert(treeNode.name);
try {
this.$confirm('确认删除节点 -- ' + treeNode.name + ' 吗?', '提示', {
confirmButtonText: '确定',
cancelButtonText: '取消',
type: 'warning'
});
} catch (e) {
return false;
}
},
zTreeOnRemove: function(event, treeId, treeNode) {
alert(treeNode.tId);
alert('onRemove执行了');
}
zTreeOnRemove里的alert在zTreeBeforeRemove里的确认弹框出来之前就执行了,是不是$confirm回调的缘故？前端用的是vue,不是很熟悉，请大神帮忙解惑

**Comment by zTree** [comment]
你这很明显是一个异步问题导致的。 如果你触发了 confirm，请务必 return false，从而阻止 zTree 的默认删除操作； 然后在你的 confirm 回调中根据需要去执行 removeNode 方法即可
