### ISSUE TITLE
节点修改问题

### ISSUE THREAD

**Issue by tttmango** [zTree/zTree_v3#355]
我又来了。。代码如下：
```
    beforeEditName: function(treeId, treeNode) {
      const zTree = $.fn.zTree.getZTreeObj('treeDemo');
      zTree.selectNode(treeNode);
      zTree.editName(treeNode);

      return false;
    },

    beforeRename: function(treeId, treeNode, newName, isCancel) {
      if (newName.length === 0) {
        var zTree = $.fn.zTree.getZTreeObj('treeDemo');
        zTree.cancelEditName();
        this.$message('节点名称不能为空！');

        return false;
      } else if (newName === treeNode.name) {
        return false;
      } else {
        return true;
      }
    },

    onRename: function(event, treeId, treeNode, isCancel) {
      // 调用修改接口
      alert('onRename执行了');
    }
```

这次是节点编辑问题。
1、节点进入编辑状态后，如果输入的名称为空弹出提示，返回false,但是我的onRename弹框先执行了，这次应该不是异步的问题，message只是一个提示啊
2、如果输入的名称和之前一样的话我希望是不要去调用onRename，因为onRename方法里会调用后台接口改数据库，我试了返回false只会使输入框处于编辑状态，调用cancelEditName方法取消编辑状态也不行。
实在是麻烦大神了~~

**Comment by tttmango** [comment]
按照您的提点，我把代码改成如下：
beforeRename: function(treeId, treeNode, newName, isCancel) {
      var zTree = $.fn.zTree.getZTreeObj('treeDemo');
      if (newName.length === 0) {
        setTimeout(function() {
          zTree.cancelEditName();
        }, 0);
        this.$message('节点名称不能为空！');
        return false;
      } else if (newName === treeNode.name) {
        alert(newName);
        setTimeout(function() {
          zTree.cancelEditName();
        }, 0);
        return false;
      } else {
        return true;
      }
    },

    onRename: function(event, treeId, treeNode, isCancel) {
      alert(isCancel);
      if (isCancel === false) {
        // 调用修改接口
        alert('onRename执行了');
      }
    },

结果不管是newName为空或者和原来一样，都弹出原来的节点名称，这是怎么个情况？

**Comment by zTree** [comment]
你根据你的需要调整代码就是了， 我也不知道你的全部需求，只是根据你之前的代码说的解决方案。
