### ISSUE TITLE
Prevent Click Action on Double Click

### ISSUE THREAD

**Issue by cyberzilla** [zTree/zTree_v3#357]
I have two action, first execute **onClick** in callback, second executed onDblClick in callback too, when i double click the node, the action onClick executed too, how to prevent onClick Action when double Click? Thanks

**Comment by zTree** [comment]
please use setTimeout in onClick

example:
```
var timer = null;
function onClick() {
   clearTimeout(timer);
   timer = setTimeout(function() {
       // there is your code

   }, 500);
}

function onDblClick() {
}
```
