### ISSUE TITLE
IE搜索一直自动聚焦搜索框

### ISSUE THREAD

**Issue by JerryWang24** [zTree/zTree_v3#360]
IE搜索一直自动聚焦搜索框。在输入框输入空格然后把空格删了，你点其他地方，他会一直自动聚焦到输入框里面，，，，，，，，，，

**Comment by zTree** [comment]
你指的是哪个Demo？ 还是官网 API 里面的 搜索？

**Comment by JerryWang24** [comment]
只要有placeholder   ie都会这样！！

**Comment by zTree** [comment]
placeholder 和 焦点有什么关系？ 不可能是因为 placeholder 吧？ 请检查你的 beforeRename 回调，尝试屏蔽掉这个回调的功能。

**Comment by JerryWang24** [comment]
我没有用beforeRename，现在给他返回一个false还是一样的问题，ie11也有这样的问题，blur的时候tree都会刷新一次，有时候还会导致布局往上移动了10多个像素，但是debug是看不到有样式改变的！你可以在ie试试调用搜索，输入框有placeholder的情况！

**Comment by zTree** [comment]
请你找一个zTree 中的 Demo 修改一下，保证重现此问题，然后贴出来代码吧，否则这个问题无法继续沟通下去了。

**Comment by JerryWang24** [comment]
[ File Path: fuzzySearch/fuzzySearch.html ]这个页面，搜索输入框给了placeholder

`<!DOCTYPE html>
<HTML>
<HEAD>
	<TITLE> ZTREE DEMO - fuzzySearch</TITLE>
	<meta http-equiv="content-type" content="text/html; charset=UTF-8">
	<link rel="stylesheet" href="../../../css/demo.css" type="text/css">
	<link rel="stylesheet" href="../../../css/zTreeStyle/zTreeStyle.css" type="text/css">
	<script type="text/javascript" src="../../../js/jquery-1.4.4.min.js"></script>
	<script type="text/javascript" src="../../../js/jquery.ztree.core.js"></script>
	<script type="text/javascript" src="../../../js/jquery.ztree.exhide.js"></script>
	<script type="text/javascript" src="../../js/fuzzysearch.js"></script>
	
	<SCRIPT type="text/javascript">
		$.ajax({
			url : 'https://www.easy-mock.com/mock/5a4afaa6acbe6802cb6ea41a/tree',
			type : 'GET',
			sync: false,
			success: function(res){
				var setting = {
						check: {
							enable: true//checkbox
						},
						view: {
							nameIsHTML: true, //allow html in node name for highlight use				
							selectedMulti: false
						},
						edit: {
							enable: false,
							editNameSelectAll: false
						},
						data: {
							simpleData: {
								enable: true
							}
						}
				};
				var zNodes =res.data.list

				$(document).ready(function(){
					$.fn.zTree.init($("#treeDemo"), setting, zNodes);
					fuzzySearch('treeDemo','#key',null,true); //initialize fuzzysearch function
				});
			}
		});
			
		//-->
	</SCRIPT>
</HEAD>

<BODY>
<h1>Fuzzy Search</h1>
<h6>[ File Path: fuzzySearch/fuzzySearch.html ]</h6>
<div class="content_wrap">
	<div class="zTreeDemoBackground left">
		<ul id="treeDemo" class="ztree"></ul>
	</div>
	<div class="right">
		<ul class="info">
			<li class="title">
				<h2>1. Explaination of fuzzySearch()</h2>
				<ul class="list">
				<li class="highlight_red">
 					@param the ztree id used to get the ztree object
				</li>
				<li class="highlight_red">
					@param searchField selector of your input for fuzzy search
				</li>
				<li class="highlight_red">
					@param isHighLight whether highlight the match words, default true
				</li>
				<li class="highlight_red">
					@param isExpand whether to expand the node, default false
				</li>
				<li class="highlight_red">
					fuzzySearch ( zTreeId, searchField, isHighLight, isExpand )
				</li>
				<li><p>Try to search：<br/>
						Keywords：<input type="text" id="key" placeholder="请输入考评表名称" value="" class="empty" /><br/>
					</p>
				</li>
				</ul>
			</li>
			<li class="title"><h2>2. js dependencies</h2>
				<ul class="list">
					<li>ztree v3.5.19.1 +, getPath() in use</li>
					<li>ztree.exhide extension, hideNode() in use</li>
				</ul>
			</li>
		</ul>
	</div>
</div>
</BODY>
</HTML>`

**Comment by zTree** [comment]
原来是这个Demo 呀，那得等有空的时候检查一下了

**Comment by zTree** [comment]
已经修正！请检查！！ 非常感谢！！
