### ISSUE TITLE
虚线的连接线可不可以更改成实线

### ISSUE THREAD

**Issue by YuFy1314** [zTree/zTree_v3#362]
就是将第一个图改成第二个图
![图一](https://user-images.githubusercontent.com/24446694/45066693-22f73280-b0f2-11e8-90a6-853694f738a1.png)

![图二](https://user-images.githubusercontent.com/24446694/45066677-0f4bcc00-b0f2-11e8-920e-e0e09047c411.png)

**Comment by YuFy1314** [comment]
@zTree   这个问题的意思就是想把左侧的虚线换成实线，右侧以及子树的线全都去掉，可以实现不？

**Comment by lb091188** [comment]
修改主题中的雪碧图即可，

**Comment by zTree** [comment]
修改雪碧图 可以让虚线换成实线，但是如果指向 root 显示 线条，子树的线全去的话，可以修改 css 样式实现

https://my.oschina.net/dyhunter/blog/97535  zTree 的 css 详解 可以参考
