### ISSUE TITLE
点击子节点改变颜色

### ISSUE THREAD

**Issue by YuFy1314** [zTree/zTree_v3#367]
通过API提供的onClick事件可以获取到节点的id, 就可以实现对其样式的改变, 但是点击改变之后, 之前点击的样式还在, 这个情况怎么处理呢?
预期效果: 点击哪个节点, 哪个节点就变色, 其他的节点恢复默认,如下:
![](https://user-images.githubusercontent.com/24446694/46642775-676f6580-cbab-11e8-8f3f-fe5b6029a527.png)
实际效果: 点击的节点变色, 之前点击的节点的样式没有被清除,如下:
![](https://user-images.githubusercontent.com/24446694/46642815-95ed4080-cbab-11e8-9c25-c06fa8388f5f.png)
有没有好的实现方法麻烦大神们提供一下, 谢谢 @zTree

**Comment by wowolyzh** [comment]
如果是普通的节点，对curSelectedNode的className设置颜色样式就好了，这个就是选中的class。
如果是checkbox，就通过onCheck来实现，检测当前node的checked为true或false进行控制颜色

**Comment by zTree** [comment]
可以每次把当前高亮的节点数据保存下来呀，设置新的高亮节点时，就把之前高亮的节点恢复正常即可
