### ISSUE TITLE
ztree点击checbox勾选节点，如何获取勾选节点的DOM？

### ISSUE THREAD

**Issue by DancingC** [zTree/zTree_v3#372]
ztree点击checbox勾选节点，如何获取勾选节点的DOM？

**Comment by zTree** [comment]
利用 callback 回调捕获勾选操作，利用 节点的 treeId 根据 DOM 的 ID 命名规则可以拼出来 相应的 id （用调试工具看看这些 Dom 的id 就明白了，很简单）
