### ISSUE TITLE
半选- 选中的问题。

### ISSUE THREAD

**Issue by ynicing** [zTree/zTree_v3#373]
JQuery zTree core v3.5.33
jquery.ztree.all.js
line:2424
var chkName = setting.check.chkStyle + "_" + (nodeChecked ? c.TRUE : c.FALSE) + "_" + fullStyle;
/*以下判断是否半选中*/
if(fullStyle == c.PART){
  chkName = setting.check.chkStyle + "_" + (node.check_Child_State == 1 ? c.TRUE : c.FALSE) + "_" + fullStyle;
}
如果是半选，判断错误。

**Comment by ynicing** [comment]
![aaaa](https://user-images.githubusercontent.com/17871283/47974753-fc4f7b00-e0e5-11e8-80b6-10df7636a80c.png)
![bbbb](https://user-images.githubusercontent.com/17871283/47974756-007b9880-e0e6-11e8-8fb9-67304b5ae122.png)
系统用户 与 系统管理 半选问题。第一张是bug，第二张是修复后的。

**Comment by zTree** [comment]
明白了，这是理解不同，再加上你们自定义了图标导致的。

首先还是要理解一下 API 中 treeNode.getCheckStatus 里面的表格具体说明。

在视图上 zTree 默认为 ：
1、子节点 有选中情况，父节点至少是一个 选中状态的（当然可能是半选状态）；
2、父节点一旦选中时，就会将子节点全部选中。
3、全选状态时，一旦有某一个子节点取消选中，父节点也会成为半选状态，如果所有子节点都取消选中，那么父节点就自动变为取消选中的状态
（这都是默认状态下会出现的情况）；

而如果要出现 父节点完全不被选中的半选状态，只有初始化时设置父节点的数据是 checked = false；而有子节点的 checked = true 时才会出现

具体可以参考官网的Demo 进行比较：http://www.treejs.cn/v3/demo.php#_201

对于你的情况，我感觉你可能是 半勾选时就只有一种状态，并不会出现两种半勾选的情况，如果是这样的话，你只需要修改一下 css 即可（例如： checkbox_false_part 和 checkbox_true_part）

顺便说一下，有空还是可以升级到最新版本的 zTree

**Comment by zTree** [comment]
补充一下，你看到的代码貌似也不太正确，因为那个 else if 后面应该还会有一个 else 的，而且最新代码这一块还是有些差异的。 所以还是先升级到最新版本再看看我上面说的几点问题

**Comment by ynicing** [comment]
根本问题，我同事修改了图标产生的bug。 直至今天才跟我说更改过了图标。好崩溃。

**Comment by zTree** [comment]
好吧， 让你那同事请客吧！
