### ISSUE TITLE
win10设置自定义图标样式出现问题

### ISSUE THREAD

**Issue by rpsffx** [zTree/zTree_v3#374]
给树节点设置iconSkin自定义类名，结果每个节点出现两个图标，为何？win7上无此问题。

**Comment by rpsffx** [comment]
![image](https://user-images.githubusercontent.com/28640170/48711276-ccf05080-ec45-11e8-8db4-fb02e75bb667.png)

**Comment by zTree** [comment]
http://www.treejs.cn/v3/demo.php#_106
对照官网Demo，是不会出现此问题的。

所以请务必使用 开发者工具进行调试，检查 Dom 差异，检查代码逻辑，是否自行添加了什么元素。
