### ISSUE TITLE
关于指定data中的key 问题

### ISSUE THREAD

**Issue by caibinghong** [zTree/zTree_v3#375]
key:{
chidren:"",
name:"",
title:"",
url:""
}
其实有很多情况下，
返回数据包格式并非是这样的标准，有可能是多级分类的属性
比如
`{
    "name":"page",
    "ver":"1.0.0",
    "attrs":{
      "id":"page1",
      "title":"页面标题1",
        "children":[
      {
        "name":"button",
        "ver":"1.0.0",
        "attrs":{
          "id":"button1",
          "title":"按钮标题1"
        }
      }
    ]
    }
  }`
那这样的数据就没有办法指定
data.key的值了
因为chidren:"attrs.chidren",那这样就处理不了

**Comment by zTree** [comment]
zTree 不支持这种规则的数据格式，请自行处理一下数据结构，其实只需要把 attrs 属性的 value 拿出来当作节点数据就可以了。

可以在 dataFilter 内进行操作
