### ISSUE TITLE
zTree v3.5.37 fuzzysearch 模糊搜索功能开启 checkbox 复选功能失效

### ISSUE THREAD

**Issue by aqair** [zTree/zTree_v3#376]
作者您好，fuzzysearch 模糊搜索功能开启之后，checkbox 复选框就看不到。
使用的Ztree版本是：zTree v3.5.37

**Comment by zTree** [comment]
fuzzysearch 的 Demo 中只引入了 core 这个js ，没有引入 excheck.js，所以没有 checkbox 功能，一旦引入后，就可以正常使用了
