### ISSUE TITLE
带有单选框的树，页面切换，反复的创建、移除Dom 后，树上单个节点前出现多个radio 单选框

### ISSUE THREAD

**Issue by Terry-cjgu** [zTree/zTree_v3#378]
通过配置构建一个带有单选框的树，加载模板，第一次创建树没问题，当切换其他页面再切换回树页面再次构建树的时候，单选框就会多一个，切换几次，就多几个单选框，谁知道这是什么原因导致的呀

**Comment by zTree** [comment]
请检查你的 js 引用，是否出现了重复加载

**Comment by Terry-cjgu** [comment]
@zTree 恩，确实是重复加载了 excheck js 我昨天吧ztree.core js 拿出去了 ，没注意这个，问题解决了 多谢
