### ISSUE TITLE
可以发布下版本吗？

### ISSUE THREAD

**Issue by leshalv** [zTree/zTree_v3#379]
当前最新版本为 3.5.37，但是releases里依旧是3.5.33，我想构建webjars，无法构建最新版，可以发布一下3.5.37releases吗？

**Comment by zTree** [comment]
非常抱歉，这是我的疏忽，现在已经添加上了！！

**Comment by zTree** [comment]
我觉得我真的很懒，这么方便，居然一直没有去维护 npm 的代码库；刚才已经上传到 npm 了，以后这个地址就是我自己来维护啦！！

https://www.npmjs.com/package/@ztree/ztree_v3

**Comment by leshalv** [comment]
哈哈

**Comment by jasonHzq** [comment]
> 我觉得我真的很懒，这么方便，居然一直没有去维护 npm 的代码库；刚才已经上传到 npm 了，以后这个地址就是我自己来维护啦！！
> 
> [npmjs.com/package/@ztree/ztree_v3](https://www.npmjs.com/package/@ztree/ztree_v3)

嗯，你直接发了3.5.37 吗？低版本可以也写个脚本都发一下。不过npm只能发更高的版本。。。

**Comment by jasonHzq** [comment]
> 为何还要发布低版本？ 这个我真的不想发了 @jasonHzq

你好，我们项目有人用了 ztree，很不错的组件。但是用的是低版本（3.5.26）。由于之前的研发直接copy了源码，既不符合规范，也难以进行构建优化。现在我想用 npm 包，但是你直接发布了高版本。虽然我可以 copy 你的代码发布我想要的版本，但是我也不想像另一位同学那样，让其它 ztree 用户感到混乱。

**Comment by zTree** [comment]
git+https://github.com/zTree/zTree_v3/tree/v3.5.27 

那你应该可以使用 git 地址 进行处理。

另外，我看了一下发布日志，并没有进行什么不兼容之前版本的改动，你应该可是直接升级到最新版的 zTree 代码，建议你大胆的尝试一下

**Comment by jasonHzq** [comment]
> git+[zTree/zTree_v3.git#v3.5.27](https://github.com/zTree/zTree_v3.git#v3.5.27)
> 
> 那你应该可以使用 git 地址 进行处理。
> 
> 另外，我看了一下发布日志，并没有进行什么不兼容之前版本的改动，你应该可是直接升级到最新版的 zTree 代码，建议你大胆的尝试一下

哈哈，一个大项目，不敢造次。我用git地址吧。
