### ISSUE TITLE
子节点属性存在且empty,依旧被当成父节点

### ISSUE THREAD

**Issue by yandixuan** [zTree/zTree_v3#380]
like: {children:[]} 节点儿子属性存在且empty,依旧被当成父节点渲染

**Comment by zTree** [comment]
这不算空，如果没有子节点 就不应该设置 children 属性

**Comment by yandixuan** [comment]
好吧...构造的树对象一起序列化就是会带空数组的 我已经通过构造isParent属性解决了。

**Comment by yandixuan** [comment]
> 这不算空，如果没有子节点 就不应该设置 children 属性
构造的对象序列化出来的，我已经通过构造isParent属性解决了。
