### ISSUE TITLE
excheck和exhide组件在_initNode时不能正常给结点的checked和hidden属性赋值

### ISSUE THREAD

**Issue by xinhochen** [zTree/zTree_v3#384]
例如：
`  data.nodeChecked = function (setting, node, newChecked) {
    if (!node) {
      return false;
    }
    var key = setting.data.key.checked;
    if (typeof newChecked !== 'undefined') {
      if (typeof newChecked === "string") {
        newChecked = tools.eqs(newChecked, "true");
      }
      newChecked = !!newChecked;
      node[key] = newChecked;
    }
    return node[key];
  };`
当_initNode中第一次调用该方法时，var checked = data.nodeChecked(setting, n);
checked值为undefined，导致无法正常获取节点的checked属性，建议修改为return !!node[key];

exhide插件也相同的修改

**Comment by zTree** [comment]
非常同意！！必须要支持你的建议！！！感谢！

**Comment by zTree** [comment]
已经提交，请更新代码
