### ISSUE TITLE
异步加载时，点击展开，没有发送ajax请求

### ISSUE THREAD

**Issue by yh794406573** [zTree/zTree_v3#385]
代码：
var setting = {
        async: {
            enable: true,
            url: uu,
            autoParam: ["type=level", "type", "level=plevel"],
            otherParam: {"id": args.path},
            type: "get",
            dataFilter: function (treeId, parentNode, responseData) {
                if (responseData.code == CONFIG.SUCCESS_CODE) {
                    return responseData.result;
                }
                return null;
            }
        },
        check: {
            enable: true,
            chkboxType: {"Y": "ps", "N": "ps"}
        },
        data: {
            simpleData: {
                enable: true//使用简单模式
            }
        },
        view: {
            selectedMulti: false,//允许选多个
            showLine: false
        },
        callback: {
            onClick: zTreeOnClick,
            onCheck: zTreeOnCheck
        }
    };
    zTreeObj = $.fn.zTree.init($("#" + widgetStr), setting);

**Comment by zTree** [comment]
请务必检查你的节点数据，如果父节点已经存在 children 属性，即使是 [] 空数组的情况下，也不会去加载的。 这种情况被判断为已经有数据，且子节点为空

**Comment by yh794406573** [comment]
> 请务必检查你的节点数据，如果父节点已经存在 children 属性，即使是 [] 空数组的情况下，也不会去加载的。 这种情况被判断为已经有数据，且子节点为空

抱歉，没注意到这个，是有children属性的，解决了这个问题，非常感谢！
