### ISSUE TITLE
setting.view.selectedMulti  设置是否允许同时选中多个节点。

### ISSUE THREAD

**Issue by santosshen** [zTree/zTree_v3#392]
1、设置为 true时，按下 Ctrl 或 Cmd 键可以选中多个节点 
这个功能，可以支持  按住 shift  一次选取多个节点吗

**Comment by zTree** [comment]
这个 shift 的快捷键功能并没有添加，请捕获键盘事件，自行开发。 可以利用 selectNode 方法

因为 shift 这个会牵扯到是否需要选中 子节点的问题。。还有异步加载时的情况，具体情况比较复杂，所以并没有添加到核心功能内
