### ISSUE TITLE
异步请求时请求头添加无效

### ISSUE THREAD

**Issue by Kira-li** [zTree/zTree_v3#393]

**Comment by Kira-li** [comment]
异步请求时，请求头添加无效

 async: {
                        url: process.env.BASE_API + "/api/v1/devices/getTreeAll",
                        autoParam: ["parentId"],
                        type: "get",
                        // dataFilter: this.ajaxDataFilter,
                        headers: { "Authorization": getToken(), "Cache-Control": "no-cache", "Content-Type": "application/json;charset=UTF-8" },
                        // otherParam: { "parentId": "3333" },
                        enable: true
                    },

**Comment by zTree** [comment]
请自行调试看看，应该没有问题呀，或者请检查你的 zTree 版本

代码中有这个处理的：
headers: setting.async.headers,
