### ISSUE TITLE
fontCss添加font-size设置，没办法改变节点字体大小！

### ISSUE THREAD

**Issue by seanin** [zTree/zTree_v3#395]
fontCss没办法改变节点字体font-size和font-family！！！以下两种方法，试了都无效。

![image](https://user-images.githubusercontent.com/5111701/53479287-aa2acf00-3ab3-11e9-8bd6-7502b61a2204.png)

![image](https://user-images.githubusercontent.com/5111701/53479298-aeef8300-3ab3-11e9-9845-b4c430a9484a.png)

**Comment by zTree** [comment]
抱歉，由于 zTree 的 古老的 DOM 结构，这两个样式修改会导致 树的连接线显示异常。 另外 fontCss 影响的是 < a > 标签 而 节点名称 <span> 标签也有自己的 font 设置，从而导致你设置无效。

修改这两个属性建议配合 css 进行

**Comment by seanin** [comment]
好吧，
