### ISSUE TITLE
updateNode方法无法更新复杂结构的子节点

### ISSUE THREAD

**Issue by garygao12580** [zTree/zTree_v3#396]
用的时候发现updateNode方法只会update第一层节点，而无法更新包含children结构的子节点。
另外：建议文档说明一下updateNode方法不允许修改id。

**Comment by zTree** [comment]
updateNode 方法仅仅是用来更新视图作用的，因为早先的jQuery 架构 再加上 兼容浏览器的限制，并没有像现在的 js get set 方法能直接针对 JSON 对象进行属性变化的跟踪，自动更新视图。

所以此方法也仅仅针对你制定的 treeNode ，并不会更新其子节点的视图。所以请针对改变的 treeNode 逐一使用 updateNode 方法
