### ISSUE TITLE
请问3.5.24到3.5.40，npm包从`npm i ztree`改成了`npm i @ztree/ztree_v3`，请问这中间有破坏性修改吗？

### ISSUE THREAD

**Issue by rdkmaster** [zTree/zTree_v3#397]

**Comment by rdkmaster** [comment]
[Jigsaw](https://github.com/rdkmaster/jigsaw)采用ztree作为基础数的基础实现，封装成了[angular](https://github.com/angular/angular)组件，之前一直采用ztree这个npm包，近期发现新版本需要改为`@ztree/ztree_v3`，请问这中间的版本是否有破坏性修改？

**Comment by zTree** [comment]
现在只做小版本更新，主要就是修改 bug 和 适当补充功能。应该是可以正常升级的，不过为了稳妥起见，你们可以升级后，适当测试一下，发现什么问题可以告诉我。

@ztree/ztree_v3 是我近期才提交到 npm 上面的，以前太懒，始终没有维护 npm 的版本
