### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tId' of undefined

### ISSUE THREAD

**Issue by AbnerHao** [zTree/zTree_v3#398]
网上这个问题资源很少，不知道是啥原因

**Comment by zTree** [comment]
首先 tId 是 zTree 内部操作节点使用的属性。

其次，你没有提到你是怎么操作时报的这个错误。 但我怀疑你很可能给 zTree 操作节点的方法传递了 非 zTree 内部的节点数据。

**Comment by AbnerHao** [comment]
谢谢，目前已解决




| |
沙浩
邮箱：mmhgch@163.com
|

签名由 网易邮箱大师 定制

On 04/01/2019 09:34, zTree wrote:

首先 tId 是 zTree 内部操作节点使用的属性。

其次，你没有提到你是怎么操作时报的这个错误。 但我怀疑你很可能给 zTree 操作节点的方法传递了 非 zTree 内部的节点数据。
