### ISSUE TITLE
搜索功能问题：原本为目录节点，搜索后该目录无下级节点但前面还是显示了+号

### ISSUE THREAD

**Issue by letianzhang** [zTree/zTree_v3#399]

**Comment by zTree** [comment]
早期 zTree 的设计是 只要是 父节点 就会显示 +/- 展开的符号，不管是否有子节点存在。

对于你这种需求，要么保持现状，要么修改一下css，利用自定义图标的方式，让无子节点的节点变为叶子节点，同时设置其图标为 文件夹的图标即可。
