### ISSUE TITLE
updateNode 无效Bug

### ISSUE THREAD

**Issue by thbgh** [zTree/zTree_v3#400]
当重命名的时候,如果命名不规范,我用updateNode()还原原来的名称,treeNode数据变化了,但是tree试图没有更新
![image](https://user-images.githubusercontent.com/9399517/55375592-54789500-553f-11e9-8d7f-6c1ef7db8738.png)

![image](https://user-images.githubusercontent.com/9399517/55375542-25faba00-553f-11e9-9edc-6b57f24b3e2f.png)

**Comment by luke-huang666** [comment]
在beforeRename中使用updateNode方法刷新 确实会失效；
你场景可以用 onRename 实现，在onRename中加上你的业务逻辑，再调用updateNode更新，会生效；

**Comment by zTree** [comment]
beforeRename 执行之后 zTree 会根据 beforeRename 的返回值去重置 name 的属性，所以你之前updateNode 是无效的
