### ISSUE TITLE
selectNode选中节点后，列表中的该节点样式没有变化

### ISSUE THREAD

**Issue by celineWong7** [zTree/zTree_v3#402]
一般情况下，手动点击（选中）节点，该节点会添加上一个 .curSelectedNode 选中样式。
现在我通过treeObj.selectNode(node)的方式选中节点，但该节点没有显示出选中样式。
似乎也不会触发初始化时参数设置的callback：onClick()方法。

是本身插件api设计如此，还是说我哪里有疏漏？

**Comment by celineWong7** [comment]
代码如下：
       var treeObj = $.fn.zTree.getZTreeObj("treeUl"); // 获取treeObj，treeUl是对应ztree的id
	var node = treeObj.getNodesByParam("id", '1', null); // 获取id为1的节点
	treeObj.expandAll(true); // 展开所有列表
	treeObj.selectNode(node); // 选中指定节点
	console.log(treeObj.getSelectedNodes()); // 选中列表里确实有node数据

**Comment by zTree** [comment]
1，selectNode 方法并不会触发 onClick 事件
2，你的 node 对象得到的是一个 数组，并不是一个节点数据对象，请区分 getNodesByParam 和 getNodeByParam 的区别
