### ISSUE TITLE
jquery.ztree.all-3.5.40.js中不包含node.getpath函数

### ISSUE THREAD

**Issue by eastzq** [zTree/zTree_v3#403]

**Comment by zTree** [comment]
当然没有  getpath 了，但是有 getPath

**Comment by eastzq** [comment]
node.getPath core里边有，但是all里边报undefined

**Comment by zTree** [comment]
这是肯定不可能的。请再仔细检查一下代码，并且检查一下 你的 node 是否是 zTree 内部获取的节点数据，可以用 console.log 输出看看

**Comment by applejoo** [comment]
github上是有的，但是BootCDN上3.5.33之后就开始没有这个方法了，我查了半天这个问题

**Comment by zTree** [comment]
BootCDN 可不是我维护的。。。慎用。 请看看我在 官网上公布的有效地址

**Comment by applejoo** [comment]
只是说他的这个问题可能是这样的

**Comment by eastzq** [comment]
是的，我用的是bootCDN上的资源

**Comment by applejoo** [comment]
我昨晚也是遇到这个问题，猜发现的
