### ISSUE TITLE
父节点/子节点级联勾选问题

### ISSUE THREAD

**Issue by zhuwenbing** [zTree/zTree_v3#404]
你好，今天在使用updateNode更新节点时发现一个问题：如果被勾选的父节点或子节点所级联的节点未展开的时候，更新后这些级联的节点不会被勾选，如果这些级联的节点为展开状态则没有问题都能顺利勾选。当前的解决办法是在更新前调用expandAll或者expandNode方法展开节点后再更新。特来请教是否有更合理的方法？谢谢！

**Comment by zTree** [comment]
更合理的方法就是你需要自己制作后台接口来处理数据！！

想一下，你的数据都在后台数据库中，这一个小小的 前端 js 能自动把你尚未加载的数据全部处理一遍？？真要那么实现了，估计你会恐慌的。

**Comment by zhuwenbing** [comment]
不好意思，可能我之前没有表达清楚，，调用updateNode前这棵树是已经生成好的了（不存在任何未加载的数据），只是上面的节点都是折叠起来的，我只是调用updateNode来勾选某些节点（不会和后台发生任何交互），然后就发现了这个问题。现在的解决方案是通过node.getPath()找得级联的节点然后调用ztreeObj.expandNode(path[idx], true, true)将这些级联节点展开，最后再调用ztreeObj.updateNode(node, true)进行勾选。特在此回复记录希望能帮到有相同需求的人。最后还是非常感谢您的回答！

**Comment by zTree** [comment]
@zhuwenbing  更改 勾选状态 要使用 专门的 checkNode 方法！！ 仔细看看 API 文档

**Comment by zhuwenbing** [comment]
好的，谢谢

**Comment by shanshantoyou** [comment]
> 不好意思，可能我之前没有表达清楚，，调用updateNode前这棵树是已经生成好的了（不存在任何未加载的数据），只是上面的节点都是折叠起来的，我只是调用updateNode来勾选某些节点（不会和后台发生任何交互），然后就发现了这个问题。现在的解决方案是通过node.getPath()找得级联的节点然后调用ztreeObj.expandNode(path[idx], true, true)将这些级联节点展开，最后再调用ztreeObj.updateNode(node, true)进行勾选。特在此回复记录希望能帮到有相同需求的人。最后还是非常感谢您的回答！



> 不好意思，可能我之前没有表达清楚，，调用updateNode前这棵树是已经生成好的了（不存在任何未加载的数据），只是上面的节点都是折叠起来的，我只是调用updateNode来勾选某些节点（不会和后台发生任何交互），然后就发现了这个问题。现在的解决方案是通过node.getPath()找得级联的节点然后调用ztreeObj.expandNode(path[idx], true, true)将这些级联节点展开，最后再调用ztreeObj.updateNode(node, true)进行勾选。特在此回复记录希望能帮到有相同需求的人。最后还是非常感谢您的回答！

你好，你这种操作方法是不是也是前端递归展开，这样的如果节点过多，性能是不是不高
