### ISSUE TITLE
drag&drop not work 

### ISSUE THREAD

**Issue by DEV-RYU** [zTree/zTree_v3#405]
Hello.

I Inquire about ztree.

Drag&drop not work if there is an iframe behind the tree area.

Give me an answer. Thank you.

**Comment by zTree** [comment]
please Demo: http://www.treejs.cn/v3/demo.php#_302

if you set some iframe into this demo, Drag&drop is work well.

**Comment by DEV-RYU** [comment]
Thank you for your reply. but the problem was not resolved.
My intention is that Iframe and Tree overlap. not Iframe not contains a tree. 
I attach the attachment...
Please look at this file. (zTree_v3-master/demo/en/exedit/drag_super.html)
Please give me an answer. Thank you.

[zTree_v3-master.zip](https://github.com/zTree/zTree_v3/files/3159871/zTree_v3-master.zip)

**Comment by zTree** [comment]
I understand what happened.

When you drag node, zTree will create a mask to cover the iframe.  
But your iframe is behind the zTree Container.  So the mask cover the zTree too.

You can check the  zTreeStyle.css
```
.zTreeMask {z-index:10000; background-color:#cfcfcf; opacity:0.0; filter:alpha(opacity=0); position:absolute}
```

### Solution
Chang your zTree Container's z-index, It will work well.

```
<div class="content_wrap" style="position:absolute;top:0px; z-index: 10001;">...
```

**Comment by DEV-RYU** [comment]
I solved the problem.
Really Really Thank you.
