### ISSUE TITLE
点击CheckBox之后希望返回所有所选子节点ID，现在返回连父节点也返回

### ISSUE THREAD

**Issue by PasserbyFluid** [zTree/zTree_v3#406]
可能是方法错了，没找到，请帮忙看一下
复现：app.itolddriver.com/demo/cn/excheck

**Comment by PasserbyFluid** [comment]
http://app.itolddriver.com/demo/cn/excheck

**Comment by zTree** [comment]
你使用的获取节点的方法没有错，但是你遍历结果的方法错了。 

因为返回的节点数据是 zTree 内部正在使用的 节点数据，所以 父节点都会带有 children 属性来保存子节点。

对于你的需求来讲，该方法直接返回的数组就是满足要求的节点集合， 但这些数据中的 children 是不需要考虑的。
