### ISSUE TITLE
getSelectedNodes，getCheckedNodes 都不能够获取到被隐藏节点

### ISSUE THREAD

**Issue by qiutian00** [zTree/zTree_v3#407]
### getSelectedNodes:
可以用过滤的方式来获取被隐藏的checked节点
```javascript
   zTree.getNodesByFilter(function (node) {
                return node.checked == true;
    });
```

### getSelectedNodes:
 不知道用哪方式来获取被隐藏的selected节点

**Comment by yingrm** [comment]
模糊搜索时也遇到了这个问题，树结构变化后，之前勾选的节点获取不到了

**Comment by zTree** [comment]
被隐藏的节点怎么会有 被选中的状态？ 对于 zTree 来说这是不存在的呀。

**Comment by yingrm** [comment]
![QQ图片20190606151049](https://user-images.githubusercontent.com/15642540/59013774-70fdba00-886d-11e9-9456-a99bd48bf1c5.png)
![QQ截图20190606151118](https://user-images.githubusercontent.com/15642540/59013775-71965080-886d-11e9-84dd-f44e29e4ad49.jpg)

一个完整zTree，经过模糊搜索后，结构变化了，再调用getSelectedNodes获取选中节点，之前勾选的确实获取不到

**Comment by qiutian00** [comment]
明白了☕️
