### ISSUE TITLE
fontCss样式问题

### ISSUE THREAD

**Issue by letianzhang** [zTree/zTree_v3#408]
return treeNode.level == 0 ? {color: 'red'} : {};
当level != 0时，树节点还是红色的，我期望是恢复原本的颜色，该如何做？

**Comment by zTree** [comment]
如果 你使用的 fontCss 是 function 方式的，level !=0 时，节点文字就是默认的颜色呀。

请参考http://www.treejs.cn/v3/demo.php#_107 这个 Demo 的源码，我直接把 fontCss 里面的 内容换成你提供的规则，并且让数据产生 子节点，就是你需要实现的效果。

**Comment by letianzhang** [comment]
我是使用了updateNode进行更新节点，若return treeNode.stop == 1 ? {color: 'red'} : {};初始化树时，颜色显示完全没有问题，随后我代码更新节点，将其stop更新为0，这时候节点还是红色

**Comment by zTree** [comment]
原来是这样呀， 我也疏忽了， fontCss 使用的是 inline 方式给 元素加入 style 实现 的样式修改， 所以 当你取消 属性时，不能是设置为空，这样仍然会保留之前设置的 style，换一种写法就可以啦：

```
node.stop == 1 ? {color: 'red'} : {color: ''};
```

**Comment by letianzhang** [comment]
好的
