### ISSUE TITLE
节点数据更新有问题

### ISSUE THREAD

**Issue by ranwei-001** [zTree/zTree_v3#415]
你好！
有个问题咨询，我在解析模型的时候，把模型里的数据添加到每一个模型对应json对象里面去，然后在初始化树里面也打印出了这些数据，但是当我打印当前节点下数据的时候，数据没有发生改变，是什么原因啊

**Comment by zTree** [comment]
1、初始化 zTree 时，zTree 会直接数据对象进行 clone 并初始化后再使用的
2、所以你首先要确定你添加的属性是加给原始数据的还是加给  zTree 内的数据对象
3、再就是打印时，同样要检查你打印的是原始数据 还是zTree 内的数据对象

**Comment by ranwei-001** [comment]
1.我打印出来和调试出来的都是初始化树后里面所获取到的znodes里面显示的结果，我在每个函数里面都有用到获取tree，里面也是用到的获取当前节点返回值treenode，但是通过打印当前节点显示出来的数据没有修改前的

**Comment by zTree** [comment]
你还是跟踪代码调试一下吧，建议你使用未压缩版的的 zTree js 代码。 毕竟 视图上使用的 数据和 给你返回过来的数据不匹配，这个完全不可能呀。

**Comment by ranwei-001** [comment]
你好，咨询一下，在ztree中，我应该通过什么方式去判断我当前选中的节点，有比它更高的节点；
比如说，我新建了一个层级目录（1号楼），在该目录下我新建了四个次级目录（楼层一、二、三、四），假如说我点击楼层一，我就需要把比楼层一更大的目录删除掉，以此类推，我永远都需要把比当前选中的目录更搞得目录给删除掉，那么这种情况下，我应该用什么来判断（不能用id，因为id是随机生成的）

**Comment by zTree** [comment]
层级 的英文是 level，所以去找 和 level 相关的属性即可

**Comment by ranwei-001** [comment]
你好，请教一个问题，我如何获取我当前节点的父节点下的所有子节点，我看了ztree的API，他好像只有获取父节点，然后获取选中节点下的所有子节点，我现在是需要把这两个功能结合起来，当做一个功能使用

**Comment by zTree** [comment]
请了解一下 transformToArray  这个方法 @ranwei-001

**Comment by ranwei-001** [comment]
这个我用过了，好像就是获取选中节点下的所有子节点
