### ISSUE TITLE
同时存在isParent和children属性，children为空数组【】,  isParent: "false",但最后显示的是父亲节点

### ISSUE THREAD

**Issue by IVANLEE99** [zTree/zTree_v3#417]
![image](https://user-images.githubusercontent.com/18308725/61602784-956ef380-ac6d-11e9-8fc2-cb428b19b7a7.png)
`

> {

                  deviceID: 71,
                  children: [],
                  isParent: "false",
                  type: 2,
                  chlID: 2366,
                  id: "chn_2366",
                  parentId: "1549",
                  open: "false",
                  name: "通道3-西-东",
                  longitude: "105.408685",
                  latitude: "26.780445",
                  nodeType: "2",
                  parentName: "发展大道与中山东路路口",
                  dockID: 200103
                },
`

![image](https://user-images.githubusercontent.com/18308725/61602933-26de6580-ac6e-11e9-8b6d-8259c18ea93a.png)

**Comment by IVANLEE99** [comment]
![image](https://user-images.githubusercontent.com/18308725/61603902-1203d100-ac72-11e9-9871-19577c1ff860.png)

**Comment by zTree** [comment]
zTree 中因为允许随意操作节点，所以 判断节点是否父节点的状态是会动态变化的，所以 这里是根据 children 的情况为主进行判断的。

所以当你设置 isParent 为 false 时，应该设置 children 为 null/undefined 或者直接删除 children 属性
