### ISSUE TITLE
Author Information In Source Code

### ISSUE THREAD

**Issue by azharakbar** [zTree/zTree_v3#422]
https://github.com/zTree/zTree_v3/blob/b3597acfc77aba8f88b7e73e5a29b8dfb955ca10/js/jquery.ztree.all.js#L11

在注释信息中，建议不要向客户端暴露版本号和个人邮箱等敏感数据
Do not expose sensitive data such as version numbers and personal email addresses to the client.

Please remove this from the code

**Comment by zTree** [comment]
Please remove this by yourself, thanks.

Many users need to ask me some question by this email.
