### ISSUE TITLE
ztree使用fuzzySearch.js的模糊搜索后的半选中问题

### ISSUE THREAD

**Issue by 429365799** [zTree/zTree_v3#423]
**问题现象：**
在未搜索的时候是这样的：
![image](https://user-images.githubusercontent.com/7577355/64678452-2b740d00-d4ac-11e9-9c40-307c85824afd.png)
获取到的结果是这样子的：
![image](https://user-images.githubusercontent.com/7577355/64678493-42b2fa80-d4ac-11e9-95b6-7d288f80d141.png)

然后搜索后是这样子的：
![image](https://user-images.githubusercontent.com/7577355/64678524-55c5ca80-d4ac-11e9-8852-b5986a62c711.png)
获取到的结果是这样子的：
![image](https://user-images.githubusercontent.com/7577355/64678545-61b18c80-d4ac-11e9-85b2-ee0b25b4dcda.png)

**问题描述：**
问题出在如果我搜索后的子节点只有一个的话，那么我勾选上这个子节点会把父节点也勾选上而不是半勾选的状态，导致在搜索和未搜索的时候勾选同一个节点获取到的结果是不一样的。

**期望结果：**
期望是能在以上搜索的情况下，勾选子节点的时候，父节点能正确判断半勾选状态。

**环境信息：**
JQuery zTree core: v3.5.23
JQuery zTree exHideNodes: v3.5.23
模糊搜索用了@ztree/ztree_v3@3.5.40的fuzzySearch.js

**备注：**
我用3.5.40的ztree搭配fuzzySearch也有同样的问题，还望解惑，万分感谢！

**Comment by zTree** [comment]
请你尝试修改 treeNode.halfCheck，并使用 updateNode 方法更新视图，进行干涉。 在不考虑复杂业务逻辑的情况下，只有一个子节点，并且子节点被勾选时，父节点自然不会被设置为半勾选状态的。

**Comment by 429365799** [comment]
@zTree 多谢提示，最后解决了我的业务场景

```javascript
onCheck() {
    let checkedNodes = this.zTreeObj.getCheckedNodes(true);
    // 如果是搜索模式，需要修正选中节点中父节点的半选中状态
    if (this.zTreeObj.searchText) {
        checkedNodes.forEach(node => this.updateParentsCheckedState(node));
    }
    // 如果是父子级关联的模式，半选中状态不包括在选中列表中，除非设置了withHalfCheck=true
    if (!this.withHalfCheck && this.strict) {
        checkedNodes = checkedNodes.filter(item => {
            return !item.getCheckStatus().half
        })
    }
    this.$emit('checkedChange', checkedNodes);
},
// 更新父节点半选中状态
updateParentsCheckedState(node) {
    let parent = node.getParentNode();
    if (parent) {
        if (parent.children && parent.children.some(n => !n.checked)) {
            parent.halfCheck = true;
            this.zTreeObj.updateNode(parent);
        }

        this.updateParentsCheckedState(parent);
    }
},
```

在选中节点的时候遍历一遍选中的节点，修正半选中状态
