### ISSUE TITLE
使用 reAsyncChildNodes 报错  Uncaught TypeError: Cannot read property 'tId' of null 

### ISSUE THREAD

**Issue by charrysong** [zTree/zTree_v3#429]
addHoverDom 的 元素 onclick 事件中 reAsyncChildNodes
`

var setting = {
            async: {
                enable: true,
                url: "org_node.ashx",
                autoParam: ["id", "pId", "name"]
            },
            data: {
                simpleData: {
                    enable: true
                }
            },
            view: {
                showIcon: false,
                dblClickExpand: false,
                txtSelectedEnable: false,
                addHoverDom: addHoverDom,
                removeHoverDom: removeHoverDom,
                addDiyDom: addDiyDom,//添加自定义菜单
            },
            edit: {
                drag: {
                    autoExpandTrigger: false,
                    isMove: false,
                    isCopy: false,
                },
                enable: false,
                editNameSelectAll: false,
                showRemoveBtn: false,
                showRenameBtn: false,
                removeTitle: "删除",
                renameTitle: "重命名"
            }
 }; 

function nodeclick(obj, id, pid) {

            if (pid == null) { }
            
           else {
                let treeObj = $.fn.zTree.getZTreeObj("treeDemo");

                let node = treeObj.getNodeByParam("id", pid, null);

                treeObj.reAsyncChildNodes(node, "refresh", false, function () { });

            }
 }

`
`

var setting = {
            async: {
                enable: true,
                url: "org_node.ashx",
                autoParam: ["id", "pId", "name"]
            },
            data: {
                simpleData: {
                    enable: true
                }
            },
            view: {
                showIcon: false,
                dblClickExpand: false,
                txtSelectedEnable: false,
                addHoverDom: addHoverDom,
                removeHoverDom: removeHoverDom,
                addDiyDom: addDiyDom,//添加自定义菜单
            },
            edit: {
                drag: {
                    autoExpandTrigger: false,
                    isMove: false,
                    isCopy: false,
                },
                enable: false,
                editNameSelectAll: false,
                showRemoveBtn: false,
                showRenameBtn: false,
                removeTitle: "删除",
                renameTitle: "重命名"
            }
        };

function addHoverDom(treeId, treeNode) {

            var node = $("#" + treeNode.tId + "_a");

            if (node.find('.node_up').length == 0) {

                node.append(“<span title=\"更新当前父节点下的子节点\" class=\"ui_btn node_up\" onclick=\"nodeclick(this,” + treeNode.id + “," + treeNode.pId + ")\"><i class=\"ico up\"></i></span>");

            }

        };

`
![TIM截图20191120101625](https://user-images.githubusercontent.com/16949356/69203297-e7257d00-0b7e-11ea-919a-f0475d264889.png)

**Comment by charrysong** [comment]
`function addHoverDom(treeId, treeNode) {
            var node = $("#" + treeNode.tId + "_a");
            if (node.find('.node_up').length == 0) {
                node.append('<span href="javascript:;" title="上移" class="ui_btn node_up" onclick="nodeclick(this,' + treeNode.id + ',' + treeNode.pId + ')"><i class="ico up"></i></span>');
            }
            if (node.find('.node_down').length == 0) {
                node.append('<span href="javascript:;" title="下移" class="ui_btn node_down" onclick="nodeclick(this,' + treeNode.id + ',' + treeNode.pId + ')"><i class="ico up flipy"></i></span>');
            }
            if (node.find('.node_add').length == 0) {
                node.append('<span href="javascript:;" title="添加子级" class="ui_btn node_add" onclick="nodeclick(this,' + treeNode.id + ',' + treeNode.pId + ')"><i class="ico edit"></i></span>');
            }
            if (node.find('.node_edit').length == 0) {
                node.append('<span href="javascript:;" title="修改" class="ui_btn node_edit" onclick="nodeclick(this,' + treeNode.id + ',' + treeNode.pId + ')"><i class="ico edit"></i></span>');
            }
            if (node.find('.node_del').length == 0) {
                node.append('<span href="javascript:;"  title="删除" class="ui_btn node_del" onclick="nodeclick(this,' + treeNode.id + ',' + treeNode.pId + ')"><i class="ico del"></i></span>');
            }
        };`

**Comment by charrysong** [comment]
`
function addHoverDom(treeId, treeNode) {
            var node = $("#" + treeNode.tId + "_a");
            if (node.find('.node_up').length == 0) {
                node.append('<span href="javascript:;" title="上移" class="ui_btn node_up" onclick="nodeclick(this,' + treeNode.id + ',' + treeNode.pId + ')"><i class="ico up"></i></span>');
            }
            if (node.find('.node_down').length == 0) {
                node.append('<span href="javascript:;" title="下移" class="ui_btn node_down" onclick="nodeclick(this,' + treeNode.id + ',' + treeNode.pId + ')"><i class="ico up flipy"></i></span>');
            }
            if (node.find('.node_add').length == 0) {
                node.append('<span href="javascript:;" title="添加子级" class="ui_btn node_add" onclick="nodeclick(this,' + treeNode.id + ',' + treeNode.pId + ')"><i class="ico edit"></i></span>');
            }
            if (node.find('.node_edit').length == 0) {
                node.append('<span href="javascript:;" title="修改" class="ui_btn node_edit" onclick="nodeclick(this,' + treeNode.id + ',' + treeNode.pId + ')"><i class="ico edit"></i></span>');
            }
            if (node.find('.node_del').length == 0) {
                node.append('<span href="javascript:;"  title="删除" class="ui_btn node_del" onclick="nodeclick(this,' + treeNode.id + ',' + treeNode.pId + ')"><i class="ico del"></i></span>');
            }
        };

`

**Comment by zTree** [comment]
请再仔细查找一下错误的位置，这是在 selectNode 时报错的，但你的代码里面有没有调用 selectNode 方法，应该是你调用 selectNode 方法时，没有传入 zTree 内部的节点数据

**Comment by charrysong** [comment]
> 请再仔细查找一下错误的位置，这是在 selectNode 时报错的，但你的代码里面有没有调用 selectNode 方法，应该是你调用 selectNode 方法时，没有传入 zTree 内部的节点数据

节点的数据能重新加载，但是就是报这个错误

**Comment by zTree** [comment]
你的逻辑有问题呀！！ 点击 节点A 的时候，你却要去重新加载 A 的父节点的 子节点，这样会导致 A 节点被删除，但与此同时， zTree 还会因为 点击 A节点，要进行选中 A节点的操作，所以就出现这个错误了！
