### ISSUE TITLE
大数据量搜索，寻求解决方法

### ISSUE THREAD

**Issue by liushouqian** [zTree/zTree_v3#431]
如果是4万数据的一棵树，做搜索功能。就会很卡，在这方面会有优化吗？

**Comment by zTree** [comment]
首先，这么大的数据量，就不应该考虑把数据全部加载到前端，并且从前端进行搜索。zTree 中使用了 异步加载，以及 延迟渲染 DOM 结构，就是为了尽量避免大数据量时的性能瓶颈。你这种需求，应该首先考虑在后台提供搜索接口，返回搜索结果，前端根据搜索结果动态显示树结构。

**Comment by liushouqian** [comment]
感谢回复，晓得怎样做了
