### ISSUE TITLE
拖拽到两个节点中间，会显示平级，但是实际上可能是这两个节点的子节点

### ISSUE THREAD

**Issue by dev-caofei** [zTree/zTree_v3#432]

**Comment by dev-caofei** [comment]
onDrop参数targetNode其实是，这两个节点中的某一个，而不是这两个节点的父节点。

**Comment by dev-caofei** [comment]
@zTree

**Comment by dev-caofei** [comment]
![微信截图_20191209103435](https://user-images.githubusercontent.com/8357403/70402787-88fa0480-1a6f-11ea-9e80-390aa49dd178.png)

**Comment by zTree** [comment]
朋友，不能只看 targetNode 这一个参数呀，还有一个重要的参数是 moveType

**Comment by dev-caofei** [comment]
![ing](https://user-images.githubusercontent.com/8357403/70403038-703e1e80-1a70-11ea-968a-8d0deeabdd60.png)
这样拖拽。
![show](https://user-images.githubusercontent.com/8357403/70403054-80ee9480-1a70-11ea-9cbc-90dc578f3d4b.png)
显示这样。
![actual](https://user-images.githubusercontent.com/8357403/70403056-8946cf80-1a70-11ea-8780-bcb9e306e161.png)
实际上是这样。
![微信截图_20191209104246](https://user-images.githubusercontent.com/8357403/70403092-ada2ac00-1a70-11ea-8356-5fcf49ab9890.png)
moveType是next。
@zTree

**Comment by dev-caofei** [comment]
感谢，确实是这样，要根据moveType判断。
