### ISSUE TITLE
文档中setting.async.headers没有实际生效

### ISSUE THREAD

**Issue by the8th** [zTree/zTree_v3#433]
经阅读源码得知，setting.async.headers这一jquery ajax选项并没有设置到$.ajax中。

需要在jquery.ztree.all.js第1004行增加如下代码：
headers: setting.async.headers。

另外，实际项目中，异步请求很可能都是封装过的，包含了很多自定义header等内容，仅使用ztree暴露的api很难统一管理。建议允许setting.async为一个promise，具体如何异步交由业务代码自行实现

**Comment by zTree** [comment]
1，关于 headers ， jquery.ztree.core.js line1079；jquery.ztree.all.js line 1080 有你说的内容啊

2，如果自行实现完全可以 利用 beforeAsync 回调 return false 阻止 zTree 默认异步加载，然后转由自己的方法去进行异步加载， 完成后 利用添加节点的方法即将节点可加入到 zTree 内部

**Comment by the8th** [comment]
看了源码，的确有。
我从npm得到的版本是 JQuery zTree core v3.5.23
发布日期是2016-04-01，这个版本的确是没有设置header的。我再研究一下

**Comment by zTree** [comment]
npm 要去找 npm install @ztree/ztree_v3 这个的
