### ISSUE TITLE
Why does the parent node not exist，The child node becomes the root node

### ISSUE THREAD

**Issue by yigegehao** [zTree/zTree_v3#436]
Why does the parent node not exist，The child node becomes the root node，Is it possible to filter out nodes whose parent node does not exist

**Comment by zTree** [comment]
The rule of zTree is this, the node that cannot find the parent node will be regarded as the root node. You can filter the data of the nodes by yourself

**Comment by yigegehao** [comment]
Ok, thank you for your answer
