### ISSUE TITLE
content样式错误，应该为  content: "\f054";content attribute is wrong,it supposed to be content: "\f054";），

### ISSUE THREAD

**Issue by Jermyk93** [zTree/zTree_v3#439]
https://github.com/zTree/zTree_v3/blob/7939cd81878e2c4f8e3af0b682514799cb79f30c/css/awesomeStyle/awesome.css#L218

**Comment by Jermyk93** [comment]
content attribute is wrong,it supposed to be `content: "\f054"`;

**Comment by zTree** [comment]
thank you. I will fixed this issue as soon as possible
