### ISSUE TITLE
when i use awesomeStyle/awesome.css,the modified icon styel can't hide the icon.

### ISSUE THREAD

**Issue by Jermyk93** [zTree/zTree_v3#440]
https://github.com/zTree/zTree_v3/blob/7939cd81878e2c4f8e3af0b682514799cb79f30c/js/jquery.ztree.core.js#L1360

**Comment by Jermyk93** [comment]
l try to modify it to `width:0px;height:0px;visibility:hidden;` and `display:none;`,both of them hide the icon,so can you change the style?

**Comment by Jermyk93** [comment]
sorry，i forget to say that i use the **view** attribute `showIcon:false`,but the icon and part of the font overlap.

**Comment by Jermyk93** [comment]
after i add the showIcon attribute [picture](https://github.com/Jermyk93/images/blob/master/awesomeModified.jpg)

**Comment by zTree** [comment]
the issue is because the  font-icon; I will fixed this and the other issue.

**Comment by zTree** [comment]
I have fixed this issue.
