### ISSUE TITLE
v3.5.42版本 当node的children为空数组时会导致节点isParent=true

### ISSUE THREAD

**Issue by lwjx** [zTree/zTree_v3#443]
追踪后发现bug原因，文件：jquery.ztree.core.js,Row：306  if语句 只判断了children是否为数组，缺少判断children.length>0

**Comment by zTree** [comment]
这个不是bug，应该是咱们两个对于是否为父节点的定义有分歧。
我这么实现的原因是考虑到 父节点的子节点数目就是空，但它本身也是父节点的情况。

所以， 在 setting 里面有 setting.data.keep.leaf / setting.data.keep.parent 两个属性用于配置是否锁定 叶子节点/父节点 状态，否则在节点发生变化时，就会自动处理 children 属性。
