### ISSUE TITLE
3000条数据使用fuzzySearch()搜索，chrome卡成狗

### ISSUE THREAD

**Issue by Teeeeeequila** [zTree/zTree_v3#449]
大概3000多条数据，在使用fuzzySearch()搜索时，浏览器就开始延迟2、3秒响应操作，是我使用不当吗

**Comment by Teeeeeequila** [comment]
在执行搜索时，chrome内存占用率瞬间130%，是否算法有问题？

**Comment by zTree** [comment]
等我抽空测试一下，再给你反馈吧

**Comment by zTree** [comment]
最近工作比较忙，回复 信息也就拖后了很多，请见谅。

fuzzySearch 是一位 zTree 的用户，把自己的作品提交过来，供大家参考和使用的。但 fuzzySearch 的工作方式是利用 隐藏节点的功能实现的。所以其实性能问题主要是出现在反复操作节点 DOM 的渲染上了。

请你参考一下 我专门针对 大数据制作的几个 Demo。zTree 使用惰性加载，就是为了提升性能。但 fuzzySearch 会把搜到的所有节点进行展开，这种操作其实就是将 zTree 的优化一下载化为乌有。其实就相当于做了一个全部展开的操作，然后把不该显示的节点隐藏了起来。

所以， fuzzySearch 主要是给出一个思路，并且不适合针对大数据量情况下的处理。

建议：针对大数据量的情况下，就不要直接把 fuzzySearch 拿来使用了。你可以利用 fuzzySearch 的算法，找到所有需要显示的节点，然后利用 zTree 的init 方法重新初始化树节点，效果肯定会更好一些的。再就是针对你自己的情况，可以设置是否需要初始化就展开所有节点，以及是否使用动画，这些都是可以提升性能的部分。
