### ISSUE TITLE
升级到.net core 3.0后的问题

### ISSUE THREAD

**Issue by yongqingxie** [zTree/zTree_v3#452]
升级.net core 3.0以后 ztree渲染就把子节点变成了父节点 当最后一个节点下没有子节点时 依然是父节点
下图中 test下面已经没有子节点了 但它现在依然是父节点
![TIM截图20200330115142](https://user-images.githubusercontent.com/24885976/77873638-22e2f880-727d-11ea-85f0-8050fcdf42a3.png)

net core版本:3.1.101
操作系统:microsoft windows  10 1903
浏览器版本:google chrome 80
ztree版本:zTree_v3-3.5.42
jquery版本:v3.4.1
bootstrap版本:v3.3.7
angularjs版本:v1.7.8

**Comment by zTree** [comment]
请检查你提供给 zTree 的节点数据 是否正常，是否带有 children 属性

**Comment by yongqingxie** [comment]
> 请检查你提供给 zTree 的节点数据 是否正常，是否带有 children 属性

节点数据都是正常的 因为在.net core 2.0是完全正常的
![TIM截图20200401104136](https://user-images.githubusercontent.com/24885976/78093720-649eab00-7405-11ea-8341-7439ab83c1ab.png)

**Comment by yongqingxie** [comment]
已解决
