### ISSUE TITLE
初始化节点时，判断节点的'zAsync'问题？

### ISSUE THREAD

**Issue by Diazhao** [zTree/zTree_v3#455]
你好，在3.5.29版本中，判断方式为
```
if (n[childKey] && n[childKey].length > 0) {
				n.isParent = true;
				n.zAsync = true;
			} else {
				n.isParent =
					typeof n.isParent === 'string' ? tools.eqs(n.isParent, 'true') : !!n.isParent;
				n.open = n.isParent && !setting.async.enable ? n.open : false;
				n.zAsync = !n.isParent;
			}
```
在3.5.44版本中，判断方式修改为
```
if (tools.isArray(children)) {
        data.nodeIsParent(setting, n, true);
        n.zAsync = true;
      } else {
        isParent = data.nodeIsParent(setting, n, isParent);
        n.open = (isParent && !setting.async.enable) ? n.open : false;
        n.zAsync = !isParent;
      }
```
在老一些的版本中需要校验children为数组，并且数组的长度大于0；
新版本中却只要是数组就可以判定zAsync为true；
是否应该修改为确认是数组，并且数组长度大于0更兼容老版本一些？
`if (tools.isArray(children) && children.length > 0) {`

**Comment by zTree** [comment]
抱歉，请修改你的程序中的逻辑来兼容最新版本的逻辑。

*2017.12.28* v3.5.31
   * [修改] 初始化节点数据的规则，支持 treeNode { name: "Node2", children: []}, 情况下自动设置为 isParent = true

以上是 修改的的 log，这应该是专门进行的修改。我思考了一下，觉得不能因为这种情况再把代码逻辑修改回去，而应该按照当前更严格的规范来执行。 既然生成了 children 属性，且数组为空，其意义就是表明该节点的子节点为空； 如果仅仅是为了异步加载，而设置节点为父节点，那么就应该设置 isParent 属性，而不是 设置一个 children 为空数组
