### ISSUE TITLE
怎么样允许拖拽时多个被选择的节点不是同级关系 ，通过拖拽被选择的节点，来触发事件

### ISSUE THREAD

**Issue by Yourroot** [zTree/zTree_v3#458]

**Comment by Yourroot** [comment]
`比如允许拖拽红色这部分
![6](https://user-images.githubusercontent.com/29765892/85998861-eff7fe80-ba3d-11ea-8f00-a0aacd8c4660.png)
`

**Comment by zTree** [comment]
抱歉，这种逻辑是被禁止的。因为可能出现的情况太多，容易造成数据混乱。所以直接就在源头禁止了
