### ISSUE TITLE
expandNode 虚展开

### ISSUE THREAD

**Issue by ShiRouMi** [zTree/zTree_v3#462]
搜索 ztree， 找到匹配的节点进行展开，第一次搜索正常展开，第二次搜索就会虚展开。调试中发现，在偶次搜索的过程中，调用expandNode 正常展开过，但是最后又会虚展开。呈现如下情况
![image](https://user-images.githubusercontent.com/8840585/90588034-3f240980-e20d-11ea-9311-e2fa0ce2a519.png)

每次搜索后强行调用 refresh 方法重刷一遍 ztree 能解决问题，但这样会严重影响性能。

**Comment by zTree** [comment]
你这种使用方式时，建议关闭展开的动画效果，试试看

**Comment by ShiRouMi** [comment]
嗯嗯  的确可以。在 expandAll 前关闭动画，expand 后打开动画即可。
```js
treeObj.setting.view.expandSpeed = "";
treeObj.expandAll(false);
treeObj.setting.view.expandSpeed = "fast";
```
