### ISSUE TITLE
节点初始化的时候需要渲染为半选状态，又希望该半选状态能自动根据子节点的勾选状态联动，这样的需求不知道大佬有没有好的方式来实现下

### ISSUE THREAD

**Issue by LeoMao0808** [zTree/zTree_v3#466]
异步渲染数据会有这个需求，我在加载数据的时候会遍历 父级节点的所有子节点的选中状态或者根据父节点的getCheckStatus（）方法来还原父节点的半选状态，使用到的是api中给到的halfCheck（强制为半勾选状态后，不再进行自动计算半勾选状态）属性，这样设置后父节点的勾选状态不再根据子节点的勾选状态来联动了。不知道我描述的是否明白，如果明白请大佬给点建议！！！感谢！！！

**Comment by zTree** [comment]
目前来说一定要这么实现，只能是你自己在获取子节点后，去修正父节点的勾选状态
