### ISSUE TITLE
Module not found: Error: Can't resolve '@ztree/ztree_v3'

### ISSUE THREAD

**Issue by yinjinit** [zTree/zTree_v3#468]
When I try to import ztree in typescript file, it shows the error above. I am not pro in typescript so please help me to solve this problem. How can I import ztree_v3 on typescript file.

**Comment by zTree** [comment]
Sorry,  zTree is just a jQuery plugin. 
It does not use react framework and typescript.

I have not used zTree in typescript and react projects either.

You can study how uses other jQuery plug-ins in typescript. You should be able to use zTree normally in the same way.

(PS: You can contact the author who made index.d.ts  https://github.com/bseddon)   

I hope you can write down the solution here after solving the problem for other friends to use, thank you
