### ISSUE TITLE
node端使用buffer作为数据时的问题

### ISSUE THREAD

**Issue by qishibo** [zTree/zTree_v3#474]
`{name:"test1",bufferData: Buffer.from([111])`
这种作为节点数据时，onclick事件的调用参数`treeNode`中的bufferData属性转为了object了，不是原来的buffer类型，类似下面的
`{0: 49, 1: 49, 2: 49, readBigUInt64LE: ƒ, readBigUInt64BE: ƒ, readBigInt64LE: ƒ, readBigInt64BE: ƒ, writeBigUInt64LE: ƒ, …}`

**Comment by zTree** [comment]
因为 zTree 导入数据时，做了深度的 clone 操作，但肯定是不支持你目前使用的 Buffer 这种类型，建议你这种特殊类型的数据专门用 Map 保存到其他地方，给 节点配上对应的id 当作key，这样就可以随时检索到这种特殊数据了

**Comment by qishibo** [comment]
换了个方法，用toJSON把buffer转为object后再作为属性带着就好了，使用时再转回来
