### ISSUE TITLE
dataFilter能否支持async await

### ISSUE THREAD

**Issue by WifiStop** [zTree/zTree_v3#477]
目前使用中，在dataFilter发起网络请求，将不会去等待请求完毕之后在去添加子节点。请问ztree有别的方案在展开节点的时候请求两个接口吗

**Comment by zTree** [comment]
这代码太古老了，现在不太方便直接修改成支持 async 的代码，主要也担心 旧浏览器的兼容问题。

建议你 利用 beforeAsync 方法，阻止 zTree 自己的 异步加载，你自己实现 ajax，获取数据后，再自行使用 addNodes 方法导入数据即可，这样你的灵活性就多了很多
