### ISSUE TITLE
你好，fuzzySearch模糊搜索时，50%几率会报Cannot read property '_z' of undefined  at jquery.ztree.exhide.js:287

### ISSUE THREAD

**Issue by wangjiangbo0427** [zTree/zTree_v3#478]

**Comment by zTree** [comment]
http://www.treejs.cn/v3/demo.php#_516  Demo上并不会出现 50%的几率，你这种报告 issue 的方式几乎起不到任何作用。

**Comment by wangjiangbo0427** [comment]
初始化fuzzySearch()时，exhide文件中$.extend(true, $.fn.zTree._z, _z) 里$.fn.zTree有时为undefined，请问该怎么解决

**Comment by zTree** [comment]
这个就准确多了，仔细检查你的代码框架吧，看看是否会由于不同页面 或者不同插件的加载，导致 反复加载 jquery 吧
