### ISSUE TITLE
setting.data.render使用方法描述出错

### ISSUE THREAD

**Issue by 768141033** [zTree/zTree_v3#482]
api文档描述为
var setting = {
		data: {
			render: function(name,treeNode){
				return name + treeNode.id;
			}
		}
	};
实际使用失效，经测试，实际使用方法为
var setting = {
		data: {
			render: {
                               name: function(name, treeNode) {
                                           return name + treeNode.id
                                }
                          }
		 }
	};

**Comment by zTree** [comment]
多谢，的确是当时写api demo 的时候疏忽了

**Comment by gMan1990** [comment]
@zTree 为啥我用了后没效果？v-3.5.24

**Comment by zTree** [comment]
> @zTree 为啥我用了后没效果？v-3.5.24

<img width="288" alt="image" src="https://github.com/zTree/zTree_v3/assets/682855/207075ba-7b2f-4122-8417-99a3d46865d8">

请注意 API 中的版本说明， 这个功能是 v3.5.45 才加上的
