### ISSUE TITLE
当setting 配置nameIsHTML时候,鼠标放到节点上显示的名字是HTML标签,为什么不是显示的名字,好无奈呀..

### ISSUE THREAD

**Issue by xinyaxi** [zTree/zTree_v3#483]
当setting 配置nameIsHTML时候,鼠标放到节点上显示的名字是HTML标签,为什么不是显示的名字,好无奈呀..
![](https://myrgb.space:4433/s/MF2JYCrxEdqJAbK/preview)

**Comment by zTree** [comment]
setting.data.key.title
