### ISSUE TITLE
Uncaught TypeError: Cannot read property 'match' of null 

### ISSUE THREAD

**Issue by Vacny** [zTree/zTree_v3#484]
生成树包含a标签且没有href属性，导致Uncaught TypeError: Cannot read property 'match' of null

**Comment by zTree** [comment]
请先确定是哪儿报的这个 错误

**Comment by Vacny** [comment]
![image](https://user-images.githubusercontent.com/29767078/126598466-ab2d6617-fab7-4326-a25b-05a5644de398.png)

**Comment by Vacny** [comment]
这个是断点的堆栈，我项目里面没有加对a标签的监听。。。不清楚这玩意是怎么出现的

**Comment by zTree** [comment]
检查你的浏览器是不是装什么插件了？ 看你这里面都什么乱七八糟的，又是 jd 又是 taobao 的

**Comment by Vacny** [comment]
![Uploading image.png…]()

好吧。。这个的问题

**Comment by Vacny** [comment]
![image](https://user-images.githubusercontent.com/29767078/127122839-f1919918-f7b5-4465-9e2e-dae3af7869bb.png)
这个插件的问题。。。
