### ISSUE TITLE
子节点全选反选问题

### ISSUE THREAD

**Issue by louandme** [zTree/zTree_v3#489]
chkboxType不管是选中或取消时影响父节点都是无法达到子节点全部选中才选中父节点或者子节点取消一个就取消选中父节点,

**Comment by zTree** [comment]
http://www.treejs.cn/v3/demo.php#_202

请对照这个 Demo 操作，看看是否有你说的情况

**Comment by louandme** [comment]
![1630476859(1)](https://user-images.githubusercontent.com/53675908/131621368-d2038cb8-8bb5-411f-842a-fc1988de2383.png)
正如图中所示，我只选中了一个子节点，实际上却是选中了父节点，子节点取消一个就取消选中父节点明显在图中就无法做到

**Comment by zTree** [comment]
那我明白了，你的需求是 子节点全部选中，父节点才能选中，否则就不能选中。
如果是这样的话很容易实现，只需要修改  css，让 半勾选的父节点 显示成未勾选的样子就是了，你看到的这种情况：子节点没有完全被勾选时，父节点这种状态其实表明的是半勾选。

**Comment by louandme** [comment]
我看其他的树形组件，其实半选中其实是不算选中的，改css也只是让样式变得看起来没选中
![1630480847(1)](https://user-images.githubusercontent.com/53675908/131630944-a889e95c-9450-40f5-b037-a293ca59d584.png)
![1630481300(1)](https://user-images.githubusercontent.com/53675908/131630960-3b3e9589-4f62-4009-9c0c-7404e9effefb.png)

**Comment by zTree** [comment]
就是个 css 样式问题，你很容易会就可以修改的
