### ISSUE TITLE
基于节点dom结构缩进方式的问题

### ISSUE THREAD

**Issue by Cassandra000** [zTree/zTree_v3#491]
树节点的dom是padding-left 的形式做的层级缩进，使用时发现：
当层级较深时，
1. 树节点左侧区域（展开节点左侧空白部分）因没有dom而无法响应事件；
2. 难以给整行（包含左侧无dom区域）添加hover时的背景；
是否有其他解决办法？

**Comment by zTree** [comment]
修改样式吧，让每一行节点不是外层缩进，改成内部缩进
