### ISSUE TITLE
zTree  in a web framework, without going for iframes : possible?

### ISSUE THREAD

**Issue by PY-Delens** [zTree/zTree_v3#517]
Dear,

I first thank you for your wonderful plugin : zTree, which I selected after long searches.
I head already basic tests and understanding of the components and main settings and fole dependencies of Ztree, a little less about the API.
I’m working with the Flask (Python) framework, which means with Jinga2 for templating, and mainly for managing the so called ‘holygrail’ layout (header + left side menu + main content + footer).
For my web projects, I will often use a tree menu for the left side menu; while Iframes design is a bit outdated (responsiveness, flexgrid …).

My code below is very basic; with this elementary test, 
if, from Ztree_test1a.htm , I point the url to the same page Ztree_test1a.htm, I get OK, although – as suspected -  the tree is reinitialized : I’m losing the state of expansion/contraction of the mapmenu items.
QUESTION : 
Is there a way to save the current state of the tree for displaying it in the same state with another page of my website, after the click – url process?
Is it possible with javascript, without going and back to the server side?
I presume such feature is foreseen in your tool, but I need some guidance / example
Can you help me on this?
   var zNodes = [
   {name:"test1", open:true, children:[
      {name:"test1_1", url:"targetForZtreeTest1a.htm"}, {name:"test1_2"}]},
   {name:"test2", open:true, children:[
      {name:"test2_1"}, {name:"test2_2"}]},
   {name:"testC", open:true, children:[
      {name:"testC_1", url:"targetForZtreeTest1a.htm"}, {name:"testC_2", url:"Ztree_test1a.htm"}]},
   ];

AND :
   var setting = {
      view: {
        dblClickExpand: true,
        showLine: true,
        selectedMulti: false,
        showIcon: true
      },
      data: {
        simpleData: {
          enable: false,
          idKey: "id",
          pIdKey: "pId",
          rootPId: ""
        }
      },
      callback: {
        beforeDblClick: function (treeId, treeNode) {
          var zTree = $.fn.zTree.getZTreeObj("tree");
          if (treeNode.isParent) {
            zTree.expandNode(treeNode);
            return false;
          }
          else {
            alert ("alerte");
            return true;
          }
        }
        

      },
    };

Awaiting from you,
thanks on forward
__________________________________________________________________
Pierre-Yves Delens, ir-arch.
Rue de Bau, 26   -   1450  -  Blanmont

GSM : 00 32 (0)476 54 47 31
pyd@pyDelens.be

__________________________________________________________________
Pierre-Yves Delens
Rue de Bau, 26   -   1450  -  Blanmont

GSM : 00 32 (0)476 54 47 31
pyd@pyDelens.be

**Comment by zTree** [comment]
hello,

You can use the click event of the node to open a new page with js code, and add the id of the node to be expanded to the querystring. When displaying the page, expand the node according to the corresponding id.

In addition, you can use cookie or localstorage to save the node id that needs to be expanded, and delete the corresponding data after the page is used.

How to choose, need to judge according to your actual scene.

**Comment by PY-Delens** [comment]
Thanks very much for your quick answer !

 

However, your answer seems to focus on the concerned (clicked) node state only :

what if I want the user to see – after linking – the zTree globally in the same state as before clicking?

I mean: with some nodes expanded, some others not?

 

Thanks on forward

 

__________________________________________________________________

Pierre-Yves Delens, ir-arch.

Rue de Bau, 26   -   1450  -  Blanmont

 

GSM : 00 32 (0)476 54 47 31

 ***@***.***> ***@***.***

 

De : zTree ***@***.***> 
Envoyé : mercredi 29 mars 2023 11:30
À : zTree/zTree_v3 ***@***.***>
Cc : Pierre-Yves Delens ***@***.***>; Author ***@***.***>
Objet : Re: [zTree/zTree_v3] zTree in a web framework, without going for iframes : possible? (Issue #517)

 

hello,

You can use the click event of the node to open a new page with js code, and add the id of the node to be expanded to the querystring. When displaying the page, expand the node according to the corresponding id.

In addition, you can use cookie or localstorage to save the node id that needs to be expanded, and delete the corresponding data after the page is used.

How to choose, need to judge according to your actual scene.

**Comment by PY-Delens** [comment]
Dear, 

I think I’m almost ok with your solution:

I could make use of “localstorage” to store the tree data with the open/closed state of all the nodes,

But, once I’m on the target page, when I make appeal on the data (Javascript ? JSON data ? ) passed from the calling page, as to populate the zTree (in the target page), there is a problem of format ( object/literal/string) : see snapshot below.

 

The 2 concerned pages are attached, but my code isn’t yet cleaned. I hope you get the problem just with the snapshot.  😉   :-/

 

I struggeled with JSON.stringify, with JSON.parse, etc, at various steps of the code, 
but I’m not yet clear with the processing of JSON objects wich seem to be at the same time a string, a literal, an object (and not an array, in the context of wht I’m trying to code : ?).

 

Finally, I suppose that, like in the demo code , zTree is NOT making use of JSON, but juste Javascript datas.

But what is happening once we store the znodes datas in localstorage? 
oR : … What should happen?

 

Is it just a matter of adding/deleting quotes around the array?

 

 

My passedjsontext should look like this in the Chrome debugger :


(9) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]

1. 0: {id: 1, pId: '', name: "Histoire d'une recherche Test1a", open: false, isParent: true, …}

2. 1: {id: 101, pId: 1, name: 'Trouver un lieu Test1a2', file: 'core/standardData-fromDemoIframe', url: 'targetForZtreeTest1a2.htm', …}

3. 2: {id: 102, pId: 1, name: "Gedinne - et rien d'autre Test1a", file: 'core/simpleData', url: 'targetForZtreeTest1a.htm', …}

4. 3: {id: 2, pId: '', name: 'Découverte Test1a3', open: false, isParent: true, …}

5. 4: {id: 201, pId: 2, name: 'mmm', file: 'excheck/checkbox', level: 1, …}

6. 5: {id: 202, pId: 2, name: 'nn nn', level: 1, tId: 'treeDemo_6', …}

7. 6: {id: 202, pId: 2, name: 'Sous la Forge - Copinette- ', level: 1, tId: 'treeDemo_7', …}

8. 7: {id: 3, pId: '', name: 'Inauguration', open: true, isParent: true, …}

9. 8: {id: 301, pId: 3, name: 'Inauguration-Détail', open: false, level: 1, …}

But I get this :

'[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]'

 




So, when building/initiating the zTree in the Target page, I don’t give the right datatype to the line 84 :

10.          zTreeObj = $.fn.zTree.init($("#treeDemo"), localStorage.getItem("zNodesLS"));

 

Can you help me a nudge?

 

Thanks on forward

 

P-Y Delens

 

Here the calling page : http://localhost:1180/ztree_test1a.htm

 




 

De : ***@***.*** ***@***.***> 
Envoyé : mercredi 29 mars 2023 16:39
À : 'zTree/zTree_v3' ***@***.***>
Objet : RE: [zTree/zTree_v3] zTree in a web framework, without going for iframes : possible? (Issue #517)

 

Thanks very much for your quick answer !

 

However, your answer seems to focus on the concerned (clicked) node state only :

what if I want the user to see – after linking – the zTree globally in the same state as before clicking?

I mean: with some nodes expanded, some others not?

 

Thanks on forward

 

__________________________________________________________________

Pierre-Yves Delens, ir-arch.

Rue de Bau, 26   -   1450  -  Blanmont

 

GSM : 00 32 (0)476 54 47 31

 ***@***.***> ***@***.***

 

De : zTree ***@***.*** ***@***.***> > 
Envoyé : mercredi 29 mars 2023 11:30
À : zTree/zTree_v3 ***@***.*** ***@***.***> >
Cc : Pierre-Yves Delens ***@***.*** ***@***.***> >; Author ***@***.*** ***@***.***> >
Objet : Re: [zTree/zTree_v3] zTree in a web framework, without going for iframes : possible? (Issue #517)

 

hello,

You can use the click event of the node to open a new page with js code, and add the id of the node to be expanded to the querystring. When displaying the page, expand the node according to the corresponding id.

In addition, you can use cookie or localstorage to save the node id that needs to be expanded, and delete the corresponding data after the page is used.

How to choose, need to judge according to your actual scene.

**Comment by PY-Delens** [comment]
Dear, 

I got the solution OK.

Issue : Closed

 

PY D.

 

De : ***@***.*** ***@***.***> 
Envoyé : mardi 18 avril 2023 23:27
À : 'zTree/zTree_v3' ***@***.***>
Objet : RE2: [zTree/zTree_v3] zTree in a web framework, without going for iframes : possible? (Issue #517) - YES, with localstorage OK, but problem of passing the datas in the right format

 

Dear, 

I think I’m almost ok with your solution:

I could make use of “localstorage” to store the tree data with the open/closed state of all the nodes,

But, once I’m on the target page, when I make appeal on the data (Javascript ? JSON data ? ) passed from the calling page, as to populate the zTree (in the target page), there is a problem of format ( object/literal/string) : see snapshot below.

 

The 2 concerned pages are attached, but my code isn’t yet cleaned. I hope you get the problem just with the snapshot.  😉   :-/

 

I struggeled with JSON.stringify, with JSON.parse, etc, at various steps of the code, 
but I’m not yet clear with the processing of JSON objects wich seem to be at the same time a string, a literal, an object (and not an array, in the context of wht I’m trying to code : ?).

 

Finally, I suppose that, like in the demo code , zTree is NOT making use of JSON, but juste Javascript datas.

But what is happening once we store the znodes datas in localstorage? 
oR : … What should happen?

 

Is it just a matter of adding/deleting quotes around the array?

 

 

My passedjsontext should look like this in the Chrome debugger :


(9) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]

1. 0: {id: 1, pId: '', name: "Histoire d'une recherche Test1a", open: false, isParent: true, …}

2. 1: {id: 101, pId: 1, name: 'Trouver un lieu Test1a2', file: 'core/standardData-fromDemoIframe', url: 'targetForZtreeTest1a2.htm', …}

3. 2: {id: 102, pId: 1, name: "Gedinne - et rien d'autre Test1a", file: 'core/simpleData', url: 'targetForZtreeTest1a.htm', …}

4. 3: {id: 2, pId: '', name: 'Découverte Test1a3', open: false, isParent: true, …}

5. 4: {id: 201, pId: 2, name: 'mmm', file: 'excheck/checkbox', level: 1, …}

6. 5: {id: 202, pId: 2, name: 'nn nn', level: 1, tId: 'treeDemo_6', …}

7. 6: {id: 202, pId: 2, name: 'Sous la Forge - Copinette- ', level: 1, tId: 'treeDemo_7', …}

8. 7: {id: 3, pId: '', name: 'Inauguration', open: true, isParent: true, …}

9. 8: {id: 301, pId: 3, name: 'Inauguration-Détail', open: false, level: 1, …}

 

But I get this :

'[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]'

 




So, when building/initiating the zTree in the Target page, I don’t give the right datatype to the line 84 :

10.          zTreeObj = $.fn.zTree.init($("#treeDemo"), localStorage.getItem("zNodesLS"));

 

Can you help me a nudge?

 

Thanks on forward

 

P-Y Delens

 

Here the calling page : http://localhost:1180/ztree_test1a.htm

 




 

De : ***@***.*** ***@***.***>  ***@***.*** ***@***.***> > 
Envoyé : mercredi 29 mars 2023 16:39
À : 'zTree/zTree_v3' ***@***.*** ***@***.***> >
Objet : RE: [zTree/zTree_v3] zTree in a web framework, without going for iframes : possible? (Issue #517)

 

Thanks very much for your quick answer !

 

However, your answer seems to focus on the concerned (clicked) node state only :

what if I want the user to see – after linking – the zTree globally in the same state as before clicking?

I mean: with some nodes expanded, some others not?

 

Thanks on forward

 

__________________________________________________________________

Pierre-Yves Delens, ir-arch.

Rue de Bau, 26   -   1450  -  Blanmont

 

GSM : 00 32 (0)476 54 47 31

 ***@***.***> ***@***.***

 

De : zTree ***@***.*** ***@***.***> > 
Envoyé : mercredi 29 mars 2023 11:30
À : zTree/zTree_v3 ***@***.*** ***@***.***> >
Cc : Pierre-Yves Delens ***@***.*** ***@***.***> >; Author ***@***.*** ***@***.***> >
Objet : Re: [zTree/zTree_v3] zTree in a web framework, without going for iframes : possible? (Issue #517)

 

hello,

You can use the click event of the node to open a new page with js code, and add the id of the node to be expanded to the querystring. When displaying the page, expand the node according to the corresponding id.

In addition, you can use cookie or localstorage to save the node id that needs to be expanded, and delete the corresponding data after the page is used.

How to choose, need to judge according to your actual scene.

**Comment by zTree** [comment]
You can only save the id.

**Comment by PY-Delens** [comment]
Thanks

 

De : zTree ***@***.***> 
Envoyé : mardi 25 avril 2023 12:48
À : zTree/zTree_v3 ***@***.***>
Cc : Pierre-Yves Delens ***@***.***>; Author ***@***.***>
Objet : Re: [zTree/zTree_v3] zTree in a web framework, without going for iframes : possible? (Issue #517)

 

You can only save the id.
