### ISSUE TITLE
老哥 我打算修改样式 比如每个节点的高度 line-height之类的  有没有修改建议 改哪些class之类的

### ISSUE THREAD

**Issue by NightMingGit** [zTree/zTree_v3#518]
改过一些样式，但是貌似拖动的时候箭头显示位置不太正常

**Comment by zTree** [comment]
用未压缩的代码调试啊，看看是什么原因导致的。

现在 zTree 基本上已经不维护了，用的人也越来越少了。你可以根据自己需要随便修改

**Comment by NightMingGit** [comment]
> 用未压缩的代码调试啊，看看是什么原因导致的。
> 
> 现在 zTree 基本上已经不维护了，用的人也越来越少了。你可以根据自己需要随便修改

我觉得功能很强 比那些UI库的树组件好用多了
