### ISSUE TITLE
有纯JavaScript版本么？

### ISSUE THREAD

**Issue by callmesoul** [zTree/zTree_v3#522]
如题

**Comment by zTree** [comment]
恕本人才疏学浅，请解释一下什么叫做 纯 javascript 版本？

**Comment by BlueGalaxyForest** [comment]
他的意思是不借助任何框架实现的zTree

**Comment by callmesoul** [comment]
> 恕本人才疏学浅，请解释一下什么叫做 纯 javascript 版本？
就是不依赖jquery的

**Comment by zTree** [comment]
只有依赖 jquery 的。 而且目前也不维护了
