### ISSUE TITLE
异步加载能不发请求吗

### ISSUE THREAD

**Issue by ZenkieBear** [zTree/zTree_v3#523]
您好，我这边看到官网提供一个异步加载的api来优化海量数据的渲染。目前我们的方案是滚动加载（数据一次性加载，每次触底添加节点），但是这种方式会有一些问题。
async配置的方式目前只能通过url获取数据吗，能否改为一个callback函数，数据填充由我们开发者实现？

**Comment by zTree** [comment]
自己随便改吧，目前这个版本已经不维护了。

你这种需求其实有很多种方式来实现，自己监听滚动条时间，获取数据利用 addNode 方式自己添加节点都可以的

**Comment by ZenkieBear** [comment]
> 自己随便改吧，目前这个版本已经不维护了。
> 
> 你这种需求其实有很多种方式来实现，自己监听滚动条时间，获取数据利用 addNode 方式自己添加节点都可以的

addNode到后面会很卡，主要是在查找父节点上
