### ISSUE TITLE
官网g了

### ISSUE THREAD

**Issue by FC0511** [zTree/zTree_v3#528]
官网g了

**Comment by zhangqigang-ones** [comment]
谢谢，是决定不再续费，已经关闭了。

**Comment by zTree** [comment]
谢谢，是决定不再续费，已经关闭了

**Comment by FC0511** [comment]
> 谢谢，是决定不再续费，已经关闭了

可惜了

**Comment by zTree** [comment]
一点儿也不可惜，该落幕了。技术陈旧，而且现在新的虚拟列表方式实现的更优化的树都很多了。 感谢你的支持。

**Comment by chengzhanpeng** [comment]
有什么其他的树形结构推荐的吗？

**Comment by zTree** [comment]
我就不推荐了，东西太多，框架也太多，找适合自己的吧

**Comment by terry8204** [comment]
@zTree 大佬，非常感谢一直这么好的组件，我们一直在用，目前我们遇到加载10000个节点问题，有啥好办法添加虚拟化吗？
项目要改太难了

**Comment by zTree** [comment]
> @zTree 大佬，非常感谢一直这么好的组件，我们一直在用，目前我们遇到加载10000个节点问题，有啥好办法添加虚拟化吗？ 项目要改太难了

这套代码不可能改成虚拟化的， 只能按照zTree 的方式，避免同时展示所有节点。 但如果你的节点分布不均匀，也很难处理，最后就只有分页展示（这些都已经不符合当今组件交互需求啦）

**Comment by genezx** [comment]
> 一点儿也不可惜，该落幕了。技术陈旧，而且现在新的虚拟列表方式实现的更优化的树都很多了。 感谢你的支持。

技术没有所谓陈旧一说，只是适用场景不同而已。
