### ISSUE TITLE
Ztree 

### ISSUE THREAD

**Issue by Bkrishnaveni** [zTree/zTree_v3#53]
Im using ztree plugin to show up an organization hireachy details i have a enhancement where i need to show a addDiyDom and addHoverDom both for a node....is it possible to show up like this.Right now to my ztree for a node i have an hover showing up add,remove,rename  now i need to show up an icon to the same node as adddiydom.Plz........ help me out ..

**Comment by moorthimnk** [comment]
when i trying dynamic tree and Ajax... there was a error occurred in getting child Node undefined error. i did you done in the page source but error occurring help me to solve the error....


index.html

<!DOCTYPE html>
<HTML>
    <HEAD>
        <TITLE> ZTREE DEMO - Async</TITLE>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <link rel="stylesheet" href="css/demo.css" type="text/css">
        <link rel="stylesheet" href="css/zTreeStyle.css" type="text/css">
        <script type="text/javascript" src="js/jquery-1.4.4.min.js"></script>
        <script type="text/javascript" src="js/jquery.ztree.core-3.5.js"></script>

        <SCRIPT type="text/javascript">
            var setting = {
                async: {
                    enable: true,
                    url: "asyncData/getNodes.php",
                    autoParam: ["id", "name=n", "level=lv"],
                    otherParam: {"otherParam": "zTreeAsyncTest"},
                    dataFilter: filter
                }
            };

            function filter(treeId, parentNode, childNodes) {
                alert(childNodes);
                alert(parentNode);
                alert(childNodes.length);
                if (!childNodes)
                    return null;
                for (var i = 0, l = childNodes.length; i < l; i++) {
                    childNodes[i].name = childNodes[i].name.replace(/\.n/g, '.');
                }
                return childNodes;
            }

            $(document).ready(function () {
                $.fn.zTree.init($("#treeDemo"), setting);
            });
        </SCRIPT>
    </HEAD>

    <BODY>


        <div class="content_wrap">
            <div class="zTreeDemoBackground left">
                <ul id="treeDemo" class="ztree"></ul>
            </div>
            <div class="right">
            </div>
        </div>


    </BODY>
</HTML>
![picture1](https://cloud.githubusercontent.com/assets/10783084/5987168/f6aab986-a943-11e4-860e-2eb8cc432b08.jpg)

and this is my output window
![s](https://cloud.githubusercontent.com/assets/10783084/5987174/2ca25b7a-a944-11e4-953f-2d583cc871dd.jpg)

**Comment by moorthimnk** [comment]
plz help me as soon as possible....

**Comment by liuzengjun** [comment]
Please mail to for help

hunter.z@263.net

 

发件人: moorthimnk [mailto:notifications@github.com] 
发送时间: 2015年1月31日 14:55
收件人: zTree/zTree_v3
主题: Re: [zTree_v3] Ztree (#53)

 

when i trying dynamic tree and Ajax... there was a error occurred in getting child Node undefined error. i did you done in the page source but error occurring help me to solve the error....

index.html

<!DOCTYPE html>


ZTREE DEMO - Async





    <SCRIPT type="text/javascript">
        var setting = {
            async: {
                enable: true,
                url: "asyncData/getNodes.php",
                autoParam: ["id", "name=n", "level=lv"],
                otherParam: {"otherParam": "zTreeAsyncTest"},
                dataFilter: filter
            }
        };
 
        function filter(treeId, parentNode, childNodes) {
            alert(childNodes);
            alert(parentNode);
            alert(childNodes.length);
            if (!childNodes)
                return null;
            for (var i = 0, l = childNodes.length; i < l; i++) {
                childNodes[i].name = childNodes[i].name.replace(/\.n/g, '.');
            }
            return childNodes;
        }
 
        $(document).ready(function () {
            $.fn.zTree.init($("#treeDemo"), setting);
        });
    </SCRIPT>
</HEAD>
 
<BODY>
 
 
    <div class="content_wrap">
        <div class="zTreeDemoBackground left">
            <ul id="treeDemo" class="ztree"></ul>
        </div>
        <div class="right">
        </div>
    </div>
 
 
</BODY>


 <https://cloud.githubusercontent.com/assets/10783084/5987168/f6aab986-a943-11e4-860e-2eb8cc432b08.jpg> picture1

and this is my output window
 <https://cloud.githubusercontent.com/assets/10783084/5987174/2ca25b7a-a944-11e4-953f-2d583cc871dd.jpg> s

**Comment by zTree** [comment]
I'm so sorry.... My job is so busy.

~~~
function filter(treeId, parentNode, childNodes)
~~~

The childNodes is data what you get from 'getNodes.php'.....please check the childNodes....

~~~
//output data
console.log(childNodes);
~~~
