### ISSUE TITLE
zTree支持查询节点功能吗

### ISSUE THREAD

**Issue by gaojianzhuang** [zTree/zTree_v3#71]
能否支持查询的api, 如果树的数据比较多，对于想快速定位到指定节点的场景，是否有指定的api支持。

**Comment by xiaoyifang** [comment]
支持
可以通过name查询
zTree.getNodesByFilter(filter)

**Comment by zTree** [comment]
感谢楼上的同志。。。最近忙项目， 木有来看。。抱歉了
