### ISSUE TITLE
jquery.ztree.all-3.5.js中不包含hidenodes的函数

### ISSUE THREAD

**Issue by xiaoyifang** [zTree/zTree_v3#73]
如题，
hidenodes的函数是exthide.js中的。
all.js中应该需要包含吧。

**Comment by zTree** [comment]
不包含。。因为这是比较不常用的扩展， 而且实在不想加大核心包的大小。。。以后重构可能会考虑直接使用 seajs 之类的， 让插件更灵活，更方便选择自己想要的功能
