### ISSUE TITLE
父子节点有设置别名idKey,pIdKey 那么对应的其它名称是否也能够设置别名如name？

### ISSUE THREAD

**Issue by kisshc** [zTree/zTree_v3#74]
父子节点有设置别名idKey,pIdKey 那么对应的其它名称是否也能够设置别名如name? 
如：可能我的id是DEPT_ID pid是DEPT_PARENT_ID 这两项都有折折 name 却是DEPT_NAME我没有找到解决方法nameKey也不正确请问有这个别名设置吗 ？

**Comment by zTree** [comment]
参考 setting.data.key
