### ISSUE TITLE
How to select a node via node_id ?

### ISSUE THREAD

**Issue by halimuygun** [zTree/zTree_v3#75]
Hello i tryed these code but dont working. How can i select node via node_id?

    var treeObj = $.fn.zTree.init($("#treeDemo"), setting, zNodes);
    var node = treeObj.getNodeByTId(2300);
    treeObj.selectNode(node);

**Comment by zTree** [comment]
~~~
treeObj.getNodeByParam('id', 2300);  // id is Number
treeObj.getNodeByParam('id', '2300');  // id is String
~~~
the tId is zTree's special attribute by self.
