### ISSUE TITLE
支持css3的icon属性

### ISSUE THREAD

**Issue by oncereply** [zTree/zTree_v3#76]
通过icon属性设置图标时,如果图标文件大小不是16px*16px,则会出现只有一部分的图标.
![qq 20150206160224](https://cloud.githubusercontent.com/assets/1457297/6076137/b3fc10fa-ae19-11e4-9fab-db3f7ba53be8.png)
css3有一个支持设置背景图片大小的background-size样式,可以指定背景图片大小,设置为"100% 100%",则背景图片会缩放至跟背景图片所在元素标签一样大小.
![qq 20150206160236](https://cloud.githubusercontent.com/assets/1457297/6076140/bfd3c31e-ae19-11e4-892b-42e7f99c8e08.png)
我查看了源码,view.makeNodeIcoStyle()方法中是这样写的:
```javascript
icoStyle.push("background:url(", icon, ") 0 0 no-repeat;");
```
能否改为如下代码以便更适应css3样式:
```javascript
icoStyle.push("background:url(", icon, ") 0 0 no-repeat;background-size:contain;");
```

**Comment by zTree** [comment]
这个你直接加到 zTreeStyle.css 里面就足够了， 本来这个 icon 的属性也不打算支持， 当初只是为了满足旧用户的。

.ztree li span.button

**Comment by oncereply** [comment]
这个icon还是很有用处的啊?我的树是因为要动态显示图标(用户上传的),如果不用路径的话,难不成要动态生成背景图片样式?

**Comment by zTree** [comment]
那你直接按照我上面说的情况 给 button 添加 特殊样式即可！   看来你的 图标太多了。。。。的确是特殊情况。

**Comment by oncereply** [comment]
我只是向您反应一下这种情景.我的做法是修改了js文件,因为makeNodeIcoStyle()方法最终是直接填充在style属性里,即便是修改css样式也是改变不了,会被background样式给覆盖,除非使用important.谢了~

**Comment by zTree** [comment]
修改 css 文件可以避免代码中反复去设置 inline 的 style，而且方便你以后修改； 现在因为 目前版本的 zTree 不会有什么改动，所以你修改源码没关系。。。否则会不利于升级。
只要你找到 zTreeStyle 里面对应的位置，在 background 后面多加上background-size，就应该是有效的了。。。仅仅是讨论如何处理更好一些。。。
