### ISSUE TITLE
你好,有个bug,不知道杂处理,找不到你构建node的html的地方,自己没法修复

### ISSUE THREAD

**Issue by csharpweb** [zTree/zTree_v3#77]
你好,我使用了view的nameishtml:true属性,发现在构建node节点html的时候出现了bug

在谷歌中,把name的html添加到a标签后面,而不是里面,这样就导致了选中节点时的样式是设置在上面的a标签上的,选中样式就只有半截,后面name的html显示出来的就没有节点选中样式,并且,onclick回调函数,点击name显示的地方触发不了,必须得点击前面的图标才能触发(图标是包含在前面那个a标签中的).

在IE8中,第一个a标签中的span里有name的html,是正确的,只是在a的后面,同级的再添加了一次name值,就是name传过来的html,前面那个a标签中还多了很多乱的a的标签,这样也导致了像谷歌浏览器中的那个问题.a同级的name遮挡住了a里面的name.

请回复一个,我好修正一下,把name定义的html直接添加到a中的span里面.

图片没法上传,很老火

**Comment by zTree** [comment]
请你对照一下 http://www.ztree.me/v3/demo.php#_107 这个Demo 的源码， 其实 nameishtml 仅仅是为了给 名称支持一些简单的 html 支持。。。不清楚你是怎么又把 name 添加到了 a标签后面？ 难道是你的节点没有正常的关闭？

**Comment by csharpweb** [comment]
我没有做额外操作,只是把nameishtml设为true,然后name传入的值是<a xxxx各种属性>节点名称</a>

**Comment by zTree** [comment]
检查一下你的 zTree 版本， 然后对照一下 我提供的 Demo。。。看看把你的数据放到 Demo 里面是否正常显示？

**Comment by csharpweb** [comment]
我仔细看了demo,用了nameishtml,直接传入data数据,不会出现闭合标签错误问题,但是,还是会出现name值 放在节点中的a之后,
然后我项目中的节点是异步请求的,会出现标签闭合错误,和name值放在节点中的a之后,

demo和我项目中的唯一的区别就是我的数据是异步请求的,但是这个也只能解决name值放在a后面的问题,

我使用nameishtml的情况是为了解决节点默认a是固定的,无法添加额外的属性,能不能把diy的节点属性和属性值加到节点自身的a上面去,这样就能解决大部分问题,这种问题我想是很普遍的,大神,请考虑下,或者请节点出处理节点的代码,我自己加上处理来实现.因为没时间仔细研究ztree的源码,请大神指导下,十分感谢.

**Comment by zTree** [comment]
请提供一下你的 节点数据， 利用 setTimeout 可以轻松实现异步添加数据，看看使用demo 做成异步的情况，是否还会出现 dom 错误的问题？？ 因为 是否异步获取数据 和 生成dom 不应该有冲突， 无论是否是否异步，都肯定要有了数据才会生成dom结构的。

另外， 你相对节点做额外处理， 可以利用 onNodeCreated 回调进行控制

**Comment by csharpweb** [comment]
感谢大神,用onnodecreated回调把额外属性添加到a上可以了,问题已解决,十分感谢.
