### ISSUE TITLE
可以做到直接显示到某个节点吗

### ISSUE THREAD

**Issue by explorerit** [zTree/zTree_v3#80]
搜索后，自动定位到这个节点，如果是父节点不想展开。expandNode是可以显示，但他也展开了子节点，同时非父节点不能定位到。 
求解，谢谢!

**Comment by zTree** [comment]
用 selectNode 方法选中节点 应该可以实现你需要的功能

**Comment by explorerit** [comment]
如果在滚动框里，无父节点的根节点貌似不能自动回滚以显示出来

**Comment by explorerit** [comment]
这应该是个bug，在代码里如下改就可以了
![1](https://cloud.githubusercontent.com/assets/8748522/6681111/f332f004-cc9b-11e4-8e4d-637b1717b07f.jpg)

**Comment by zTree** [comment]
等我抽空检查一下，再做答复

**Comment by zTree** [comment]
你好， 我使用 simpleData.html 这个Demo 做测试， 把 ul 设置为 height: 50px; 同时把好几个叶子节点都设置 pId=0 增加根节点数量， 然后利用 selectNode 方法完全没有问题呀，可以正常滚动到可视区域内的
