### ISSUE TITLE
请问init方法有没回调

### ISSUE THREAD

**Issue by fgjun** [zTree/zTree_v3#81]
请问init方法有没回调，我的代码如下：
var setting = {
			async: {
				enable: true,
				url:"${pageContext.request.contextPath}/baikeType/getNode.html",
				autoParam:["id"],
				dataFilter: zTreefilter
			},
			view:{
				showIcon :false,
				showLine :false
			},
			callback: {
				onAsyncSuccess: function(event, treeId, treeNode, msg){
					//alert(msg);
				}
			}
		};
function zTreefilter(treeId, parentNode, responseData) {
			if (!responseData) return null;
			for (var i=0, l=responseData.length; i<l; i++) {
				responseData[i].name = responseData[i].text;
				responseData[i].isParent = responseData[i].hasMenu;
				responseData[i].icon = "<%=staticUrl%>/front/images/bb.png";
				responseData[i].iconOpen = "<%=staticUrl%>/front/images/aa.png";
				responseData[i].iconClose = "<%=staticUrl%>/front/images/bb.png";
				responseData[i].url = "${pageContext.request.contextPath}/baike/list.html?baikeTypeId="+responseData[i].id;
				responseData[i].target = "_self";
			}
			return responseData;
		}
function refreshNode(nodeIds) {
			//alert(2222);
			if(!nodeIds){
				return;
			}
			var nodeIdsArr = nodeIds.split('/');
			if(nodeIdsArr.length<2){
				return;
			}
			var zTree = $.fn.zTree.getZTreeObj("treeDemo"),
			type = 'refresh',
			silent = false;
			for (var i=0, l=nodeIdsArr.length; i<l; i++) {
				zTree.reAsyncChildNodes(zTree.getNodeByTId(nodeIdsArr[i]), type, silent);
				if (!silent) zTree.selectNode(nodeIdsArr[i]);
			}
		}
		$(document).ready(function(){
			$.fn.zTree.init($("#treeDemo"), setting);
			setTimeout("refreshNode('${baikeType.codePath}')",2000);
			//refreshNode('${baikeType.codePath}');
		});

上面的代码就是想，已加载页面就展开树的某个节点

**Comment by zTree** [comment]
你好，
使用了 async 的异步模式后， 利用 onAsyncSuccess 当作回调就是了




zTreeAPI     http://www.ztree.me
 
 发件人： fgjun发送时间： 2015-03-20 09:19收件人： zTree/zTree_v3主题： [zTree_v3] 请问init方法有没回调 (#81)请问init方法有没回调，我的代码如下：

var setting = {

            async: {

                enable: true,

                url:"${pageContext.request.contextPath}/baikeType/getNode.html",

                autoParam:["id"],

                dataFilter: zTreefilter

            },

            view:{

                showIcon :false,

                showLine :false

            },

            callback: {

                onAsyncSuccess: function(event, treeId, treeNode, msg){

                    //alert(msg);

                }

            }

        };

function zTreefilter(treeId, parentNode, responseData) {

            if (!responseData) return null;

            for (var i=0, l=responseData.length; i
                responseData[i].name = responseData[i].text;

                responseData[i].isParent = responseData[i].hasMenu;

                responseData[i].icon = "/front/images/bb.png";

                responseData[i].iconOpen = "<%=staticUrl%>/front/images/aa.png";

                responseData[i].iconClose = "<%=staticUrl%>/front/images/bb.png";

                responseData[i].url = "${pageContext.request.contextPath}/baike/list.html?baikeTypeId="+responseData[i].id;

                responseData[i].target = "_self";

            }

            return responseData;

        }

function refreshNode(nodeIds) {

            //alert(2222);

            if(!nodeIds){

                return;

            }

            var nodeIdsArr = nodeIds.split('/');

            if(nodeIdsArr.length<2){

                return;

            }

            var zTree = $.fn.zTree.getZTreeObj("treeDemo"),

            type = 'refresh',

            silent = false;

            for (var i=0, l=nodeIdsArr.length; i<l; i++) {

                zTree.reAsyncChildNodes(zTree.getNodeByTId(nodeIdsArr[i]), type, silent);

                if (!silent) zTree.selectNode(nodeIdsArr[i]);

            }

        }

        $(document).ready(function(){

            $.fn.zTree.init($("#treeDemo"), setting);

            setTimeout("refreshNode('${baikeType.codePath}')",2000);

            //refreshNode('${baikeType.codePath}');

        });

上面的代码就是想，已加载页面就展开树的某个节点

**Comment by zTree** [comment]
使用了 async 的异步模式后， 利用 onAsyncSuccess 当作回调就是了

**Comment by fgjun** [comment]
需求：加载页面的时候，树想自动展开定位到某子节点，但是这时还在初始化树的父节点（ajax形式）
这个怎么写代码。请指导！

**Comment by zTree** [comment]
对于你需要逐级自动加载子节点的需求， 系统更不可能给出标准的初始化完毕 的事件，因为不同用户的需求千差万别。。。你这就是利用 onAsyncSuccess 捕获每个父节点加载子节点结束的事件，同时让子节点中必要的父节点展开并加载它的子节点。。。当满足你需要的子节点获得后， 触发你需要的js 方法即可。
逐级加载子节点 请参考 Demo  http://www.ztree.me/v3/demo.php#_512
