### ISSUE TITLE
How can i use single root?

### ISSUE THREAD

**Issue by halimuygun** [zTree/zTree_v3#82]
Hello,
i want to use single root. when i drag-drop folders they can be a root. but i dont want it.
i used : "dropRoot:false" and "childOuter:false" but its dont working.

i need:
c:\ (root)
-- Folder (draggable in root)
----- File (draggable in root)
-- Folder (draggable in root)

i dont want it:
Folder (root ??)
--- File
c:\ (root)
--- Folder

when i used childOuter:false
File (childOuter, dont work on sub-sub items ??)
c:\ (root)
----- Folder (draggable)
----- Folder (draggable)

**Comment by zTree** [comment]
It's so easy:

please set the 'setting.edit.drag.inner'

```
setting.edit.drag.inner = function(treeId, nodes, targetNode) {
    return !!targetNode
}
```

**Comment by halimuygun** [comment]
Thank you! Good job ;)

**Comment by halimuygun** [comment]
Hello, 
Same problem: childOuter:false.
Your code is working on first sub items (on root folders) but sub-sub items (files, folders) can be root..

File
File
c:\ (root)
----- Folder
----- Folder

**Comment by zTree** [comment]
I'm so sorry....

```
setting.edit.drag.prev= function(treeId, nodes, targetNode) {
    return targetNode.level > 0
}
setting.edit.drag.next= function(treeId, nodes, targetNode) {
    return targetNode.level > 0
}

```

**Comment by halimuygun** [comment]
Thank you so much.. Working now.
