### ISSUE TITLE
请问在一些回调函数里，能否加入对promise的支持？

### ISSUE THREAD

**Issue by hwoarangzk** [zTree/zTree_v3#83]
比如beforeDrop，我拖拽一个节点到别的节点里，释放鼠标，这时候我可能会调用一个后台的cgi，如果返回的结果成功，我return true，如果失败，我return false从而不执行drop。类似的还有onRename等。我现在在代码里试过return一个promise，没有用的。谢谢~

**Comment by zTree** [comment]
对于需要异步处理的过程， 请在 beforeDrop 或 beforeRename、beforeRemove 里面 return false; 同时保存好对应的数据， 发起ajax 请求， 等 ajax 的success 回调执行时，利用 zTree 提供的一些方法操作节点（例如 removeNode、moveNode 等）

**Comment by hwoarangzk** [comment]
我试过在before等函数里return promise，在这些promise的done和fail回调里来return true和false，但是没有用。如果是直接先return false，然后再发起异步函数调用，等回调回来的时候再来做rename等操作，我觉得视觉效果上会有问题，可能会对用户造成迷惑

**Comment by zTree** [comment]
抱歉， 目前版本不会增加对这个的支持， 但我会考虑在下一次大的结构重新改版时， 加入众多新特性的

**Comment by hwoarangzk** [comment]
期待：）

**Comment by snowchenlei** [comment]
几年过去了，新特性还在展望中

**Comment by zTree** [comment]
> 几年过去了，新特性还在展望中

感谢厚爱，真要有时间，应该是完全重新做一套了。 目前这版本样式太老旧，dom结构也不行了，js 代码也太古老。。。都应该换新的了
