### ISSUE TITLE
editName的时候，如果想给input添加一些属性，比如maxlength，有接口么？

### ISSUE THREAD

**Issue by hwoarangzk** [zTree/zTree_v3#86]
RT，如果没接口，应该怎么添加呢？如果还想加一些别的自定义属性给dom该怎么弄？谢谢

**Comment by zTree** [comment]
抱歉， 如果使用 zTree 默认的input 只能是自己利用 js 找到这个input 去设置。。。或者直接修改源码了。
再或者是自己添加 input
