### ISSUE TITLE
关于icon的问题

### ISSUE THREAD

**Issue by nodejsissb** [zTree/zTree_v3#87]
默认的icon代表的是节点的打开和关闭状态，但是有些人会认为代表的是是否有子节点，按照这个逻辑来看整棵树会感觉有点奇怪，所以作者可以考虑在按照这个逻辑写一下，然后可配置

**Comment by zTree** [comment]
你好， 目前 icon 全部都可以自行替换 ，直接修改css 即可。。。另外参考 Demo ，还有其他扩展 图标的方式
