### ISSUE TITLE
Callback for node selected

### ISSUE THREAD

**Issue by bjaanes** [zTree/zTree_v3#93]
Currently, I am using the callback for onClick, but it doesn't trigger if you move a node. However, if you move a node with drag and drop, you also select the node.

I need to do some special stuff every time a node has been clicked, and there is no smooth way to do that now.

**Comment by zTree** [comment]
I think that you don't need the onClick, but you need the onSelected.....Now, zTree has not the  onSelected callback.  And if you edit the node, it will be selected too. 

So, if you need the  onSelected... I will add this callback for you!

**Comment by bjaanes** [comment]
Thank you, that would be perfect! :)

**Comment by zTree** [comment]
I'm so sorry, I haven't add this at last week....I'will modify it in this week.

**Comment by bjaanes** [comment]
That is fine, thank you! :)

**Comment by zTree** [comment]
Hi....I'm so sorry for push this version too late.

Please pull the lastest version.  I add the callback:  onSelected / onUnSelected

When you use it when zTree was edited....the onSelected will be trigger many times... Please try it, and if you have any question , tell me.

````
onSelected: function(event, treeId, treeNode);
onUnSelected: function(event, treeId, treeNode);
````

**Comment by bjaanes** [comment]
This appears to work fine! I like it!

Thank you very much! :)

When do you think this will go into a new release? 3.5.18?

**Comment by zTree** [comment]
I have push  the lastest code(v3.5.18) to github.  add  demo: 'awesome style'.  (thanks to mikkelking)
