### ISSUE TITLE
Official bower package

### ISSUE THREAD

**Issue by bjaanes** [zTree/zTree_v3#94]
It would be very nice if this repository could provide an official bower package that follows the releases done here. I don't think it would be too much work to get that done.

http://bower.io/docs/creating-packages/

**Comment by zTree** [comment]
thank you very much.  I'm not going to go around promoting this plugin, because I was going to be redone.

**Comment by bjaanes** [comment]
Are you making a new zTree? Anything you can tell me about it? :)

**Comment by zTree** [comment]
I think zTree is not good enough. I want to remake it. But it hasn't started.

**Comment by mikkelking** [comment]
There is a bower package already called zTree. Happy to help with v4

**Comment by bjaanes** [comment]
The existing bower packages are not official and are horrible outdated.

**Comment by mikkelking** [comment]
I just did a bower install zTree and got this
/*
 * JQuery zTree core v3.5.17
 * http://zTree.me/
 *
 * Copyright (c) 2010 Hunter.z
 *
 * Licensed same as jquery - MIT License
 * http://www.opensource.org/licenses/mit-license.php
 *
 * email: hunter.z@263.net
 * Date: 2014-05-08
 */

That is the latest version - are you getting it from somewhere else?
AFAIK Zhang is the original author, right?

**Comment by bjaanes** [comment]
I did not get the appropriate bower.json file with it. The one that states dependencies and just as important the main file. The main file is need for use with a lot of build scripts.
