### ISSUE TITLE
初始未展开的情况下通过js设置叶子节点的checked属性后，父节点没有关联更新显示

### ISSUE THREAD

**Issue by front-thinking** [zTree/zTree_v3#95]
初始未展开的情况下通过js设置叶子节点的checked属性后，父节点没有关联更新显示
PS：数展开后或者展开后在收缩后，js设置叶子节点的checked都会关联并更新显示父子节点。（注：经检查和多人反复确定，updateNode函数调用正确、setting.check及对应子配置均无误。）

为了解决这个bug，目前的做法是在所有节点数据异步回来后，在js里手动展开和收缩了一次树的所有节点（即onAsyncSuccess中执行了treeObj.expandFlag(true)和treeObj.expandFlag(false)）。

不知道是不是个bug。

**Comment by zTree** [comment]
为何不使用 checkNode 方法呢？

**Comment by front-thinking** [comment]
感谢   你的这个方法很好的解决了这个问题    还是使用的不太熟练  ！！！
之前那么处理的确看起来笨拙   不过的确发现了这个问题
再次感谢！
