### ISSUE TITLE
建议在 data.key{} 中增加 isParent 键值

### ISSUE THREAD

**Issue by dusdong** [zTree/zTree_v3#97]
既然 treeNode 可以直接设置 IsParent 的值，那么，建议：

在 data.key{} 中增加 isParent 键值：
1、如果设置了此键值，以此作为是否有下级节点的依据。
2、如果没有设置，按照目前代码判断。

**Comment by zTree** [comment]
你这是希望使用 其他键值 替换 isParent 么？

**Comment by dusdong** [comment]
应用场景：
一棵树上的节点明确的分为两类：文件夹和文件。不论该文件夹下面是否存在文件，该节点都是文件夹。

目前存在的问题：
虽然可以人为的指定 IsParent=true，但是当该文件夹下面所有的文件都被删除的时候，zTree会自动把该文件夹的 IsParent 设置为 false。

解决方案：
方法1、自定义键值。zTree 在检查该 node 是否是『父节点』的时候，先检查『自定义的键值』。如果是true，就认为他是父节点；如果是 false，继续执行原代码。

方法2、zTree可以保存该节点的初始 IsParent，如果初始 IsParent = true，即使子节点全部删除也不影响。

或许方法2更优雅一些？

**Comment by zTree** [comment]
那我明白了， 你这个需求修改 key 是没有意义的， 而应该去看 setting.data.keep.parent / leaf 这两个设置
